// 80 fictional B2B customers for the collections, dunning & dispute workflow.
// Hand-written so Neo's ranking + tone calibration has realistic behavioral signals
// and CRM context to reference.
//
// Source of truth: docs/handoff/collections/04-data-model.md § "seed-customers.ts".
// Hero customers (4) are verbatim per the spec — do not edit without also updating
// the demo script (docs/handoff/collections/05-demo-script.md) and the cases/disputes
// seeds that reference these IDs.
//
// Tier mix: ~10 strategic, ~50 standard, ~20 long-tail.
// ~30 customers have crm data populated (top-of-worklist + hero scenarios).

import type { Customer, CustomerId } from "./types"

export const SEED_CUSTOMERS: Customer[] = [
  // ════════════════════════════════════════════════════════════════════
  // Hero customers (4) — referenced by name in cases + disputes + demo
  // ════════════════════════════════════════════════════════════════════
  {
    id: "cust-westpoint-mfg",
    name: "Westpoint Manufacturing",
    accountNumber: "WPT-04451",
    domain: "westpoint-mfg.com",
    primaryContactName: "Maria Gonzalez",
    primaryContactEmail: "maria.gonzalez@westpoint-mfg.com",
    primaryContactRole: "AR Manager",
    paymentTermsDays: 30,
    industry: "industrial-supplies",
    behavior: {
      averageDaysToPay: 41.5,
      monthsOnTimeHistory: 12,
      silentDays: 14,
      breachedPromiseCount: 0,
      disputeCount: 0,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 480000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-12",
      lastConversationSummary:
        "Quarterly check-in. Maria mentioned ERP migration in Q3 — possible payment delays.",
    },
  },
  {
    id: "cust-atlantic-logistics",
    name: "Atlantic Logistics LLC",
    accountNumber: "ATL-07892",
    domain: "atlantic-logistics.com",
    primaryContactName: "Maria Gonzalez",
    primaryContactEmail: "maria@atlantic-logistics.com",
    paymentTermsDays: 30,
    industry: "logistics",
    behavior: {
      averageDaysToPay: 38,
      monthsOnTimeHistory: 8,
      breachedPromiseCount: 1,
      disputeCount: 0,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 280000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-22",
      lastConversationSummary:
        "Follow-up on April past-due. Maria committed to wire by May 9.",
    },
  },
  {
    id: "cust-pacific-distribution",
    name: "Pacific Distribution Co",
    accountNumber: "PAC-03128",
    domain: "pacific-dist.com",
    primaryContactName: "Robert Kim",
    primaryContactEmail: "rkim@pacific-dist.com",
    paymentTermsDays: 30,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 56,
      monthsOnTimeHistory: 0,
      silentDays: 28,
      breachedPromiseCount: 2,
      disputeCount: 0,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 340000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-02-19",
      lastConversationSummary:
        "Robert acknowledged February past-due, promised batch payment 'soon'. No follow-through.",
    },
  },
  {
    id: "cust-atlantic-industrial",
    name: "Atlantic Industrial",
    accountNumber: "ATL-IND-09921",
    domain: "atlantic-industrial.com",
    primaryContactName: "Maria Gonzalez",
    primaryContactEmail: "maria.gonzalez@atlantic-industrial.com",
    paymentTermsDays: 30,
    industry: "industrial",
    behavior: {
      averageDaysToPay: 35,
      monthsOnTimeHistory: 18,
      disputeCount: 1,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 620000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-05-08",
      lastConversationSummary:
        "Maria confirmed PO-1208 receipt; followed up about 200-vs-197 unit discrepancy.",
    },
  },

  // ════════════════════════════════════════════════════════════════════
  // Strategic accounts (~10 total including atlantic-industrial above)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "cust-mariner-aerospace",
    name: "Mariner Aerospace Components",
    accountNumber: "MAR-AERO-11240",
    domain: "marineraerospace.com",
    primaryContactName: "Linda Park",
    primaryContactEmail: "linda.park@marineraerospace.com",
    primaryContactRole: "AP Director",
    paymentTermsDays: 45,
    industry: "aerospace",
    behavior: {
      averageDaysToPay: 43,
      monthsOnTimeHistory: 24,
      disputeCount: 0,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 1240000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-05-04",
      lastConversationSummary:
        "QBR — Linda confirmed FY27 expansion plan, $2M+ pipeline.",
    },
  },
  {
    id: "cust-northstar-energy",
    name: "Northstar Energy Solutions",
    accountNumber: "NS-ENRG-22781",
    domain: "northstar-energy.com",
    primaryContactName: "Daniel Wilcox",
    primaryContactEmail: "daniel.wilcox@northstar-energy.com",
    primaryContactRole: "VP Finance",
    paymentTermsDays: 45,
    industry: "energy",
    behavior: {
      averageDaysToPay: 41,
      monthsOnTimeHistory: 22,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 980000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-05-01",
      lastConversationSummary:
        "Renewal conversation — Daniel locked in 18-month contract through Q4 2027.",
    },
  },
  {
    id: "cust-cypress-pharma",
    name: "Cypress Pharmaceuticals Inc",
    accountNumber: "CYP-PHARM-08819",
    domain: "cypress-pharma.com",
    primaryContactName: "Eleanor Babcock",
    primaryContactEmail: "ebabcock@cypress-pharma.com",
    paymentTermsDays: 30,
    industry: "pharmaceuticals",
    behavior: {
      averageDaysToPay: 28,
      monthsOnTimeHistory: 24,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 860000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-30",
      lastConversationSummary:
        "Eleanor flagged a potential FDA-cycle slowdown in Q3; no AR impact expected.",
    },
  },
  {
    id: "cust-vanguard-defense",
    name: "Vanguard Defense Systems",
    accountNumber: "VG-DEF-44120",
    domain: "vanguard-defense.com",
    primaryContactName: "Otis Wilkerson",
    primaryContactEmail: "otis.wilkerson@vanguard-defense.com",
    primaryContactRole: "Controller",
    paymentTermsDays: 45,
    industry: "defense",
    behavior: {
      averageDaysToPay: 44,
      monthsOnTimeHistory: 24,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 1450000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-25",
      lastConversationSummary:
        "Otis confirmed funding for FY27 contract amendment; payment cycle unchanged.",
    },
  },
  {
    id: "cust-keystone-grocers",
    name: "Keystone Grocers",
    accountNumber: "KEY-GRC-19022",
    domain: "keystone-grocers.com",
    primaryContactName: "Marisol Aguilar",
    primaryContactEmail: "marisol@keystone-grocers.com",
    primaryContactRole: "AP Manager",
    paymentTermsDays: 30,
    industry: "retail-grocery",
    behavior: {
      averageDaysToPay: 27,
      monthsOnTimeHistory: 24,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 720000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-05-06",
      lastConversationSummary:
        "Weekly payment-run cadence confirmed; Marisol asked about consolidated billing.",
    },
  },
  {
    id: "cust-summit-healthcare",
    name: "Summit Healthcare Group",
    accountNumber: "SH-CARE-30144",
    domain: "summithealthcare.com",
    primaryContactName: "Aditi Sharma",
    primaryContactEmail: "aditi.sharma@summithealthcare.com",
    primaryContactRole: "AP Director",
    paymentTermsDays: 45,
    industry: "healthcare",
    behavior: {
      averageDaysToPay: 47,
      monthsOnTimeHistory: 20,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 880000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-18",
      lastConversationSummary:
        "Aditi confirmed Q2 supply expansion; no AR concerns.",
    },
  },
  {
    id: "cust-blueridge-rail",
    name: "Blue Ridge Rail Services",
    accountNumber: "BR-RAIL-55288",
    domain: "blueridgerail.com",
    primaryContactName: "Marquis DuBois",
    primaryContactEmail: "mdubois@blueridgerail.com",
    paymentTermsDays: 60,
    industry: "transportation",
    behavior: {
      averageDaysToPay: 58,
      monthsOnTimeHistory: 18,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 1100000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-29",
      lastConversationSummary:
        "Marquis confirmed Q3 fleet maintenance schedule; large order incoming.",
    },
  },
  {
    id: "cust-meridian-financial",
    name: "Meridian Financial Services",
    accountNumber: "MER-FIN-07712",
    domain: "meridianfinancial.com",
    primaryContactName: "Augustine Holloway",
    primaryContactEmail: "augustine.holloway@meridianfinancial.com",
    primaryContactRole: "AP Lead",
    paymentTermsDays: 30,
    industry: "financial-services",
    behavior: {
      averageDaysToPay: 26,
      monthsOnTimeHistory: 24,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 540000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-05-10",
      lastConversationSummary:
        "Augustine reviewed Q2 invoicing summary; payment cadence smooth.",
    },
  },
  {
    id: "cust-orionstar-software",
    name: "Orionstar Software Solutions",
    accountNumber: "ORI-SW-66104",
    domain: "orionstarsoft.com",
    primaryContactName: "Emiliana Ruszowski",
    primaryContactEmail: "emiliana@orionstarsoft.com",
    paymentTermsDays: 30,
    industry: "technology",
    behavior: {
      averageDaysToPay: 27,
      monthsOnTimeHistory: 24,
      relationshipTier: "strategic",
      last6MonthsOrderVolume: 680000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-05-12",
      lastConversationSummary:
        "Emiliana confirmed multi-year licensing renewal; AP cadence unchanged.",
    },
  },

  // ════════════════════════════════════════════════════════════════════
  // Standard accounts with CRM data (~20)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "cust-evergreen-paper",
    name: "Evergreen Paper Products",
    accountNumber: "EVR-PAP-13355",
    domain: "evergreenpaper.com",
    primaryContactName: "Daniel Ofori",
    primaryContactEmail: "daniel.ofori@evergreenpaper.com",
    paymentTermsDays: 30,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 33,
      monthsOnTimeHistory: 14,
      silentDays: 6,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 240000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-15",
      lastConversationSummary:
        "Daniel acknowledged March balance, mentioned cash-flow tightness.",
    },
  },
  {
    id: "cust-summitline-mfg",
    name: "Summitline Manufacturing",
    accountNumber: "SUM-MFG-21884",
    domain: "summitlinemfg.com",
    primaryContactName: "Robert Kershaw",
    primaryContactEmail: "robert.kershaw@summitlinemfg.com",
    paymentTermsDays: 30,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 34,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 320000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-09",
      lastConversationSummary:
        "Robert confirmed receipt of April invoices; standard cadence.",
    },
  },
  {
    id: "cust-coastal-foods",
    name: "Coastal Foods Wholesale",
    accountNumber: "CST-FOOD-29011",
    domain: "coastalfoodswh.com",
    primaryContactName: "Yuki Tanaka",
    primaryContactEmail: "yuki.tanaka@coastalfoodswh.com",
    paymentTermsDays: 30,
    industry: "food-distribution",
    behavior: {
      averageDaysToPay: 31,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 290000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-20",
      lastConversationSummary:
        "Yuki confirmed cold-chain delivery cadence; no AR issues.",
    },
  },
  {
    id: "cust-driftwood-hospitality",
    name: "Driftwood Hospitality Group",
    accountNumber: "DRF-HOSP-44023",
    domain: "driftwoodhg.com",
    primaryContactName: "Elena Kovac",
    primaryContactEmail: "elena.kovac@driftwoodhg.com",
    paymentTermsDays: 45,
    industry: "hospitality",
    behavior: {
      averageDaysToPay: 46,
      monthsOnTimeHistory: 10,
      silentDays: 9,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 380000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-26",
      lastConversationSummary:
        "Elena flagged that two properties are switching AP processors in May.",
    },
  },
  {
    id: "cust-stonebridge-construction",
    name: "Stonebridge Construction",
    accountNumber: "STN-CON-38422",
    domain: "stonebridgeconst.com",
    primaryContactName: "Gabriela Mendez",
    primaryContactEmail: "gabriela.mendez@stonebridgeconst.com",
    paymentTermsDays: 60,
    industry: "construction",
    behavior: {
      averageDaysToPay: 63,
      monthsOnTimeHistory: 8,
      breachedPromiseCount: 1,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 420000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-03-29",
      lastConversationSummary:
        "Gabriela tied April payments to project milestone; expected mid-May.",
    },
  },
  {
    id: "cust-cascade-chemicals",
    name: "Cascade Chemicals",
    accountNumber: "CSC-CHM-91044",
    domain: "cascadechem.com",
    primaryContactName: "Vinod Reddy",
    primaryContactEmail: "vinod.reddy@cascadechem.com",
    paymentTermsDays: 30,
    industry: "chemicals",
    behavior: {
      averageDaysToPay: 42,
      monthsOnTimeHistory: 6,
      silentDays: 11,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 215000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-11",
      lastConversationSummary:
        "Vinod flagged HSE compliance work delaying invoicing approvals.",
    },
  },
  {
    id: "cust-pinnacle-logistics",
    name: "Pinnacle Logistics Partners",
    accountNumber: "PIN-LOG-50221",
    domain: "pinnaclelog.com",
    primaryContactName: "Marcus Whitfield",
    primaryContactEmail: "marcus.whitfield@pinnaclelog.com",
    paymentTermsDays: 60,
    industry: "logistics",
    behavior: {
      averageDaysToPay: 59,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 360000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-23",
      lastConversationSummary:
        "Marcus confirmed monthly bundled payment cadence is unchanged.",
    },
  },
  {
    id: "cust-thornwood-furniture",
    name: "Thornwood Furniture Co",
    accountNumber: "THW-FRN-77810",
    domain: "thornwoodfurn.com",
    primaryContactName: "Jasper Lin",
    primaryContactEmail: "jasper.lin@thornwoodfurn.com",
    paymentTermsDays: 60,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 67,
      monthsOnTimeHistory: 4,
      silentDays: 22,
      breachedPromiseCount: 1,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 410000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-03-15",
      lastConversationSummary:
        "Jasper requested 30-day grace on March invoices; no follow-up since.",
    },
  },
  {
    id: "cust-clearwater-pharma",
    name: "Clearwater Pharmaceuticals",
    accountNumber: "CLR-PHM-14523",
    domain: "clearwaterpharma.com",
    primaryContactName: "Bryce Calderón",
    primaryContactEmail: "bryce.calderon@clearwaterpharma.com",
    paymentTermsDays: 30,
    industry: "pharmaceuticals",
    behavior: {
      averageDaysToPay: 29,
      monthsOnTimeHistory: 22,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 295000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-05-02",
      lastConversationSummary:
        "Bryce confirmed standing cadence; April balance paid in full.",
    },
  },
  {
    id: "cust-harborside-metals",
    name: "Harborside Metals",
    accountNumber: "HBR-MTL-66338",
    domain: "harborsidemetals.com",
    primaryContactName: "Devorah Klein",
    primaryContactEmail: "devorah.klein@harborsidemetals.com",
    paymentTermsDays: 60,
    industry: "metals",
    behavior: {
      averageDaysToPay: 71,
      monthsOnTimeHistory: 5,
      silentDays: 18,
      breachedPromiseCount: 1,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 480000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-07",
      lastConversationSummary:
        "Devorah cited tight cash; promised batch payment for April invoices in early May.",
    },
  },
  {
    id: "cust-northeast-supply",
    name: "Northeast Supply Group",
    accountNumber: "NES-SUP-22090",
    domain: "nesupply.com",
    primaryContactName: "Linda Park",
    primaryContactEmail: "linda.park@nesupply.com",
    paymentTermsDays: 30,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 29,
      monthsOnTimeHistory: 20,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 310000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-05-05",
      lastConversationSummary:
        "Linda confirmed monthly batch payments are still on schedule.",
    },
  },
  {
    id: "cust-aspenglow-resorts",
    name: "Aspenglow Resorts",
    accountNumber: "ASP-RES-40119",
    domain: "aspenglowresorts.com",
    primaryContactName: "Tobias Reinhart",
    primaryContactEmail: "tobias.reinhart@aspenglowresorts.com",
    paymentTermsDays: 45,
    industry: "hospitality",
    behavior: {
      averageDaysToPay: 48,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 295000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-17",
      lastConversationSummary:
        "Tobias confirmed Q2 booking volume strong; no AR risk.",
    },
  },
  {
    id: "cust-bristol-printing",
    name: "Bristol Commercial Printing",
    accountNumber: "BRS-PRT-31509",
    domain: "bristolprint.com",
    primaryContactName: "Shawna Mendel",
    primaryContactEmail: "shawna.mendel@bristolprint.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 44,
      monthsOnTimeHistory: 4,
      silentDays: 16,
      breachedPromiseCount: 1,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 145000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-03-22",
      lastConversationSummary:
        "Shawna missed a March 30 promise; needs follow-up.",
    },
  },
  {
    id: "cust-cedarvalley-retail",
    name: "Cedar Valley Retail Group",
    accountNumber: "CED-RET-58270",
    domain: "cedarvalleyretail.com",
    primaryContactName: "Booker Tatum",
    primaryContactEmail: "booker.tatum@cedarvalleyretail.com",
    paymentTermsDays: 45,
    industry: "retail",
    behavior: {
      averageDaysToPay: 49,
      monthsOnTimeHistory: 12,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 380000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-21",
      lastConversationSummary:
        "Booker confirmed multi-store batched remits; one location late.",
    },
  },
  {
    id: "cust-magnolia-dairy",
    name: "Magnolia Dairy Cooperative",
    accountNumber: "MAG-DRY-71109",
    domain: "magnoliadairy.coop",
    primaryContactName: "Eleanor Pope",
    primaryContactEmail: "eleanor.pope@magnoliadairy.coop",
    paymentTermsDays: 30,
    industry: "food-distribution",
    behavior: {
      averageDaysToPay: 32,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 215000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-28",
      lastConversationSummary:
        "Eleanor flagged Q3 milk-price pressure; payments unaffected so far.",
    },
  },
  {
    id: "cust-merrybrook-bakery",
    name: "Merrybrook Bakery Group",
    accountNumber: "MRB-BKR-19877",
    domain: "merrybrookbakery.com",
    primaryContactName: "Calvin Pendleton",
    primaryContactEmail: "calvin.pendleton@merrybrookbakery.com",
    paymentTermsDays: 30,
    industry: "food-distribution",
    behavior: {
      averageDaysToPay: 18,
      monthsOnTimeHistory: 24,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 160000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-05-09",
      lastConversationSummary:
        "Calvin confirmed weekly remit cadence; new bakery opening in June.",
    },
  },
  {
    id: "cust-twinpines-lumber",
    name: "Twin Pines Lumber",
    accountNumber: "TWP-LUM-26780",
    domain: "twinpineslumber.com",
    primaryContactName: "Casey Birdwell",
    primaryContactEmail: "casey.birdwell@twinpineslumber.com",
    paymentTermsDays: 30,
    industry: "building-materials",
    behavior: {
      averageDaysToPay: 24,
      monthsOnTimeHistory: 22,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 240000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-05-07",
      lastConversationSummary:
        "Casey confirmed early-payment pattern; offered to consolidate POs.",
    },
  },
  {
    id: "cust-foundry-autoparts",
    name: "Foundry Auto Parts",
    accountNumber: "FND-AUT-89200",
    domain: "foundryautoparts.com",
    primaryContactName: "Damaris Schroeder",
    primaryContactEmail: "damaris.schroeder@foundryautoparts.com",
    paymentTermsDays: 45,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 47,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 295000,
    },
    crm: {
      accountOwner: "Priya Raman",
      lastConversationAt: "2026-04-13",
      lastConversationSummary:
        "Damaris flagged a single warehouse switching AP; expects 1-week delay.",
    },
  },
  {
    id: "cust-greatlakes-distribution",
    name: "Great Lakes Distribution",
    accountNumber: "GLK-DST-77011",
    domain: "greatlakesdist.com",
    primaryContactName: "Henry Wojcik",
    primaryContactEmail: "henry.wojcik@greatlakesdist.com",
    paymentTermsDays: 60,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 53,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 410000,
    },
    crm: {
      accountOwner: "James Park",
      lastConversationAt: "2026-04-19",
      lastConversationSummary:
        "Henry confirmed 3-tranche payment schedule per master agreement.",
    },
  },

  // ════════════════════════════════════════════════════════════════════
  // Standard accounts without CRM data (~30)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "cust-ironforge-tools",
    name: "Ironforge Tooling",
    accountNumber: "IRF-TLS-30992",
    domain: "ironforgetools.com",
    primaryContactName: "Caitlin Ramos",
    primaryContactEmail: "caitlin.ramos@ironforgetools.com",
    paymentTermsDays: 30,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 28,
      monthsOnTimeHistory: 20,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 165000,
    },
  },
  {
    id: "cust-meridian-electric",
    name: "Meridian Electric Supply",
    accountNumber: "MER-ELC-49011",
    domain: "meridianelectric.com",
    primaryContactName: "Sasha Volkov",
    primaryContactEmail: "sasha.volkov@meridianelectric.com",
    paymentTermsDays: 30,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 30,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 180000,
    },
  },
  {
    id: "cust-blueridge-textiles",
    name: "Blue Ridge Textiles",
    accountNumber: "BLR-TXL-60022",
    domain: "blueridgetextiles.com",
    primaryContactName: "Hana Yoshida",
    primaryContactEmail: "hana.yoshida@blueridgetextiles.com",
    paymentTermsDays: 45,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 49,
      monthsOnTimeHistory: 12,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 195000,
    },
  },
  {
    id: "cust-grandview-hardware",
    name: "Grandview Hardware Supply",
    accountNumber: "GRV-HW-15098",
    domain: "grandviewhw.com",
    primaryContactName: "Ricky Owens",
    primaryContactEmail: "ricky.owens@grandviewhw.com",
    paymentTermsDays: 30,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 31,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 145000,
    },
  },
  {
    id: "cust-trailhead-outdoor",
    name: "Trailhead Outdoor Gear",
    accountNumber: "TRH-OUT-22855",
    domain: "trailheadoutdoor.com",
    primaryContactName: "Bryce Calderón",
    primaryContactEmail: "bryce.calderon@trailheadoutdoor.com",
    paymentTermsDays: 30,
    industry: "retail",
    behavior: {
      averageDaysToPay: 35,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 220000,
    },
  },
  {
    id: "cust-silverline-aviation",
    name: "Silverline Aviation Services",
    accountNumber: "SLV-AVT-77433",
    domain: "silverlineaviation.com",
    primaryContactName: "Margot Pelletier",
    primaryContactEmail: "margot.pelletier@silverlineaviation.com",
    paymentTermsDays: 45,
    industry: "aviation",
    behavior: {
      averageDaysToPay: 41,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 280000,
    },
  },
  {
    id: "cust-cobaltridge-mining",
    name: "Cobalt Ridge Mining",
    accountNumber: "CBR-MIN-94011",
    domain: "cobaltridge.com",
    primaryContactName: "Wesley Otieno",
    primaryContactEmail: "wesley.otieno@cobaltridge.com",
    paymentTermsDays: 60,
    industry: "mining",
    behavior: {
      averageDaysToPay: 61,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 350000,
    },
  },
  {
    id: "cust-fieldcrest-agri",
    name: "Fieldcrest Agricultural Supply",
    accountNumber: "FLD-AGR-55209",
    domain: "fieldcrestag.com",
    primaryContactName: "Dolores Ramirez",
    primaryContactEmail: "dolores.ramirez@fieldcrestag.com",
    paymentTermsDays: 45,
    industry: "agriculture",
    behavior: {
      averageDaysToPay: 52,
      monthsOnTimeHistory: 10,
      silentDays: 7,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 195000,
    },
  },
  {
    id: "cust-vanguard-security",
    name: "Vanguard Security Systems",
    accountNumber: "VG-SEC-66007",
    domain: "vanguardsec.com",
    primaryContactName: "Adrienne Czarnecki",
    primaryContactEmail: "adrienne.czarnecki@vanguardsec.com",
    paymentTermsDays: 30,
    industry: "technology",
    behavior: {
      averageDaysToPay: 31,
      monthsOnTimeHistory: 20,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 145000,
    },
  },
  {
    id: "cust-meridian-fitness",
    name: "Meridian Fitness Equipment",
    accountNumber: "MER-FIT-33011",
    domain: "meridianfit.com",
    primaryContactName: "Roman Avalos",
    primaryContactEmail: "roman.avalos@meridianfit.com",
    paymentTermsDays: 30,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 30,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 130000,
    },
  },
  {
    id: "cust-stratoview-aerospace",
    name: "Stratoview Aerospace",
    accountNumber: "STR-AERO-87199",
    domain: "stratoview.com",
    primaryContactName: "Imani Okafor",
    primaryContactEmail: "imani.okafor@stratoview.com",
    paymentTermsDays: 60,
    industry: "aerospace",
    behavior: {
      averageDaysToPay: 63,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 460000,
    },
  },
  {
    id: "cust-lighthouse-publishing",
    name: "Lighthouse Publishing",
    accountNumber: "LHT-PUB-21088",
    domain: "lighthousepub.com",
    primaryContactName: "Quincy Marlowe",
    primaryContactEmail: "quincy.marlowe@lighthousepub.com",
    paymentTermsDays: 30,
    industry: "media",
    behavior: {
      averageDaysToPay: 38,
      monthsOnTimeHistory: 12,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 110000,
    },
  },
  {
    id: "cust-hawthorne-dental",
    name: "Hawthorne Dental Supply",
    accountNumber: "HWT-DNT-19033",
    domain: "hawthornedental.com",
    primaryContactName: "Beatriz Quintero",
    primaryContactEmail: "beatriz.quintero@hawthornedental.com",
    paymentTermsDays: 30,
    industry: "healthcare",
    behavior: {
      averageDaysToPay: 30,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 175000,
    },
  },
  {
    id: "cust-skyharbor-logistics",
    name: "Sky Harbor Logistics",
    accountNumber: "SKY-LOG-88412",
    domain: "skyharborlog.com",
    primaryContactName: "Garrison Wexley",
    primaryContactEmail: "garrison.wexley@skyharborlog.com",
    paymentTermsDays: 30,
    industry: "logistics",
    behavior: {
      averageDaysToPay: 29,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 195000,
    },
  },
  {
    id: "cust-burnsidehill-coffee",
    name: "Burnside Hill Coffee Roasters",
    accountNumber: "BNS-COF-12099",
    domain: "burnsidehill.coffee",
    primaryContactName: "Mateo Velasquez",
    primaryContactEmail: "mateo.velasquez@burnsidehill.coffee",
    paymentTermsDays: 30,
    industry: "food-distribution",
    behavior: {
      averageDaysToPay: 33,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 95000,
    },
  },
  {
    id: "cust-rivercrest-banking",
    name: "Rivercrest Banking Services",
    accountNumber: "RVC-BNK-44022",
    domain: "rivercrestbank.com",
    primaryContactName: "Holland Whitford",
    primaryContactEmail: "holland.whitford@rivercrestbank.com",
    paymentTermsDays: 45,
    industry: "financial-services",
    behavior: {
      averageDaysToPay: 42,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 220000,
    },
  },
  {
    id: "cust-foggyharbor-shipping",
    name: "Foggy Harbor Shipping",
    accountNumber: "FOG-SHP-23409",
    domain: "foggyharbor.com",
    primaryContactName: "Saoirse O'Bannon",
    primaryContactEmail: "saoirse.obannon@foggyharbor.com",
    paymentTermsDays: 45,
    industry: "logistics",
    behavior: {
      averageDaysToPay: 50,
      monthsOnTimeHistory: 10,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 250000,
    },
  },
  {
    id: "cust-gulfshore-energy",
    name: "Gulfshore Energy Partners",
    accountNumber: "GLF-ENR-67011",
    domain: "gulfshore-energy.com",
    primaryContactName: "Imani Lockhart",
    primaryContactEmail: "imani.lockhart@gulfshore-energy.com",
    paymentTermsDays: 60,
    industry: "energy",
    behavior: {
      averageDaysToPay: 57,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 380000,
    },
  },
  {
    id: "cust-woodlandcrest-toys",
    name: "Woodland Crest Toys",
    accountNumber: "WDL-TOY-90112",
    domain: "woodlandcresttoys.com",
    primaryContactName: "Fern Aldridge",
    primaryContactEmail: "fern.aldridge@woodlandcresttoys.com",
    paymentTermsDays: 60,
    industry: "retail",
    behavior: {
      averageDaysToPay: 66,
      monthsOnTimeHistory: 8,
      breachedPromiseCount: 1,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 195000,
    },
  },
  {
    id: "cust-emberlight-candles",
    name: "Emberlight Candle Co",
    accountNumber: "EMB-CND-55009",
    domain: "emberlightcandles.com",
    primaryContactName: "Soledad Marchetti",
    primaryContactEmail: "soledad.marchetti@emberlightcandles.com",
    paymentTermsDays: 30,
    industry: "retail",
    behavior: {
      averageDaysToPay: 36,
      monthsOnTimeHistory: 12,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 78000,
    },
  },
  {
    id: "cust-northland-glass",
    name: "Northland Glass & Mirror",
    accountNumber: "NLG-GLS-31202",
    domain: "northlandglass.com",
    primaryContactName: "Rosalind Brody",
    primaryContactEmail: "rosalind.brody@northlandglass.com",
    paymentTermsDays: 30,
    industry: "building-materials",
    behavior: {
      averageDaysToPay: 33,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 115000,
    },
  },
  {
    id: "cust-crestview-medical",
    name: "Crestview Medical Devices",
    accountNumber: "CRV-MED-77011",
    domain: "crestviewmed.com",
    primaryContactName: "Inigo Marquez",
    primaryContactEmail: "inigo.marquez@crestviewmed.com",
    paymentTermsDays: 45,
    industry: "healthcare",
    behavior: {
      averageDaysToPay: 46,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 285000,
    },
  },
  {
    id: "cust-stoneharbor-cables",
    name: "Stone Harbor Cable Works",
    accountNumber: "STH-CBL-19087",
    domain: "stoneharborcables.com",
    primaryContactName: "Mireille Vasquez",
    primaryContactEmail: "mireille.vasquez@stoneharborcables.com",
    paymentTermsDays: 30,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 34,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 165000,
    },
  },
  {
    id: "cust-westbrook-paints",
    name: "Westbrook Industrial Paints",
    accountNumber: "WST-PNT-26095",
    domain: "westbrookpaints.com",
    primaryContactName: "Tobias Niemeyer",
    primaryContactEmail: "tobias.niemeyer@westbrookpaints.com",
    paymentTermsDays: 30,
    industry: "chemicals",
    behavior: {
      averageDaysToPay: 35,
      monthsOnTimeHistory: 12,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 135000,
    },
  },
  {
    id: "cust-stellarwave-comms",
    name: "Stellarwave Communications",
    accountNumber: "STL-CMM-44233",
    domain: "stellarwavecomms.com",
    primaryContactName: "Yamileth Cordero",
    primaryContactEmail: "yamileth.cordero@stellarwavecomms.com",
    paymentTermsDays: 30,
    industry: "technology",
    behavior: {
      averageDaysToPay: 32,
      monthsOnTimeHistory: 16,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 180000,
    },
  },
  {
    id: "cust-hartfield-cabinets",
    name: "Hartfield Cabinet Makers",
    accountNumber: "HRT-CAB-71109",
    domain: "hartfieldcabinets.com",
    primaryContactName: "Devereaux Mills",
    primaryContactEmail: "devereaux.mills@hartfieldcabinets.com",
    paymentTermsDays: 45,
    industry: "manufacturing",
    behavior: {
      averageDaysToPay: 47,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 110000,
    },
  },
  {
    id: "cust-bayline-seafood",
    name: "Bayline Seafood Distributors",
    accountNumber: "BAY-SEA-22099",
    domain: "baylineseafood.com",
    primaryContactName: "Magdalena Reichert",
    primaryContactEmail: "magdalena.reichert@baylineseafood.com",
    paymentTermsDays: 30,
    industry: "food-distribution",
    behavior: {
      averageDaysToPay: 31,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 145000,
    },
  },
  {
    id: "cust-pinecrest-roofing",
    name: "Pinecrest Roofing Supply",
    accountNumber: "PCR-RF-58009",
    domain: "pinecrestroofing.com",
    primaryContactName: "Booker Hodges",
    primaryContactEmail: "booker.hodges@pinecrestroofing.com",
    paymentTermsDays: 30,
    industry: "building-materials",
    behavior: {
      averageDaysToPay: 34,
      monthsOnTimeHistory: 14,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 125000,
    },
  },
  {
    id: "cust-evergreen-software",
    name: "Evergreen Software Studios",
    accountNumber: "EVS-SW-67411",
    domain: "evergreensoftware.io",
    primaryContactName: "Solenne Mauriac",
    primaryContactEmail: "solenne.mauriac@evergreensoftware.io",
    paymentTermsDays: 30,
    industry: "technology",
    behavior: {
      averageDaysToPay: 28,
      monthsOnTimeHistory: 18,
      relationshipTier: "standard",
      last6MonthsOrderVolume: 135000,
    },
  },

  // ════════════════════════════════════════════════════════════════════
  // Long-tail / chronically slow accounts (~20)
  // ════════════════════════════════════════════════════════════════════
  {
    id: "cust-redmesa-equipment",
    name: "Red Mesa Equipment Rentals",
    accountNumber: "RDM-EQP-12077",
    domain: "redmesaeq.com",
    primaryContactName: "Tom Buchanan",
    primaryContactEmail: "tom.buchanan@redmesaeq.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 52,
      monthsOnTimeHistory: 4,
      silentDays: 11,
      breachedPromiseCount: 1,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 78000,
    },
  },
  {
    id: "cust-sundown-printing",
    name: "Sundown Printing Co",
    accountNumber: "SUN-PRT-32088",
    domain: "sundownprinting.com",
    primaryContactName: "Quintus Beaufort",
    primaryContactEmail: "quintus.beaufort@sundownprinting.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 64,
      monthsOnTimeHistory: 2,
      silentDays: 21,
      breachedPromiseCount: 2,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 42000,
    },
  },
  {
    id: "cust-applewood-decor",
    name: "Applewood Décor",
    accountNumber: "APW-DEC-55903",
    domain: "applewooddecor.com",
    primaryContactName: "Imelda Vázquez",
    primaryContactEmail: "imelda.vazquez@applewooddecor.com",
    paymentTermsDays: 30,
    industry: "retail",
    behavior: {
      averageDaysToPay: 49,
      monthsOnTimeHistory: 6,
      silentDays: 9,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 36000,
    },
  },
  {
    id: "cust-kestrel-press",
    name: "Kestrel Press Inc",
    accountNumber: "KST-PRS-18077",
    domain: "kestrelpress.com",
    primaryContactName: "Wendell Birch",
    primaryContactEmail: "wendell.birch@kestrelpress.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 57,
      monthsOnTimeHistory: 0,
      silentDays: 33,
      breachedPromiseCount: 2,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 28000,
    },
  },
  {
    id: "cust-tidemark-supply",
    name: "Tidemark Supply Inc",
    accountNumber: "TDM-SUP-44209",
    domain: "tidemarksupply.com",
    primaryContactName: "Aurelia Carmichael",
    primaryContactEmail: "aurelia.carmichael@tidemarksupply.com",
    paymentTermsDays: 30,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 53,
      monthsOnTimeHistory: 4,
      silentDays: 15,
      breachedPromiseCount: 1,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 64000,
    },
  },
  {
    id: "cust-juniperhill-feed",
    name: "Juniper Hill Feed Supply",
    accountNumber: "JNH-FED-66117",
    domain: "juniperhillfeed.com",
    primaryContactName: "Cassius Lindgren",
    primaryContactEmail: "cassius.lindgren@juniperhillfeed.com",
    paymentTermsDays: 45,
    industry: "agriculture",
    behavior: {
      averageDaysToPay: 71,
      monthsOnTimeHistory: 2,
      silentDays: 19,
      breachedPromiseCount: 1,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 51000,
    },
  },
  {
    id: "cust-driftway-marine",
    name: "Driftway Marine Supply",
    accountNumber: "DRF-MAR-88022",
    domain: "driftwaymarine.com",
    primaryContactName: "Phinneas Calloway",
    primaryContactEmail: "phinneas.calloway@driftwaymarine.com",
    paymentTermsDays: 30,
    industry: "marine",
    behavior: {
      averageDaysToPay: 58,
      monthsOnTimeHistory: 0,
      silentDays: 41,
      breachedPromiseCount: 2,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 37000,
    },
  },
  {
    id: "cust-pebblebrook-cafe",
    name: "Pebblebrook Café Group",
    accountNumber: "PBB-CAF-29010",
    domain: "pebblebrookcafe.com",
    primaryContactName: "Cordelia Hawkesworth",
    primaryContactEmail: "cordelia.hawkesworth@pebblebrookcafe.com",
    paymentTermsDays: 30,
    industry: "food-service",
    behavior: {
      averageDaysToPay: 48,
      monthsOnTimeHistory: 6,
      silentDays: 13,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 22000,
    },
  },
  {
    id: "cust-amberlock-locksmiths",
    name: "Amberlock Locksmiths",
    accountNumber: "AML-LCK-31019",
    domain: "amberlockls.com",
    primaryContactName: "Theodore Faulkner",
    primaryContactEmail: "theodore.faulkner@amberlockls.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 51,
      monthsOnTimeHistory: 6,
      silentDays: 18,
      breachedPromiseCount: 1,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 19000,
    },
  },
  {
    id: "cust-quicksilver-graphics",
    name: "Quicksilver Graphics",
    accountNumber: "QSV-GRX-50988",
    domain: "quicksilvergraphics.com",
    primaryContactName: "Pelagia Ferrari",
    primaryContactEmail: "pelagia.ferrari@quicksilvergraphics.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 62,
      monthsOnTimeHistory: 2,
      silentDays: 24,
      breachedPromiseCount: 2,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 31000,
    },
  },
  {
    id: "cust-windmere-events",
    name: "Windmere Events Co",
    accountNumber: "WND-EVT-77118",
    domain: "windmereevents.com",
    primaryContactName: "Marlowe Crispin",
    primaryContactEmail: "marlowe.crispin@windmereevents.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 55,
      monthsOnTimeHistory: 4,
      silentDays: 14,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 47000,
    },
  },
  {
    id: "cust-saltmarsh-bakery",
    name: "Saltmarsh Bakery",
    accountNumber: "SLM-BKR-22118",
    domain: "saltmarshbakery.com",
    primaryContactName: "Dorian Larchmont",
    primaryContactEmail: "dorian.larchmont@saltmarshbakery.com",
    paymentTermsDays: 30,
    industry: "food-distribution",
    behavior: {
      averageDaysToPay: 47,
      monthsOnTimeHistory: 8,
      silentDays: 11,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 18000,
    },
  },
  {
    id: "cust-broadview-floors",
    name: "Broadview Flooring",
    accountNumber: "BVW-FLR-66201",
    domain: "broadviewfloors.com",
    primaryContactName: "Esperanza Belmonte",
    primaryContactEmail: "esperanza.belmonte@broadviewfloors.com",
    paymentTermsDays: 30,
    industry: "building-materials",
    behavior: {
      averageDaysToPay: 50,
      monthsOnTimeHistory: 4,
      breachedPromiseCount: 1,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 62000,
    },
  },
  {
    id: "cust-fernridge-camping",
    name: "Fern Ridge Camping Supply",
    accountNumber: "FRN-CMP-89011",
    domain: "fernridgecamping.com",
    primaryContactName: "Caspian Holloway",
    primaryContactEmail: "caspian.holloway@fernridgecamping.com",
    paymentTermsDays: 30,
    industry: "retail",
    behavior: {
      averageDaysToPay: 54,
      monthsOnTimeHistory: 2,
      silentDays: 22,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 24000,
    },
  },
  {
    id: "cust-mossglen-orchards",
    name: "Mossglen Orchards",
    accountNumber: "MSG-ORD-13088",
    domain: "mossglenorchards.com",
    primaryContactName: "Pernille Aagaard",
    primaryContactEmail: "pernille.aagaard@mossglenorchards.com",
    paymentTermsDays: 30,
    industry: "agriculture",
    behavior: {
      averageDaysToPay: 56,
      monthsOnTimeHistory: 4,
      silentDays: 16,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 41000,
    },
  },
  {
    id: "cust-cornerstone-marbles",
    name: "Cornerstone Marble & Tile",
    accountNumber: "CRN-MTL-44033",
    domain: "cornerstonemarble.com",
    primaryContactName: "Lazarus Greenholt",
    primaryContactEmail: "lazarus.greenholt@cornerstonemarble.com",
    paymentTermsDays: 30,
    industry: "building-materials",
    behavior: {
      averageDaysToPay: 49,
      monthsOnTimeHistory: 6,
      silentDays: 13,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 56000,
    },
  },
  {
    id: "cust-blackwood-printers",
    name: "Blackwood Printers",
    accountNumber: "BLK-PRT-90022",
    domain: "blackwoodprinters.com",
    primaryContactName: "Endellion Whitcombe",
    primaryContactEmail: "endellion.whitcombe@blackwoodprinters.com",
    paymentTermsDays: 30,
    industry: "services",
    behavior: {
      averageDaysToPay: 60,
      monthsOnTimeHistory: 0,
      silentDays: 35,
      breachedPromiseCount: 2,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 22000,
    },
  },
  {
    id: "cust-redleaf-electronics",
    name: "Redleaf Electronics Supply",
    accountNumber: "RDL-ELC-33701",
    domain: "redleafelectronics.com",
    primaryContactName: "Innes Mountcastle",
    primaryContactEmail: "innes.mountcastle@redleafelectronics.com",
    paymentTermsDays: 30,
    industry: "distribution",
    behavior: {
      averageDaysToPay: 47,
      monthsOnTimeHistory: 8,
      silentDays: 10,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 34000,
    },
  },
  {
    id: "cust-haven-bedding",
    name: "Haven Bedding Co",
    accountNumber: "HVN-BED-19099",
    domain: "havenbedding.com",
    primaryContactName: "Talullah Greaves",
    primaryContactEmail: "talullah.greaves@havenbedding.com",
    paymentTermsDays: 30,
    industry: "retail",
    behavior: {
      averageDaysToPay: 53,
      monthsOnTimeHistory: 4,
      breachedPromiseCount: 1,
      relationshipTier: "long-tail",
      last6MonthsOrderVolume: 27000,
    },
  },
]

const CUSTOMER_INDEX: Record<CustomerId, Customer> = SEED_CUSTOMERS.reduce(
  (acc, c) => {
    acc[c.id] = c
    return acc
  },
  {} as Record<CustomerId, Customer>,
)

export function getCustomer(id: CustomerId): Customer | undefined {
  return CUSTOMER_INDEX[id]
}
