// 80 purchase orders distributed across the 40 seed vendors. Hand-written so the
// match-puzzle UI has realistic line items, units of measure, and approvers.
//
// Source of truth: docs/handoff/invoice-processing/04-data-model.md
//   § "Static seed shape" > "seed-purchase-orders.ts".
//
// Hero POs (do NOT edit copy without also updating 05-demo-script.md):
//   - po-1389  Acme Cleaning Services       monthly cleaning $4,200/mo (3-way hero)
//   - po-1422  Acme Cleaning Services       Q2 deep-clean $42,800 (duplicate hero source)
//   - po-1462  Singapore Stationery         office supplies SGD 8,000 (tax hero)
//   - po-1208  Northeast Industrial         $48,000, 6 lines (price-variance exception)
//   - po-1314  Pacific Logistics            $8,940 (missing-GRN exception)
//   - po-1455  Atlantic Industrial          $46,000, 2/10 net 30 (early-pay)

import type { PurchaseOrder, PurchaseOrderId } from "./types"

export const SEED_POS: PurchaseOrder[] = [
  // ── Hero POs ───────────────────────────────────────────────────────────
  {
    id: "po-1389",
    poNumber: "PO-1389",
    vendorId: "vendor-aclng-001",
    status: "open",
    issuedAt: "2026-04-25T14:00:00Z",
    expectedDeliveryAt: "2026-05-31T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 4200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Monthly cleaning service — Plant A — May 2026",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "mo",
        lineTotal: 4200,
      },
    ],
    glDefault: {
      account: "62100",
      costCenter: "PLANT-A",
      entity: "AcmeCo US",
    },
  },
  {
    id: "po-1422",
    poNumber: "PO-1422",
    vendorId: "vendor-aclng-001",
    status: "open",
    issuedAt: "2026-03-28T15:30:00Z",
    expectedDeliveryAt: "2026-04-30T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 42800,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Quarterly deep-clean service — Plant A (Q2 2026)",
        quantity: 1,
        unitPrice: 18400,
        unitOfMeasure: "ea",
        lineTotal: 18400,
      },
      {
        lineNumber: 2,
        description: "Quarterly deep-clean service — Plant B (Q2 2026)",
        quantity: 1,
        unitPrice: 14200,
        unitOfMeasure: "ea",
        lineTotal: 14200,
      },
      {
        lineNumber: 3,
        description: "Equipment rental — industrial vacuum (1 wk)",
        quantity: 1,
        unitPrice: 10200,
        unitOfMeasure: "wk",
        lineTotal: 10200,
      },
    ],
    glDefault: {
      account: "62100",
      costCenter: "PLANT-A",
      entity: "AcmeCo US",
    },
  },
  {
    id: "po-1462",
    poNumber: "PO-1462",
    vendorId: "vendor-sgs-001",
    status: "open",
    issuedAt: "2026-05-02T03:18:00Z",
    expectedDeliveryAt: "2026-05-14T08:00:00Z",
    approver: "Daniel Park",
    totalAmount: 8000,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "A4 paper — 80gsm white, 50 ream",
        quantity: 50,
        unitPrice: 36,
        unitOfMeasure: "ream",
        lineTotal: 1800,
      },
      {
        lineNumber: 2,
        description: "Toner cartridges — assorted (HP/Canon mix)",
        quantity: 12,
        unitPrice: 350,
        unitOfMeasure: "ea",
        lineTotal: 4200,
      },
      {
        lineNumber: 3,
        description: "Office supplies — miscellaneous (pens, notepads, files)",
        quantity: 1,
        unitPrice: 2000,
        unitOfMeasure: "lot",
        lineTotal: 2000,
      },
    ],
  },
  {
    id: "po-1208",
    poNumber: "PO-1208",
    vendorId: "vendor-northeast-001",
    status: "open",
    issuedAt: "2026-04-12T10:45:00Z",
    expectedDeliveryAt: "2026-05-10T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 48000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Steel pipe fittings — 2in stainless",
        quantity: 200,
        unitPrice: 28,
        unitOfMeasure: "ea",
        lineTotal: 5600,
      },
      {
        lineNumber: 2,
        description: "Steel pipe fittings — 3in stainless",
        quantity: 150,
        unitPrice: 42,
        unitOfMeasure: "ea",
        lineTotal: 6300,
      },
      {
        lineNumber: 3,
        description: "Industrial gaskets — Viton 4in",
        quantity: 320,
        unitPrice: 18,
        unitOfMeasure: "ea",
        lineTotal: 5760,
      },
      {
        lineNumber: 4,
        description: "Pressure relief valves — model PRV-2200",
        quantity: 375,
        unitPrice: 48,
        unitOfMeasure: "ea",
        lineTotal: 18000,
      },
      {
        lineNumber: 5,
        description: "Pipe insulation — fiberglass 4in (per ft)",
        quantity: 1200,
        unitPrice: 4.45,
        unitOfMeasure: "ft",
        lineTotal: 5340,
      },
      {
        lineNumber: 6,
        description: "Mounting brackets — heavy duty",
        quantity: 350,
        unitPrice: 20,
        unitOfMeasure: "ea",
        lineTotal: 7000,
      },
    ],
  },
  {
    id: "po-1314",
    poNumber: "PO-1314",
    vendorId: "vendor-pacific-logistics-001",
    status: "open",
    issuedAt: "2026-04-30T09:12:00Z",
    expectedDeliveryAt: "2026-05-12T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 8940,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Inbound freight — container PALC-22487 (Oakland to Plant A)",
        quantity: 1,
        unitPrice: 5200,
        unitOfMeasure: "ea",
        lineTotal: 5200,
      },
      {
        lineNumber: 2,
        description: "Drayage and chassis fees",
        quantity: 1,
        unitPrice: 1840,
        unitOfMeasure: "ea",
        lineTotal: 1840,
      },
      {
        lineNumber: 3,
        description: "Fuel surcharge",
        quantity: 1,
        unitPrice: 1900,
        unitOfMeasure: "ea",
        lineTotal: 1900,
      },
    ],
  },
  {
    id: "po-1455",
    poNumber: "PO-1455",
    vendorId: "vendor-atlantic-001",
    status: "open",
    issuedAt: "2026-04-22T11:30:00Z",
    expectedDeliveryAt: "2026-05-09T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 46000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Industrial bearings — SKF 6209-2RS1",
        quantity: 400,
        unitPrice: 65,
        unitOfMeasure: "ea",
        lineTotal: 26000,
      },
      {
        lineNumber: 2,
        description: "Drive belts — heavy-duty V-belt assortment",
        quantity: 100,
        unitPrice: 200,
        unitOfMeasure: "ea",
        lineTotal: 20000,
      },
    ],
  },

  // ── Other Acme Cleaning POs (recurring monthly + spot orders) ─────────
  {
    id: "po-1311",
    poNumber: "PO-1311",
    vendorId: "vendor-aclng-001",
    status: "closed",
    issuedAt: "2026-03-25T14:00:00Z",
    expectedDeliveryAt: "2026-04-30T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 4200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Monthly cleaning service — Plant A — April 2026",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "mo",
        lineTotal: 4200,
      },
    ],
    glDefault: { account: "62100", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },
  {
    id: "po-1248",
    poNumber: "PO-1248",
    vendorId: "vendor-aclng-001",
    status: "closed",
    issuedAt: "2026-02-25T14:00:00Z",
    expectedDeliveryAt: "2026-03-31T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 4200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Monthly cleaning service — Plant A — March 2026",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "mo",
        lineTotal: 4200,
      },
    ],
    glDefault: { account: "62100", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },

  // ── Singapore Stationery POs ──────────────────────────────────────────
  {
    id: "po-1398",
    poNumber: "PO-1398",
    vendorId: "vendor-sgs-001",
    status: "closed",
    issuedAt: "2026-04-04T03:22:00Z",
    expectedDeliveryAt: "2026-04-12T08:00:00Z",
    approver: "Priya Raman",
    totalAmount: 5400,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Office supplies — Q2 starter kits (5)",
        quantity: 5,
        unitPrice: 720,
        unitOfMeasure: "kit",
        lineTotal: 3600,
      },
      {
        lineNumber: 2,
        description: "Filing supplies — binders, folders, labels",
        quantity: 1,
        unitPrice: 1800,
        unitOfMeasure: "lot",
        lineTotal: 1800,
      },
    ],
  },

  // ── Northeast Industrial — additional POs ─────────────────────────────
  {
    id: "po-1351",
    poNumber: "PO-1351",
    vendorId: "vendor-northeast-001",
    status: "closed",
    issuedAt: "2026-03-15T10:00:00Z",
    expectedDeliveryAt: "2026-04-15T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 32400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Stainless steel sheet — 16ga (4ft x 8ft)",
        quantity: 60,
        unitPrice: 340,
        unitOfMeasure: "ea",
        lineTotal: 20400,
      },
      {
        lineNumber: 2,
        description: "Welding rod — E7018 (10lb box)",
        quantity: 80,
        unitPrice: 150,
        unitOfMeasure: "box",
        lineTotal: 12000,
      },
    ],
  },

  // ── Pacific Logistics — additional POs ────────────────────────────────
  {
    id: "po-1278",
    poNumber: "PO-1278",
    vendorId: "vendor-pacific-logistics-001",
    status: "closed",
    issuedAt: "2026-03-20T09:00:00Z",
    expectedDeliveryAt: "2026-04-02T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 6420,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Outbound LTL freight — 8 shipments to East Coast",
        quantity: 8,
        unitPrice: 480,
        unitOfMeasure: "ea",
        lineTotal: 3840,
      },
      {
        lineNumber: 2,
        description: "Fuel surcharge",
        quantity: 1,
        unitPrice: 2580,
        unitOfMeasure: "ea",
        lineTotal: 2580,
      },
    ],
  },
  {
    id: "po-1442",
    poNumber: "PO-1442",
    vendorId: "vendor-pacific-logistics-001",
    status: "open",
    issuedAt: "2026-05-01T09:30:00Z",
    expectedDeliveryAt: "2026-05-20T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 11250,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Inbound freight — container PALC-22931",
        quantity: 1,
        unitPrice: 6400,
        unitOfMeasure: "ea",
        lineTotal: 6400,
      },
      {
        lineNumber: 2,
        description: "Drayage and chassis fees",
        quantity: 1,
        unitPrice: 2150,
        unitOfMeasure: "ea",
        lineTotal: 2150,
      },
      {
        lineNumber: 3,
        description: "Fuel surcharge",
        quantity: 1,
        unitPrice: 2700,
        unitOfMeasure: "ea",
        lineTotal: 2700,
      },
    ],
  },

  // ── Westpoint Marketing POs ───────────────────────────────────────────
  {
    id: "po-1431",
    poNumber: "PO-1431",
    vendorId: "vendor-westpoint-mkt-001",
    status: "open",
    issuedAt: "2026-04-18T15:00:00Z",
    expectedDeliveryAt: "2026-05-18T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 4200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Marketing campaign deliverables — May 2026",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "mo",
        lineTotal: 4200,
      },
    ],
  },

  // ── Atlantic Industrial additional POs ────────────────────────────────
  {
    id: "po-1342",
    poNumber: "PO-1342",
    vendorId: "vendor-atlantic-001",
    status: "closed",
    issuedAt: "2026-03-10T11:00:00Z",
    expectedDeliveryAt: "2026-03-28T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 28400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Hydraulic cylinders — 4in bore",
        quantity: 20,
        unitPrice: 920,
        unitOfMeasure: "ea",
        lineTotal: 18400,
      },
      {
        lineNumber: 2,
        description: "Pump seal kits",
        quantity: 50,
        unitPrice: 200,
        unitOfMeasure: "ea",
        lineTotal: 10000,
      },
    ],
  },

  // ── Pacific Distribution POs ──────────────────────────────────────────
  {
    id: "po-1376",
    poNumber: "PO-1376",
    vendorId: "vendor-pacific-dist-001",
    status: "open",
    issuedAt: "2026-04-20T09:45:00Z",
    expectedDeliveryAt: "2026-05-12T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 38400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Pallet jacks — 5500lb capacity",
        quantity: 12,
        unitPrice: 1850,
        unitOfMeasure: "ea",
        lineTotal: 22200,
      },
      {
        lineNumber: 2,
        description: "Warehouse racking — 8ft uprights",
        quantity: 40,
        unitPrice: 405,
        unitOfMeasure: "ea",
        lineTotal: 16200,
      },
    ],
  },
  {
    id: "po-1289",
    poNumber: "PO-1289",
    vendorId: "vendor-pacific-dist-001",
    status: "closed",
    issuedAt: "2026-03-12T08:30:00Z",
    expectedDeliveryAt: "2026-03-30T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 22800,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Shipping cartons — assorted sizes (case of 500)",
        quantity: 24,
        unitPrice: 480,
        unitOfMeasure: "case",
        lineTotal: 11520,
      },
      {
        lineNumber: 2,
        description: "Stretch film — 80ga (case of 4 rolls)",
        quantity: 60,
        unitPrice: 188,
        unitOfMeasure: "case",
        lineTotal: 11280,
      },
    ],
  },

  // ── Blue Peak Materials ───────────────────────────────────────────────
  {
    id: "po-1267",
    poNumber: "PO-1267",
    vendorId: "vendor-bluepeak-001",
    status: "closed",
    issuedAt: "2026-03-08T13:15:00Z",
    expectedDeliveryAt: "2026-03-28T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 18650,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Aluminum bar stock — 1in round (12ft length)",
        quantity: 100,
        unitPrice: 86,
        unitOfMeasure: "ea",
        lineTotal: 8600,
      },
      {
        lineNumber: 2,
        description: "Copper sheet — 24ga (4ft x 8ft)",
        quantity: 30,
        unitPrice: 335,
        unitOfMeasure: "ea",
        lineTotal: 10050,
      },
    ],
  },
  {
    id: "po-1408",
    poNumber: "PO-1408",
    vendorId: "vendor-bluepeak-001",
    status: "open",
    issuedAt: "2026-04-15T13:00:00Z",
    expectedDeliveryAt: "2026-05-08T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 24350,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Brass fittings — assorted plumbing",
        quantity: 500,
        unitPrice: 22,
        unitOfMeasure: "ea",
        lineTotal: 11000,
      },
      {
        lineNumber: 2,
        description: "Steel angle iron — 2in x 2in x 1/4in",
        quantity: 75,
        unitPrice: 178,
        unitOfMeasure: "ea",
        lineTotal: 13350,
      },
    ],
  },
  {
    id: "po-1437",
    poNumber: "PO-1437",
    vendorId: "vendor-bluepeak-001",
    status: "open",
    issuedAt: "2026-04-26T11:00:00Z",
    expectedDeliveryAt: "2026-05-18T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 14820,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Galvanized steel coil — 22ga",
        quantity: 30,
        unitPrice: 494,
        unitOfMeasure: "ea",
        lineTotal: 14820,
      },
    ],
  },

  // ── Meridian Power Systems ────────────────────────────────────────────
  {
    id: "po-1295",
    poNumber: "PO-1295",
    vendorId: "vendor-meridian-001",
    status: "closed",
    issuedAt: "2026-03-22T16:00:00Z",
    expectedDeliveryAt: "2026-04-18T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 68400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Industrial generator — 250kVA standby",
        quantity: 1,
        unitPrice: 52000,
        unitOfMeasure: "ea",
        lineTotal: 52000,
      },
      {
        lineNumber: 2,
        description: "Installation & commissioning",
        quantity: 1,
        unitPrice: 16400,
        unitOfMeasure: "ea",
        lineTotal: 16400,
      },
    ],
  },
  {
    id: "po-1448",
    poNumber: "PO-1448",
    vendorId: "vendor-meridian-001",
    status: "open",
    issuedAt: "2026-04-29T10:30:00Z",
    expectedDeliveryAt: "2026-06-15T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 38200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Switchgear assembly — 480V/600A",
        quantity: 1,
        unitPrice: 32800,
        unitOfMeasure: "ea",
        lineTotal: 32800,
      },
      {
        lineNumber: 2,
        description: "Annual maintenance contract — Plant A generators",
        quantity: 1,
        unitPrice: 5400,
        unitOfMeasure: "yr",
        lineTotal: 5400,
      },
    ],
  },

  // ── Cascade Office Solutions ──────────────────────────────────────────
  {
    id: "po-1322",
    poNumber: "PO-1322",
    vendorId: "vendor-cascade-001",
    status: "closed",
    issuedAt: "2026-03-30T14:20:00Z",
    expectedDeliveryAt: "2026-04-10T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 3640,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Office paper — letter size (10 ream box)",
        quantity: 20,
        unitPrice: 62,
        unitOfMeasure: "box",
        lineTotal: 1240,
      },
      {
        lineNumber: 2,
        description: "Printer toner — HP LaserJet 4-pack",
        quantity: 6,
        unitPrice: 400,
        unitOfMeasure: "ea",
        lineTotal: 2400,
      },
    ],
  },
  {
    id: "po-1419",
    poNumber: "PO-1419",
    vendorId: "vendor-cascade-001",
    status: "open",
    issuedAt: "2026-04-23T09:15:00Z",
    expectedDeliveryAt: "2026-05-08T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 5280,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Ergonomic chairs — office (Herman Miller Aeron)",
        quantity: 4,
        unitPrice: 1170,
        unitOfMeasure: "ea",
        lineTotal: 4680,
      },
      {
        lineNumber: 2,
        description: "Monitor mounts — dual arm",
        quantity: 6,
        unitPrice: 100,
        unitOfMeasure: "ea",
        lineTotal: 600,
      },
    ],
  },

  // ── Summit IT Services ────────────────────────────────────────────────
  {
    id: "po-1370",
    poNumber: "PO-1370",
    vendorId: "vendor-summit-it-001",
    status: "open",
    issuedAt: "2026-04-01T09:00:00Z",
    expectedDeliveryAt: "2026-05-31T23:00:00Z",
    approver: "Priya Raman",
    totalAmount: 9000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Managed IT services — May 2026 monthly retainer",
        quantity: 1,
        unitPrice: 9000,
        unitOfMeasure: "mo",
        lineTotal: 9000,
      },
    ],
    glDefault: { account: "64200", costCenter: "CORP-US", entity: "AcmeCo US" },
  },
  {
    id: "po-1281",
    poNumber: "PO-1281",
    vendorId: "vendor-summit-it-001",
    status: "closed",
    issuedAt: "2026-03-01T09:00:00Z",
    expectedDeliveryAt: "2026-04-30T23:00:00Z",
    approver: "Priya Raman",
    totalAmount: 9000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Managed IT services — April 2026 monthly retainer",
        quantity: 1,
        unitPrice: 9000,
        unitOfMeasure: "mo",
        lineTotal: 9000,
      },
    ],
    glDefault: { account: "64200", costCenter: "CORP-US", entity: "AcmeCo US" },
  },

  // ── Ironbridge Machining ──────────────────────────────────────────────
  {
    id: "po-1356",
    poNumber: "PO-1356",
    vendorId: "vendor-ironbridge-001",
    status: "closed",
    issuedAt: "2026-03-18T15:45:00Z",
    expectedDeliveryAt: "2026-04-22T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 42700,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Custom CNC machined housings — drawing IB-2114",
        quantity: 35,
        unitPrice: 1220,
        unitOfMeasure: "ea",
        lineTotal: 42700,
      },
    ],
  },
  {
    id: "po-1429",
    poNumber: "PO-1429",
    vendorId: "vendor-ironbridge-001",
    status: "open",
    issuedAt: "2026-04-24T11:00:00Z",
    expectedDeliveryAt: "2026-06-04T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 28950,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Precision shafts — 1.5in diameter, 24in length",
        quantity: 50,
        unitPrice: 579,
        unitOfMeasure: "ea",
        lineTotal: 28950,
      },
    ],
  },

  // ── Clearwater Utilities ──────────────────────────────────────────────
  {
    id: "po-1382",
    poNumber: "PO-1382",
    vendorId: "vendor-clearwater-utils-001",
    status: "open",
    issuedAt: "2026-04-08T08:00:00Z",
    expectedDeliveryAt: "2026-05-08T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 11800,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Plant A water service — April 2026",
        quantity: 1,
        unitPrice: 8400,
        unitOfMeasure: "mo",
        lineTotal: 8400,
      },
      {
        lineNumber: 2,
        description: "Plant A sewer service — April 2026",
        quantity: 1,
        unitPrice: 3400,
        unitOfMeasure: "mo",
        lineTotal: 3400,
      },
    ],
    glDefault: { account: "62500", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },
  {
    id: "po-1232",
    poNumber: "PO-1232",
    vendorId: "vendor-clearwater-utils-001",
    status: "closed",
    issuedAt: "2026-03-08T08:00:00Z",
    expectedDeliveryAt: "2026-04-08T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 12350,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Plant A water service — March 2026",
        quantity: 1,
        unitPrice: 8850,
        unitOfMeasure: "mo",
        lineTotal: 8850,
      },
      {
        lineNumber: 2,
        description: "Plant A sewer service — March 2026",
        quantity: 1,
        unitPrice: 3500,
        unitOfMeasure: "mo",
        lineTotal: 3500,
      },
    ],
    glDefault: { account: "62500", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },

  // ── Greenfield Packaging ──────────────────────────────────────────────
  {
    id: "po-1303",
    poNumber: "PO-1303",
    vendorId: "vendor-greenfield-pkg-001",
    status: "closed",
    issuedAt: "2026-03-14T12:00:00Z",
    expectedDeliveryAt: "2026-04-02T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 14820,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Corrugated cartons — 12x12x12 (case of 250)",
        quantity: 30,
        unitPrice: 188,
        unitOfMeasure: "case",
        lineTotal: 5640,
      },
      {
        lineNumber: 2,
        description: "Bubble wrap — 12in x 250ft roll",
        quantity: 40,
        unitPrice: 92,
        unitOfMeasure: "ea",
        lineTotal: 3680,
      },
      {
        lineNumber: 3,
        description: "Custom printed packaging — AcmeCo logo",
        quantity: 1,
        unitPrice: 5500,
        unitOfMeasure: "lot",
        lineTotal: 5500,
      },
    ],
  },
  {
    id: "po-1411",
    poNumber: "PO-1411",
    vendorId: "vendor-greenfield-pkg-001",
    status: "open",
    issuedAt: "2026-04-17T10:30:00Z",
    expectedDeliveryAt: "2026-05-15T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 8950,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Pallet wrap — clear stretch film (60 case)",
        quantity: 60,
        unitPrice: 95,
        unitOfMeasure: "case",
        lineTotal: 5700,
      },
      {
        lineNumber: 2,
        description: "Edge protectors — corrugated",
        quantity: 500,
        unitPrice: 6.5,
        unitOfMeasure: "ea",
        lineTotal: 3250,
      },
    ],
  },

  // ── Tri-State Freight ─────────────────────────────────────────────────
  {
    id: "po-1331",
    poNumber: "PO-1331",
    vendorId: "vendor-tristate-freight-001",
    status: "open",
    issuedAt: "2026-04-05T08:00:00Z",
    expectedDeliveryAt: "2026-05-05T23:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 3850,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "LTL freight — 14 shipments (April 2026)",
        quantity: 14,
        unitPrice: 275,
        unitOfMeasure: "ea",
        lineTotal: 3850,
      },
    ],
  },
  {
    id: "po-1453",
    poNumber: "PO-1453",
    vendorId: "vendor-tristate-freight-001",
    status: "open",
    issuedAt: "2026-05-02T08:00:00Z",
    expectedDeliveryAt: "2026-06-02T23:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 4200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Expedited shipment — Plant A to Atlanta DC",
        quantity: 1,
        unitPrice: 1850,
        unitOfMeasure: "ea",
        lineTotal: 1850,
      },
      {
        lineNumber: 2,
        description: "LTL freight — 8 shipments (early May 2026)",
        quantity: 8,
        unitPrice: 240,
        unitOfMeasure: "ea",
        lineTotal: 1920,
      },
      {
        lineNumber: 3,
        description: "Fuel surcharge",
        quantity: 1,
        unitPrice: 430,
        unitOfMeasure: "ea",
        lineTotal: 430,
      },
    ],
  },

  // ── Cornerstone Legal ─────────────────────────────────────────────────
  {
    id: "po-1413",
    poNumber: "PO-1413",
    vendorId: "vendor-cornerstone-legal-001",
    status: "open",
    issuedAt: "2026-04-21T16:30:00Z",
    expectedDeliveryAt: "2026-05-30T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 18400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Legal counsel — supplier contract review (April 2026)",
        quantity: 32,
        unitPrice: 575,
        unitOfMeasure: "hr",
        lineTotal: 18400,
      },
    ],
  },

  // ── Redwood Janitorial ────────────────────────────────────────────────
  {
    id: "po-1287",
    poNumber: "PO-1287",
    vendorId: "vendor-redwood-jntr-001",
    status: "closed",
    issuedAt: "2026-03-10T11:30:00Z",
    expectedDeliveryAt: "2026-03-22T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 2840,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Restroom supplies — Q2 quarterly",
        quantity: 1,
        unitPrice: 1840,
        unitOfMeasure: "lot",
        lineTotal: 1840,
      },
      {
        lineNumber: 2,
        description: "Cleaning chemicals — industrial grade (assorted)",
        quantity: 1,
        unitPrice: 1000,
        unitOfMeasure: "lot",
        lineTotal: 1000,
      },
    ],
  },
  {
    id: "po-1425",
    poNumber: "PO-1425",
    vendorId: "vendor-redwood-jntr-001",
    status: "open",
    issuedAt: "2026-04-24T13:00:00Z",
    expectedDeliveryAt: "2026-05-12T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 1980,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Hand sanitizer — gallon refills (case of 4)",
        quantity: 12,
        unitPrice: 88,
        unitOfMeasure: "case",
        lineTotal: 1056,
      },
      {
        lineNumber: 2,
        description: "Microfiber towels — bulk (case of 200)",
        quantity: 6,
        unitPrice: 154,
        unitOfMeasure: "case",
        lineTotal: 924,
      },
    ],
  },

  // ── Keystone SaaS ─────────────────────────────────────────────────────
  {
    id: "po-1198",
    poNumber: "PO-1198",
    vendorId: "vendor-keystone-saas-001",
    status: "open",
    issuedAt: "2026-02-15T10:00:00Z",
    expectedDeliveryAt: "2027-02-14T23:00:00Z",
    approver: "Priya Raman",
    totalAmount: 26400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Keystone SaaS — annual subscription (Feb 2026 – Feb 2027)",
        quantity: 1,
        unitPrice: 26400,
        unitOfMeasure: "yr",
        lineTotal: 26400,
      },
    ],
    glDefault: { account: "64500", costCenter: "CORP-US", entity: "AcmeCo US" },
  },

  // ── Coastal Print & Signage ───────────────────────────────────────────
  {
    id: "po-1338",
    poNumber: "PO-1338",
    vendorId: "vendor-coastal-print-001",
    status: "closed",
    issuedAt: "2026-04-02T14:00:00Z",
    expectedDeliveryAt: "2026-04-18T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 1640,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Trade show banners — 3ft x 6ft retractable (4)",
        quantity: 4,
        unitPrice: 285,
        unitOfMeasure: "ea",
        lineTotal: 1140,
      },
      {
        lineNumber: 2,
        description: "Tablecloths — branded (6)",
        quantity: 6,
        unitPrice: 83.33,
        unitOfMeasure: "ea",
        lineTotal: 500,
      },
    ],
  },

  // ── Rosehill Staffing ─────────────────────────────────────────────────
  {
    id: "po-1372",
    poNumber: "PO-1372",
    vendorId: "vendor-rosehill-staffing-001",
    status: "open",
    issuedAt: "2026-04-12T08:00:00Z",
    expectedDeliveryAt: "2026-05-10T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 14820,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Temporary warehouse staff — 312 hrs (April 2026)",
        quantity: 312,
        unitPrice: 47.5,
        unitOfMeasure: "hr",
        lineTotal: 14820,
      },
    ],
  },
  {
    id: "po-1438",
    poNumber: "PO-1438",
    vendorId: "vendor-rosehill-staffing-001",
    status: "open",
    issuedAt: "2026-04-26T08:00:00Z",
    expectedDeliveryAt: "2026-05-24T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 8550,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Temporary line staff — 180 hrs (early May 2026)",
        quantity: 180,
        unitPrice: 47.5,
        unitOfMeasure: "hr",
        lineTotal: 8550,
      },
    ],
  },

  // ── East River Chemical ───────────────────────────────────────────────
  {
    id: "po-1318",
    poNumber: "PO-1318",
    vendorId: "vendor-eastriver-chem-001",
    status: "closed",
    issuedAt: "2026-03-21T13:00:00Z",
    expectedDeliveryAt: "2026-04-15T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 14200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Solvent — IPA 99% (55-gal drum)",
        quantity: 8,
        unitPrice: 1080,
        unitOfMeasure: "drum",
        lineTotal: 8640,
      },
      {
        lineNumber: 2,
        description: "Hazmat surcharge",
        quantity: 1,
        unitPrice: 560,
        unitOfMeasure: "ea",
        lineTotal: 560,
      },
      {
        lineNumber: 3,
        description: "Lab-grade reagents — assorted",
        quantity: 1,
        unitPrice: 5000,
        unitOfMeasure: "lot",
        lineTotal: 5000,
      },
    ],
  },
  {
    id: "po-1450",
    poNumber: "PO-1450",
    vendorId: "vendor-eastriver-chem-001",
    status: "open",
    issuedAt: "2026-05-01T13:00:00Z",
    expectedDeliveryAt: "2026-05-22T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 9850,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Cleaning solvents — degreaser (55-gal drum)",
        quantity: 6,
        unitPrice: 845,
        unitOfMeasure: "drum",
        lineTotal: 5070,
      },
      {
        lineNumber: 2,
        description: "Acid bath chemistry — refresh charge",
        quantity: 1,
        unitPrice: 4220,
        unitOfMeasure: "lot",
        lineTotal: 4220,
      },
      {
        lineNumber: 3,
        description: "Hazmat surcharge",
        quantity: 1,
        unitPrice: 560,
        unitOfMeasure: "ea",
        lineTotal: 560,
      },
    ],
  },

  // ── Fairfield Electric ────────────────────────────────────────────────
  {
    id: "po-1294",
    poNumber: "PO-1294",
    vendorId: "vendor-fairfield-electric-001",
    status: "closed",
    issuedAt: "2026-03-19T10:00:00Z",
    expectedDeliveryAt: "2026-04-09T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 7480,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Conduit — 1in EMT (10ft length, case of 10)",
        quantity: 40,
        unitPrice: 64,
        unitOfMeasure: "case",
        lineTotal: 2560,
      },
      {
        lineNumber: 2,
        description: "Wire — 12 AWG THHN (500ft spool)",
        quantity: 12,
        unitPrice: 168,
        unitOfMeasure: "spool",
        lineTotal: 2016,
      },
      {
        lineNumber: 3,
        description: "Breakers — 20A single pole (case of 20)",
        quantity: 8,
        unitPrice: 363,
        unitOfMeasure: "case",
        lineTotal: 2904,
      },
    ],
  },
  {
    id: "po-1434",
    poNumber: "PO-1434",
    vendorId: "vendor-fairfield-electric-001",
    status: "open",
    issuedAt: "2026-04-25T10:00:00Z",
    expectedDeliveryAt: "2026-05-16T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 4350,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "LED high-bay fixtures — 200W",
        quantity: 15,
        unitPrice: 290,
        unitOfMeasure: "ea",
        lineTotal: 4350,
      },
    ],
  },

  // ── Harborline Shipping ───────────────────────────────────────────────
  {
    id: "po-1364",
    poNumber: "PO-1364",
    vendorId: "vendor-harborline-shipping-001",
    status: "open",
    issuedAt: "2026-04-09T10:00:00Z",
    expectedDeliveryAt: "2026-05-05T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 6840,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Ocean freight — container MSCU-9281427",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "ea",
        lineTotal: 4200,
      },
      {
        lineNumber: 2,
        description: "Customs brokerage",
        quantity: 1,
        unitPrice: 1240,
        unitOfMeasure: "ea",
        lineTotal: 1240,
      },
      {
        lineNumber: 3,
        description: "Port handling and demurrage",
        quantity: 1,
        unitPrice: 1400,
        unitOfMeasure: "ea",
        lineTotal: 1400,
      },
    ],
  },

  // ── Northstar HVAC ────────────────────────────────────────────────────
  {
    id: "po-1396",
    poNumber: "PO-1396",
    vendorId: "vendor-northstar-hvac-001",
    status: "open",
    issuedAt: "2026-04-14T09:30:00Z",
    expectedDeliveryAt: "2026-05-05T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 8420,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Spring HVAC tune-up — Plant A (5 RTUs)",
        quantity: 5,
        unitPrice: 845,
        unitOfMeasure: "ea",
        lineTotal: 4225,
      },
      {
        lineNumber: 2,
        description: "Filter replacement — MERV 13 (case of 12)",
        quantity: 8,
        unitPrice: 174,
        unitOfMeasure: "case",
        lineTotal: 1392,
      },
      {
        lineNumber: 3,
        description: "Refrigerant top-up — R-410A",
        quantity: 1,
        unitPrice: 2803,
        unitOfMeasure: "lot",
        lineTotal: 2803,
      },
    ],
  },

  // ── Silverbrook Consulting ────────────────────────────────────────────
  {
    id: "po-1380",
    poNumber: "PO-1380",
    vendorId: "vendor-silverbrook-consult-001",
    status: "open",
    issuedAt: "2026-04-07T15:00:00Z",
    expectedDeliveryAt: "2026-06-07T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 32800,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Operational excellence engagement — Phase 2 (May 2026)",
        quantity: 1,
        unitPrice: 32800,
        unitOfMeasure: "ea",
        lineTotal: 32800,
      },
    ],
  },

  // ── Prairieview Catering ──────────────────────────────────────────────
  {
    id: "po-1416",
    poNumber: "PO-1416",
    vendorId: "vendor-prairieview-foods-001",
    status: "closed",
    issuedAt: "2026-04-22T11:00:00Z",
    expectedDeliveryAt: "2026-04-28T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 2240,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Lunch catering — quarterly all-hands (80 guests)",
        quantity: 80,
        unitPrice: 28,
        unitOfMeasure: "ea",
        lineTotal: 2240,
      },
    ],
  },

  // ── Arroyo Construction ───────────────────────────────────────────────
  {
    id: "po-1252",
    poNumber: "PO-1252",
    vendorId: "vendor-arroyo-construction-001",
    status: "open",
    issuedAt: "2026-02-28T14:00:00Z",
    expectedDeliveryAt: "2026-07-15T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 145000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Plant B loading dock expansion — labor",
        quantity: 1,
        unitPrice: 88000,
        unitOfMeasure: "ea",
        lineTotal: 88000,
      },
      {
        lineNumber: 2,
        description: "Concrete, rebar, and structural steel materials",
        quantity: 1,
        unitPrice: 57000,
        unitOfMeasure: "lot",
        lineTotal: 57000,
      },
    ],
  },

  // ── Bluefin Security ──────────────────────────────────────────────────
  {
    id: "po-1325",
    poNumber: "PO-1325",
    vendorId: "vendor-bluefin-security-001",
    status: "open",
    issuedAt: "2026-04-01T07:30:00Z",
    expectedDeliveryAt: "2026-04-30T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 8200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Site security — Plant A (April 2026, 4 weeks)",
        quantity: 4,
        unitPrice: 2050,
        unitOfMeasure: "wk",
        lineTotal: 8200,
      },
    ],
    glDefault: { account: "62700", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },
  {
    id: "po-1421",
    poNumber: "PO-1421",
    vendorId: "vendor-bluefin-security-001",
    status: "open",
    issuedAt: "2026-04-29T07:30:00Z",
    expectedDeliveryAt: "2026-05-31T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 8200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Site security — Plant A (May 2026, 4 weeks)",
        quantity: 4,
        unitPrice: 2050,
        unitOfMeasure: "wk",
        lineTotal: 8200,
      },
    ],
    glDefault: { account: "62700", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },

  // ── Millbrook MRO ─────────────────────────────────────────────────────
  {
    id: "po-1308",
    poNumber: "PO-1308",
    vendorId: "vendor-millbrook-mro-001",
    status: "closed",
    issuedAt: "2026-03-17T12:30:00Z",
    expectedDeliveryAt: "2026-04-01T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 4180,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Safety gloves — nitrile (case of 100)",
        quantity: 24,
        unitPrice: 65,
        unitOfMeasure: "case",
        lineTotal: 1560,
      },
      {
        lineNumber: 2,
        description: "Safety glasses — clear (case of 50)",
        quantity: 8,
        unitPrice: 92,
        unitOfMeasure: "case",
        lineTotal: 736,
      },
      {
        lineNumber: 3,
        description: "Ear plugs — corded (case of 200)",
        quantity: 4,
        unitPrice: 88,
        unitOfMeasure: "case",
        lineTotal: 352,
      },
      {
        lineNumber: 4,
        description: "Hand tools — assorted (Klein, Stanley)",
        quantity: 1,
        unitPrice: 1532,
        unitOfMeasure: "lot",
        lineTotal: 1532,
      },
    ],
  },
  {
    id: "po-1402",
    poNumber: "PO-1402",
    vendorId: "vendor-millbrook-mro-001",
    status: "open",
    issuedAt: "2026-04-16T12:30:00Z",
    expectedDeliveryAt: "2026-05-05T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 3290,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Lubricants — way oil ISO 68 (5-gal pail)",
        quantity: 18,
        unitPrice: 95,
        unitOfMeasure: "ea",
        lineTotal: 1710,
      },
      {
        lineNumber: 2,
        description: "Cutting fluid — water-soluble (5-gal pail)",
        quantity: 10,
        unitPrice: 158,
        unitOfMeasure: "ea",
        lineTotal: 1580,
      },
    ],
  },
  {
    id: "po-1446",
    poNumber: "PO-1446",
    vendorId: "vendor-millbrook-mro-001",
    status: "open",
    issuedAt: "2026-04-28T12:30:00Z",
    expectedDeliveryAt: "2026-05-14T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 1890,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Drill bits — cobalt (assorted sizes, case)",
        quantity: 6,
        unitPrice: 145,
        unitOfMeasure: "case",
        lineTotal: 870,
      },
      {
        lineNumber: 2,
        description: "End mills — carbide 4-flute (assorted, case)",
        quantity: 4,
        unitPrice: 255,
        unitOfMeasure: "case",
        lineTotal: 1020,
      },
    ],
  },

  // ── Summit Talent ─────────────────────────────────────────────────────
  {
    id: "po-1366",
    poNumber: "PO-1366",
    vendorId: "vendor-summit-recruiting-001",
    status: "open",
    issuedAt: "2026-04-10T10:00:00Z",
    expectedDeliveryAt: "2026-06-10T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 36000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Executive search — Director of Operations placement fee",
        quantity: 1,
        unitPrice: 36000,
        unitOfMeasure: "ea",
        lineTotal: 36000,
      },
    ],
  },

  // ── Blackford Insurance ───────────────────────────────────────────────
  {
    id: "po-1233",
    poNumber: "PO-1233",
    vendorId: "vendor-blackford-insurance-001",
    status: "open",
    issuedAt: "2026-02-28T09:00:00Z",
    expectedDeliveryAt: "2027-02-28T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 52000,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Commercial general liability — annual premium (2026-2027)",
        quantity: 1,
        unitPrice: 36000,
        unitOfMeasure: "yr",
        lineTotal: 36000,
      },
      {
        lineNumber: 2,
        description: "Property insurance — Plant A & B (annual premium)",
        quantity: 1,
        unitPrice: 16000,
        unitOfMeasure: "yr",
        lineTotal: 16000,
      },
    ],
  },

  // ── Pinegrove Landscape (removed from vendor list; reassign POs) ──────
  // (none — vendor not in seed)

  // ── Marina Bay IT (SG) ────────────────────────────────────────────────
  {
    id: "po-1377",
    poNumber: "PO-1377",
    vendorId: "vendor-marina-it-001",
    status: "open",
    issuedAt: "2026-04-11T03:00:00Z",
    expectedDeliveryAt: "2026-05-12T08:00:00Z",
    approver: "Priya Raman",
    totalAmount: 12400,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Network infrastructure — Cisco switches (4)",
        quantity: 4,
        unitPrice: 2400,
        unitOfMeasure: "ea",
        lineTotal: 9600,
      },
      {
        lineNumber: 2,
        description: "Installation labor",
        quantity: 1,
        unitPrice: 2800,
        unitOfMeasure: "ea",
        lineTotal: 2800,
      },
    ],
  },

  // ── Changi Freight Forwarders (SG) ────────────────────────────────────
  {
    id: "po-1359",
    poNumber: "PO-1359",
    vendorId: "vendor-changi-logistics-001",
    status: "open",
    issuedAt: "2026-04-04T03:00:00Z",
    expectedDeliveryAt: "2026-05-08T08:00:00Z",
    approver: "Priya Raman",
    totalAmount: 5640,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Air freight — components shipment (Singapore to Hong Kong)",
        quantity: 1,
        unitPrice: 3840,
        unitOfMeasure: "ea",
        lineTotal: 3840,
      },
      {
        lineNumber: 2,
        description: "Customs clearance",
        quantity: 1,
        unitPrice: 1800,
        unitOfMeasure: "ea",
        lineTotal: 1800,
      },
    ],
  },

  // ── Orchard Facilities (SG) ───────────────────────────────────────────
  {
    id: "po-1346",
    poNumber: "PO-1346",
    vendorId: "vendor-orchard-facilities-001",
    status: "open",
    issuedAt: "2026-04-01T03:00:00Z",
    expectedDeliveryAt: "2026-04-30T23:00:00Z",
    approver: "Priya Raman",
    totalAmount: 8200,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Singapore office facilities mgmt — April 2026 retainer",
        quantity: 1,
        unitPrice: 8200,
        unitOfMeasure: "mo",
        lineTotal: 8200,
      },
    ],
  },
  {
    id: "po-1440",
    poNumber: "PO-1440",
    vendorId: "vendor-orchard-facilities-001",
    status: "open",
    issuedAt: "2026-04-28T03:00:00Z",
    expectedDeliveryAt: "2026-05-31T23:00:00Z",
    approver: "Priya Raman",
    totalAmount: 8200,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Singapore office facilities mgmt — May 2026 retainer",
        quantity: 1,
        unitPrice: 8200,
        unitOfMeasure: "mo",
        lineTotal: 8200,
      },
    ],
  },

  // ── Raffles Legal (SG) ────────────────────────────────────────────────
  {
    id: "po-1394",
    poNumber: "PO-1394",
    vendorId: "vendor-raffles-legal-001",
    status: "open",
    issuedAt: "2026-04-14T03:00:00Z",
    expectedDeliveryAt: "2026-05-20T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 14200,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Singapore entity — contract review (April 2026)",
        quantity: 22,
        unitPrice: 645.45,
        unitOfMeasure: "hr",
        lineTotal: 14200,
      },
    ],
  },

  // ── Thames Print (GB) ─────────────────────────────────────────────────
  {
    id: "po-1334",
    poNumber: "PO-1334",
    vendorId: "vendor-thames-print-001",
    status: "open",
    issuedAt: "2026-04-04T09:00:00Z",
    expectedDeliveryAt: "2026-05-02T17:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 3850,
    currency: "GBP",
    lines: [
      {
        lineNumber: 1,
        description: "Brochures — full colour, A4 8pp (5000 copies)",
        quantity: 5000,
        unitPrice: 0.42,
        unitOfMeasure: "ea",
        lineTotal: 2100,
      },
      {
        lineNumber: 2,
        description: "Business cards — full colour duplex (3000)",
        quantity: 3000,
        unitPrice: 0.583,
        unitOfMeasure: "ea",
        lineTotal: 1750,
      },
    ],
  },

  // ── Mancunian Engineering (GB) ────────────────────────────────────────
  {
    id: "po-1320",
    poNumber: "PO-1320",
    vendorId: "vendor-mancunian-engineering-001",
    status: "open",
    issuedAt: "2026-03-28T11:00:00Z",
    expectedDeliveryAt: "2026-05-12T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 18400,
    currency: "GBP",
    lines: [
      {
        lineNumber: 1,
        description: "Spare parts — conveyor system rollers (200)",
        quantity: 200,
        unitPrice: 56,
        unitOfMeasure: "ea",
        lineTotal: 11200,
      },
      {
        lineNumber: 2,
        description: "Drive motors — 1.5kW geared",
        quantity: 8,
        unitPrice: 900,
        unitOfMeasure: "ea",
        lineTotal: 7200,
      },
    ],
  },

  // ── London Couriers (GB) ──────────────────────────────────────────────
  {
    id: "po-1404",
    poNumber: "PO-1404",
    vendorId: "vendor-london-couriers-001",
    status: "open",
    issuedAt: "2026-04-17T09:00:00Z",
    expectedDeliveryAt: "2026-05-17T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 1240,
    currency: "GBP",
    lines: [
      {
        lineNumber: 1,
        description: "Same-day courier — London metro (April 2026, 18 jobs)",
        quantity: 18,
        unitPrice: 68.89,
        unitOfMeasure: "ea",
        lineTotal: 1240,
      },
    ],
  },

  // ── Sydney Harbour IT (AU) ────────────────────────────────────────────
  {
    id: "po-1388",
    poNumber: "PO-1388",
    vendorId: "vendor-sydney-harbour-it-001",
    status: "open",
    issuedAt: "2026-04-13T22:30:00Z",
    expectedDeliveryAt: "2026-05-09T07:00:00Z",
    approver: "Priya Raman",
    totalAmount: 6800,
    currency: "AUD",
    lines: [
      {
        lineNumber: 1,
        description: "Laptops — Dell Latitude 5440 (4)",
        quantity: 4,
        unitPrice: 1450,
        unitOfMeasure: "ea",
        lineTotal: 5800,
      },
      {
        lineNumber: 2,
        description: "Docking stations and accessories",
        quantity: 4,
        unitPrice: 250,
        unitOfMeasure: "ea",
        lineTotal: 1000,
      },
    ],
  },

  // ── Melbourne Printworks (AU) ─────────────────────────────────────────
  {
    id: "po-1361",
    poNumber: "PO-1361",
    vendorId: "vendor-melbourne-printworks-001",
    status: "open",
    issuedAt: "2026-04-05T22:30:00Z",
    expectedDeliveryAt: "2026-05-02T07:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 2840,
    currency: "AUD",
    lines: [
      {
        lineNumber: 1,
        description: "Catalogue print run — A5 24pp (2500 copies)",
        quantity: 2500,
        unitPrice: 0.86,
        unitOfMeasure: "ea",
        lineTotal: 2150,
      },
      {
        lineNumber: 2,
        description: "Fulfilment — pick, pack, mail",
        quantity: 1,
        unitPrice: 690,
        unitOfMeasure: "ea",
        lineTotal: 690,
      },
    ],
  },

  // ── Additional fillers to reach 80 ────────────────────────────────────
  {
    id: "po-1391",
    poNumber: "PO-1391",
    vendorId: "vendor-fairfield-electric-001",
    status: "open",
    issuedAt: "2026-04-15T10:00:00Z",
    expectedDeliveryAt: "2026-05-13T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 5840,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Junction boxes — NEMA 4X (40)",
        quantity: 40,
        unitPrice: 78,
        unitOfMeasure: "ea",
        lineTotal: 3120,
      },
      {
        lineNumber: 2,
        description: "Cable trays — 12in ladder (10ft section)",
        quantity: 16,
        unitPrice: 170,
        unitOfMeasure: "ea",
        lineTotal: 2720,
      },
    ],
  },
  {
    id: "po-1428",
    poNumber: "PO-1428",
    vendorId: "vendor-northstar-hvac-001",
    status: "open",
    issuedAt: "2026-04-24T09:30:00Z",
    expectedDeliveryAt: "2026-05-22T17:00:00Z",
    approver: "Daniel Park",
    totalAmount: 14200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Replacement RTU compressor — Plant B unit 3",
        quantity: 1,
        unitPrice: 11800,
        unitOfMeasure: "ea",
        lineTotal: 11800,
      },
      {
        lineNumber: 2,
        description: "Labor — install and commission",
        quantity: 8,
        unitPrice: 300,
        unitOfMeasure: "hr",
        lineTotal: 2400,
      },
    ],
  },
  {
    id: "po-1444",
    poNumber: "PO-1444",
    vendorId: "vendor-silverbrook-consult-001",
    status: "open",
    issuedAt: "2026-05-01T15:00:00Z",
    expectedDeliveryAt: "2026-07-01T23:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 18400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Supply chain assessment — discovery workshop",
        quantity: 1,
        unitPrice: 18400,
        unitOfMeasure: "ea",
        lineTotal: 18400,
      },
    ],
  },
  {
    id: "po-1457",
    poNumber: "PO-1457",
    vendorId: "vendor-prairieview-foods-001",
    status: "open",
    issuedAt: "2026-05-04T11:00:00Z",
    expectedDeliveryAt: "2026-05-22T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 1620,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Coffee & snacks service — May 2026 (Plant A)",
        quantity: 1,
        unitPrice: 1620,
        unitOfMeasure: "mo",
        lineTotal: 1620,
      },
    ],
  },
  {
    id: "po-1463",
    poNumber: "PO-1463",
    vendorId: "vendor-marina-it-001",
    status: "open",
    issuedAt: "2026-05-05T03:00:00Z",
    expectedDeliveryAt: "2026-05-26T08:00:00Z",
    approver: "Priya Raman",
    totalAmount: 6200,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "MS Office 365 licences — annual (40 users)",
        quantity: 40,
        unitPrice: 155,
        unitOfMeasure: "yr",
        lineTotal: 6200,
      },
    ],
  },
  {
    id: "po-1465",
    poNumber: "PO-1465",
    vendorId: "vendor-rosehill-staffing-001",
    status: "open",
    issuedAt: "2026-05-05T08:00:00Z",
    expectedDeliveryAt: "2026-06-01T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 9500,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Temporary line staff — 200 hrs (late May 2026)",
        quantity: 200,
        unitPrice: 47.5,
        unitOfMeasure: "hr",
        lineTotal: 9500,
      },
    ],
  },
  {
    id: "po-1467",
    poNumber: "PO-1467",
    vendorId: "vendor-cascade-001",
    status: "open",
    issuedAt: "2026-05-06T09:15:00Z",
    expectedDeliveryAt: "2026-05-20T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 2180,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Whiteboards — magnetic 4ft x 6ft (3)",
        quantity: 3,
        unitPrice: 380,
        unitOfMeasure: "ea",
        lineTotal: 1140,
      },
      {
        lineNumber: 2,
        description: "Conference phones — Poly Trio C60",
        quantity: 2,
        unitPrice: 520,
        unitOfMeasure: "ea",
        lineTotal: 1040,
      },
    ],
  },
  {
    id: "po-1469",
    poNumber: "PO-1469",
    vendorId: "vendor-london-couriers-001",
    status: "open",
    issuedAt: "2026-05-08T09:00:00Z",
    expectedDeliveryAt: "2026-06-08T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 985,
    currency: "GBP",
    lines: [
      {
        lineNumber: 1,
        description: "Same-day courier — London metro (early May 2026)",
        quantity: 14,
        unitPrice: 70.36,
        unitOfMeasure: "ea",
        lineTotal: 985,
      },
    ],
  },
  {
    id: "po-1471",
    poNumber: "PO-1471",
    vendorId: "vendor-thames-print-001",
    status: "open",
    issuedAt: "2026-05-09T09:00:00Z",
    expectedDeliveryAt: "2026-06-05T17:00:00Z",
    approver: "Eleanor Hastings",
    totalAmount: 2240,
    currency: "GBP",
    lines: [
      {
        lineNumber: 1,
        description: "Annual report — A4 32pp full colour (500 copies)",
        quantity: 500,
        unitPrice: 4.48,
        unitOfMeasure: "ea",
        lineTotal: 2240,
      },
    ],
  },
  {
    id: "po-1473",
    poNumber: "PO-1473",
    vendorId: "vendor-changi-logistics-001",
    status: "open",
    issuedAt: "2026-05-10T03:00:00Z",
    expectedDeliveryAt: "2026-06-08T08:00:00Z",
    approver: "Priya Raman",
    totalAmount: 3400,
    currency: "SGD",
    lines: [
      {
        lineNumber: 1,
        description: "Sea freight — components shipment (Singapore to Sydney)",
        quantity: 1,
        unitPrice: 2400,
        unitOfMeasure: "ea",
        lineTotal: 2400,
      },
      {
        lineNumber: 2,
        description: "Documentation",
        quantity: 1,
        unitPrice: 1000,
        unitOfMeasure: "ea",
        lineTotal: 1000,
      },
    ],
  },
  {
    id: "po-1477",
    poNumber: "PO-1477",
    vendorId: "vendor-aclng-001",
    status: "open",
    issuedAt: "2026-05-12T14:00:00Z",
    expectedDeliveryAt: "2026-06-30T23:00:00Z",
    approver: "Daniel Park",
    totalAmount: 4200,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Monthly cleaning service — Plant A — June 2026",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "mo",
        lineTotal: 4200,
      },
    ],
    glDefault: { account: "62100", costCenter: "PLANT-A", entity: "AcmeCo US" },
  },
  {
    id: "po-1479",
    poNumber: "PO-1479",
    vendorId: "vendor-westpoint-mkt-001",
    status: "open",
    issuedAt: "2026-05-12T15:00:00Z",
    expectedDeliveryAt: "2026-06-15T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 6800,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Trade show booth design and assets",
        quantity: 1,
        unitPrice: 6800,
        unitOfMeasure: "ea",
        lineTotal: 6800,
      },
    ],
  },
  {
    id: "po-1481",
    poNumber: "PO-1481",
    vendorId: "vendor-pacific-dist-001",
    status: "open",
    issuedAt: "2026-05-13T08:30:00Z",
    expectedDeliveryAt: "2026-06-05T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 19400,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Plastic totes — stackable (case of 6)",
        quantity: 80,
        unitPrice: 145,
        unitOfMeasure: "case",
        lineTotal: 11600,
      },
      {
        lineNumber: 2,
        description: "Pallet jack — electric (1)",
        quantity: 1,
        unitPrice: 7800,
        unitOfMeasure: "ea",
        lineTotal: 7800,
      },
    ],
  },
  {
    id: "po-1483",
    poNumber: "PO-1483",
    vendorId: "vendor-atlantic-001",
    status: "open",
    issuedAt: "2026-05-13T11:30:00Z",
    expectedDeliveryAt: "2026-05-30T17:00:00Z",
    approver: "Helena Brooks",
    totalAmount: 24600,
    currency: "USD",
    lines: [
      {
        lineNumber: 1,
        description: "Industrial bearings — SKF 6309-2RS1",
        quantity: 200,
        unitPrice: 84,
        unitOfMeasure: "ea",
        lineTotal: 16800,
      },
      {
        lineNumber: 2,
        description: "Bearing pullers — heavy duty",
        quantity: 6,
        unitPrice: 1300,
        unitOfMeasure: "ea",
        lineTotal: 7800,
      },
    ],
  },
]

const PO_INDEX: Map<PurchaseOrderId, PurchaseOrder> = new Map(
  SEED_POS.map((p) => [p.id, p])
)

export function getPO(id: PurchaseOrderId): PurchaseOrder | undefined {
  return PO_INDEX.get(id)
}
