// 51 fictional vendor invoices for the invoice-processing demo: 50 in the
// "current" cohort plus 1 historical paid invoice (`inv-998123-a`) that serves
// as the duplicate target for the hero scenario.
//
// Composition (today's inbox = 31 items received in last 24h):
// - 24 auto-posted today (clean 3-way / 2-way matches, OCR ≥ 0.96)
// -  2 needs-review today (the 3-way match hero + the GST hero)
// -  4 exception today (price variance hero + GL ambiguous hero +
//      missing GRN hero + 1 OCR low-confidence)
// -  1 duplicate-suspected today (the duplicate hero, INV-998123-B)
// Plus historical / yesterday's items:
// -  7 historical auto-posted (received 2-7 days ago, audit-log demos)
// -  2 exception items received yesterday (multi-currency + master-agreement)
// -  1 historical paid duplicate-target (`inv-998123-a`, received Apr 5)
//
// Source of truth: docs/handoff/invoice-processing/04-data-model.md
//   § "Static seed shape" > "seed-invoices.ts".
// Hero copy alignment: docs/handoff/invoice-processing/05-demo-script.md.
//
// Hero invoices (do NOT edit copy without also updating the demo script):
//   - inv-998123-b               duplicate hero ($42,800, Acme Cleaning)
//   - inv-998123-a               historical paid (the duplicate's target)
//   - inv-acme-may-2026          3-way match + GL coding hero ($4,200)
//   - inv-singapore-stationery-may  GST input-tax-credit hero (SGD 8,640)
//   - inv-ne-4471                price variance hero ($48,000)
//   - inv-atlantic-77103         early-pay discount hero ($46,000)
//
// Other named invoices referenced in dashboard / chat context:
//   - inv-westpoint-mkt-001      GL ambiguous exception
//   - inv-pacific-logistics-001  Missing GRN exception
//   - inv-pacific-dist-22019     2nd early-pay discount

import type { Invoice, InvoiceId } from "./types"

// ════════════════════════════════════════════════════════════════════
// Hero invoices — verbatim per the data-model spec + demo script
// ════════════════════════════════════════════════════════════════════

const HERO_INVOICES: Invoice[] = [
  // ── Duplicate hero ────────────────────────────────────────────────────
  {
    id: "inv-998123-b",
    invoiceNumber: "INV-998123-B",
    vendorId: "vendor-aclng-001",
    amount: 42800,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-14T09:18:00Z",
    issuedAt: "2026-05-14",
    dueAt: "2026-06-13",
    termsLabel: "Net-30",
    status: "duplicate-suspected",
    ocrConfidence: 0.99,
    matchMode: "duplicate",
    lines: [
      { lineNumber: 1, description: "Q2 deep-clean — Plant A", quantity: 1, unitPrice: 18400, unitOfMeasure: "ea", lineTotal: 18400 },
      { lineNumber: 2, description: "Q2 deep-clean — Plant B", quantity: 1, unitPrice: 14200, unitOfMeasure: "ea", lineTotal: 14200 },
      { lineNumber: 3, description: "Equipment rental — industrial vac (1 wk)", quantity: 1, unitPrice: 10200, unitOfMeasure: "wk", lineTotal: 10200 },
    ],
    duplicateFinding: {
      duplicateOfInvoiceId: "inv-998123-a",
      duplicateOfApplicationId: "app-998123-a",
      similarityScore: 0.99,
      matchSignals: {
        sameInvoiceNumber: false,
        sameAmount: true,
        sameVendor: true,
        lineItemSimilarity: 1.0,
        daysApart: 26,
      },
      reasoning:
        "Same vendor (Acme Cleaning Services). Same amount ($42,800). All 3 line items verbatim. Different invoice number suffix (998123-A vs 998123-B), 26 days apart. Vendor pattern: monthly cleaning + quarterly deep-clean. They've already billed Q2 once.",
      recommendedAction: "do-not-post",
      draftedVendorEmail: {
        to: "ap@acmecleaning.com",
        cc: "tom.matsuda@acmecleaning.com",
        subject: "Duplicate invoice INV-998123 — already paid",
        body:
          "Hi Tom,\n\nWe received invoice INV-998123-B for $42,800 dated May 14 for Q2 deep-clean services across Plants A and B plus equipment rental. Our records show invoice INV-998123-A was issued April 5 with identical line items, and we paid it April 18 (Tipalti reference TIP-77492).\n\nCould you confirm whether INV-998123-B is a duplicate before we re-process? Happy to share the original remittance if helpful.\n\nThanks,\nLena",
      },
    },
  },

  // ── Historical paid duplicate-target ──────────────────────────────────
  {
    id: "inv-998123-a",
    invoiceNumber: "INV-998123-A",
    vendorId: "vendor-aclng-001",
    amount: 42800,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-04-05T08:14:00Z",
    issuedAt: "2026-04-05",
    dueAt: "2026-05-05",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1422",
    poId: "po-1422",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Q2 deep-clean — Plant A", quantity: 1, unitPrice: 18400, unitOfMeasure: "ea", lineTotal: 18400, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Q2 deep-clean — Plant B", quantity: 1, unitPrice: 14200, unitOfMeasure: "ea", lineTotal: 14200, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Equipment rental — industrial vac (1 wk)", quantity: 1, unitPrice: 10200, unitOfMeasure: "wk", lineTotal: 10200, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
    ],
    matchProposal: {
      type: "3way",
      poId: "po-1422",
      grnId: "grn-aclng-q2",
      totalVariance: 0,
      confidence: 1.0,
      reasoning:
        "Invoice matched PO-1422 (quarterly deep-clean Plants A + B + equipment rental, approved Mar 28 by Daniel Park). GRN-Q2-ACLNG confirmed all 3 services performed Apr 6-15, verified by Plant A + B managers.",
      sources: ["PO record", "GRN record"],
    },
    glProposal: {
      account: "62100",
      accountLabel: "Maintenance & Supplies",
      costCenter: "PLANT-A",
      entity: "AcmeCo US",
      confidence: 0.96,
      reasoning:
        "Per master agreement §2.3, Acme Cleaning Services posts to Maintenance & Supplies — Plant A. Q2 deep-clean follows the same coding as monthly recurring service.",
      sources: ["master agreement §2.3", "vendor history (11 invoices)", "GL chart"],
    },
  },

  // ── 3-way match + GL coding hero ──────────────────────────────────────
  {
    id: "inv-acme-may-2026",
    invoiceNumber: "INV-AC-2206-MAY",
    vendorId: "vendor-aclng-001",
    amount: 4200,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T06:42:01Z",
    issuedAt: "2026-05-01",
    dueAt: "2026-05-31",
    termsLabel: "Net-30",
    status: "needs-review",
    poRef: "PO-1389",
    poId: "po-1389",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      {
        lineNumber: 1,
        description: "Cleaning Plant A — May 2026",
        quantity: 1,
        unitPrice: 4200,
        unitOfMeasure: "mo",
        lineTotal: 4200,
        matchedPoLineNumber: 1,
        matchedGrnLineNumber: 1,
      },
    ],
    matchProposal: {
      type: "3way",
      poId: "po-1389",
      grnId: "grn-441",
      totalVariance: 0,
      confidence: 1.0,
      reasoning:
        "Invoice line matches PO-1389 line 1 exactly ($4,200 monthly cleaning). GRN-441 confirms service performed May 1–31, verified by Plant A manager.",
      sources: ["PO record", "GRN record"],
    },
    glProposal: {
      account: "62100",
      accountLabel: "Maintenance & Supplies",
      costCenter: "PLANT-A",
      entity: "AcmeCo US",
      confidence: 0.94,
      reasoning:
        "Per master agreement §2.3 (signed Jan 2024), monthly cleaning service from Acme Cleaning Services is coded to Maintenance & Supplies — Plant A. Confirmed against last 12 invoices from this vendor (Jun 2025 – Apr 2026), all coded the same way and posted without exception.",
      sources: ["master agreement §2.3", "vendor invoice history (12 invoices)", "GL chart"],
    },
  },

  // ── Singapore GST input-tax-credit hero ───────────────────────────────
  {
    id: "inv-singapore-stationery-may",
    invoiceNumber: "SGS-2206",
    vendorId: "vendor-sgs-001",
    amount: 8640,
    currency: "SGD",
    channel: "billcom",
    receivedAt: "2026-05-15T02:14:00Z",
    issuedAt: "2026-05-10",
    dueAt: "2026-06-09",
    termsLabel: "Net-30",
    status: "needs-review",
    poRef: "PO-1462",
    poId: "po-1462",
    ocrConfidence: 0.96,
    matchMode: "tax",
    lines: [
      { lineNumber: 1, description: "A4 paper — 50 ream", quantity: 50, unitPrice: 36, unitOfMeasure: "ream", lineTotal: 1800, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Toner cartridges — assorted", quantity: 12, unitPrice: 350, unitOfMeasure: "ea", lineTotal: 4200, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Office supplies — misc", quantity: 1, unitPrice: 2000, unitOfMeasure: "lot", lineTotal: 2000, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
    ],
    taxLine: {
      type: "GST",
      rate: 0.08,
      base: 8000,
      amount: 640,
      jurisdiction: "Singapore",
    },
    glProposal: {
      account: "63200",
      accountLabel: "Office Supplies",
      costCenter: "CORP-SG",
      entity: "AcmeCo Singapore",
      confidence: 0.92,
      reasoning:
        "Singapore Stationery's office-supply invoices code to 63200 Office Supplies for the AcmeCo Singapore entity. Cost center CORP-SG per master agreement.",
      sources: ["vendor master record", "GL chart", "master agreement"],
    },
    taxProposal: {
      treatment: "INPUT_TAX_CREDIT_ELIGIBLE",
      taxAccount: "21800",
      amount: 640,
      confidence: 0.96,
      reasoning:
        "Per IRAS GST Act §20(3), input tax incurred on supplies for business purposes by a GST-registered person is recoverable. All four eligibility tests pass: vendor is GST-registered (202012345W, validated against IRAS today), invoice meets IRAS format requirements, business-purpose confirmed (office supplies), receiving entity (AcmeCo Singapore) is GST-registered.",
      sources: ["IRAS GST registry", "invoice format validation", "master agreement (office supplies T&Cs)"],
      eligibilityChecks: [
        { label: "Vendor is GST-registered", passed: true },
        { label: "Vendor's GST registration is active as of today", passed: true },
        { label: "Invoice meets IRAS format requirements", passed: true },
        { label: "Receiving entity (AcmeCo Singapore) is GST-registered", passed: true },
      ],
    },
  },

  // ── Price variance exception hero ─────────────────────────────────────
  {
    id: "inv-ne-4471",
    invoiceNumber: "4471",
    vendorId: "vendor-northeast-001",
    amount: 48000,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-15T05:11:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-11",
    termsLabel: "Net-30",
    status: "exception",
    poRef: "PO-1208",
    poId: "po-1208",
    ocrConfidence: 1.0,
    matchMode: "exception",
    lines: [
      { lineNumber: 1, description: "Steel pipe fittings — 2in stainless", quantity: 200, unitPrice: 28, unitOfMeasure: "ea", lineTotal: 5600, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Steel pipe fittings — 3in stainless", quantity: 150, unitPrice: 42, unitOfMeasure: "ea", lineTotal: 6300, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Industrial gaskets — Viton 4in", quantity: 320, unitPrice: 18, unitOfMeasure: "ea", lineTotal: 5760, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
      {
        lineNumber: 4,
        description: "Pressure relief valves — model PRV-2200",
        quantity: 375,
        unitPrice: 48,
        unitOfMeasure: "ea",
        lineTotal: 18000,
        matchedPoLineNumber: 4,
        matchedGrnLineNumber: 4,
        variance: {
          type: "price",
          amount: 1500,
          explanation:
            "Vendor's separate price-escalation memo (May 1) requests $52/unit vs the PO's $48/unit, which would add $1,500 across 375 units. Invoice line currently bills at PO price pending master-agreement update.",
        },
      },
      { lineNumber: 5, description: "Pipe insulation — fiberglass 4in (per ft)", quantity: 1200, unitPrice: 4.45, unitOfMeasure: "ft", lineTotal: 5340, matchedPoLineNumber: 5, matchedGrnLineNumber: 5 },
      { lineNumber: 6, description: "Mounting brackets — heavy duty", quantity: 350, unitPrice: 20, unitOfMeasure: "ea", lineTotal: 7000, matchedPoLineNumber: 6, matchedGrnLineNumber: 6 },
    ],
    exception: {
      reasonCode: "PRICE_VARIANCE",
      neoInvestigation:
        "PO line 4 priced at $48/unit; vendor's May 1 escalation memo requests $52/unit on the next invoice ($1,500 across 375 units). Vendor billed at PO price this cycle but flagged the proposed change in the memo. Master agreement library has not been updated. Recommend confirm with Daniel before next billing cycle.",
      proposedAction: "Update master agreement OR push back on escalation before next invoice",
    },
  },

  // ── Early-pay discount hero ───────────────────────────────────────────
  {
    id: "inv-atlantic-77103",
    invoiceNumber: "AI-77103",
    vendorId: "vendor-atlantic-001",
    amount: 46000,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-13T07:00:00Z",
    issuedAt: "2026-05-11",
    dueAt: "2026-06-10",
    termsLabel: "2/10 net 30",
    status: "auto-posted",
    poRef: "PO-1455",
    poId: "po-1455",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Industrial bearings — SKF 6209-2RS1", quantity: 400, unitPrice: 65, unitOfMeasure: "ea", lineTotal: 26000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Drive belts — heavy-duty V-belt assortment", quantity: 100, unitPrice: 200, unitOfMeasure: "ea", lineTotal: 20000, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: {
      type: "3way",
      poId: "po-1455",
      grnId: "grn-457",
      totalVariance: 0,
      confidence: 1.0,
      reasoning:
        "Invoice line items match PO-1455 (bearings + drive belts) and GRN-457 confirms full receipt May 9 (400 bearings + 100 belts).",
      sources: ["PO record", "GRN record"],
    },
    earlyPayDiscount: {
      eligible: true,
      discountAmount: 920,
      payByDate: "2026-05-21",
      deadlineDays: 6,
      termsLabel: "2/10 net 30",
    },
  },
]

// ════════════════════════════════════════════════════════════════════
// Other named exceptions (referenced in dashboard + chat context)
// ════════════════════════════════════════════════════════════════════

const NAMED_EXCEPTIONS: Invoice[] = [
  // ── GL ambiguous exception (Westpoint Marketing) ──────────────────────
  {
    id: "inv-westpoint-mkt-001",
    invoiceNumber: "WPM-2426",
    vendorId: "vendor-westpoint-mkt-001",
    amount: 4200,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T07:48:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-11",
    termsLabel: "Net-30",
    status: "exception",
    poRef: "PO-1431",
    poId: "po-1431",
    ocrConfidence: 0.97,
    matchMode: "exception",
    lines: [
      { lineNumber: 1, description: "May campaign assets — digital + event mix", quantity: 1, unitPrice: 4200, unitOfMeasure: "lot", lineTotal: 4200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    glProposal: {
      account: "65100",
      accountLabel: "Marketing — Digital",
      costCenter: "CORP-US",
      entity: "AcmeCo US",
      confidence: 0.62,
      reasoning:
        "Line description mixes digital and event-marketing language. Vendor history is 50/50 split between Marketing — Digital (65100) and Marketing — Events (65200) over the last 12 invoices. No clear winner from invoice copy alone.",
      sources: ["GL chart", "vendor history (12 invoices)", "invoice line description"],
      alternatives: [
        { account: "65200", accountLabel: "Marketing — Events", confidence: 0.34 },
        { account: "65900", accountLabel: "Marketing — Other", confidence: 0.04 },
      ],
    },
    exception: {
      reasonCode: "GL_AMBIGUOUS",
      neoInvestigation:
        "Line item described as 'May campaign assets — digital + event mix'. Vendor history splits roughly 50/50 between Marketing — Digital (65100) and Marketing — Events (65200). Best guess is digital at 62% confidence — below auto-post threshold of 85%. Recommend Lena confirm coding.",
      proposedAction: "Confirm GL coding (Marketing — Digital vs Marketing — Events)",
    },
  },

  // ── Missing GRN exception (Pacific Logistics) ─────────────────────────
  {
    id: "inv-pacific-logistics-001",
    invoiceNumber: "PL-22481",
    vendorId: "vendor-pacific-logistics-001",
    amount: 8940,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T06:08:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-12",
    termsLabel: "Net-30",
    status: "exception",
    poRef: "PO-1314",
    poId: "po-1314",
    ocrConfidence: 0.97,
    matchMode: "exception",
    lines: [
      { lineNumber: 1, description: "Inbound freight — container PALC-22487 (Oakland to Plant A)", quantity: 1, unitPrice: 5200, unitOfMeasure: "ea", lineTotal: 5200 },
      { lineNumber: 2, description: "Drayage and chassis fees", quantity: 1, unitPrice: 1840, unitOfMeasure: "ea", lineTotal: 1840 },
      { lineNumber: 3, description: "Fuel surcharge", quantity: 1, unitPrice: 1900, unitOfMeasure: "ea", lineTotal: 1900 },
    ],
    matchProposal: {
      type: "2way",
      poId: "po-1314",
      totalVariance: 0,
      confidence: 0.86,
      reasoning:
        "Invoice matches PO-1314 line-for-line ($5,200 + $1,840 + $1,900 = $8,940). No GRN logged for this PO — container delivery hasn't been confirmed by receiving in 5 days. Cannot complete 3-way match.",
      sources: ["PO record", "receiving log (no entry)"],
    },
    exception: {
      reasonCode: "MISSING_GRN",
      neoInvestigation:
        "PO-1314 matched cleanly to invoice ($8,940 — inbound freight, drayage, fuel surcharge). No GRN logged for container PALC-22487 in 5 days. Likely either receiving hasn't logged it yet OR container delayed at port. Drafted email to receiving + Pacific Logistics ops.",
      proposedAction: "Send receiving confirmation request + vendor delivery status query",
      draftedEmail: {
        to: "receiving@acmeco.com",
        cc: "marcus.reed@pacificlogistics.com",
        subject: "Confirm receipt — container PALC-22487 (PO-1314)",
        body:
          "Hi team,\n\nWe received Pacific Logistics invoice PL-22481 ($8,940) for container PALC-22487 from Oakland to Plant A, but no GRN has been logged for PO-1314.\n\nReceiving: could you confirm whether the container has been received, and log it in the system if so?\n\nMarcus: if there's been a delay at port, please let us know the revised ETA.\n\nThanks,\nLena",
      },
    },
  },

  // ── Second early-pay discount (Pacific Distribution) ──────────────────
  {
    id: "inv-pacific-dist-22019",
    invoiceNumber: "PD-22019",
    vendorId: "vendor-pacific-dist-001",
    amount: 32500,
    currency: "USD",
    channel: "coupa",
    receivedAt: "2026-05-14T11:42:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-11",
    termsLabel: "2/10 net 30",
    status: "auto-posted",
    poRef: "PO-1376",
    poId: "po-1376",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Plastic totes — stackable (case of 6)", quantity: 12, unitPrice: 1850, unitOfMeasure: "case", lineTotal: 22200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Pallet wrap — heavy-duty (roll)", quantity: 40, unitPrice: 257.5, unitOfMeasure: "roll", lineTotal: 10300, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: {
      type: "3way",
      poId: "po-1376",
      grnId: "grn-379",
      totalVariance: 0,
      confidence: 0.97,
      reasoning:
        "Invoice partially bills PO-1376 ($32,500 of $38,400 total) — 12 cases totes + 40 rolls pallet wrap received May 12 per GRN-379. Remaining $5,900 expected on next shipment.",
      sources: ["PO record", "GRN record", "vendor partial-shipment history"],
    },
    earlyPayDiscount: {
      eligible: true,
      discountAmount: 920,
      payByDate: "2026-05-22",
      deadlineDays: 7,
      termsLabel: "2/10 net 30",
    },
  },

  // ── OCR low-confidence exception (today) ──────────────────────────────
  {
    id: "inv-coastal-print-3318",
    invoiceNumber: "CP-3318",
    vendorId: "vendor-coastal-print-001",
    amount: 1640,
    currency: "USD",
    channel: "photo",
    receivedAt: "2026-05-15T04:32:00Z",
    issuedAt: "2026-05-09",
    dueAt: "2026-06-08",
    termsLabel: "Net-30",
    status: "exception",
    poRef: "PO-1338",
    poId: "po-1338",
    ocrConfidence: 0.71,
    matchMode: "exception",
    lines: [
      { lineNumber: 1, description: "Trade show banners — 4 large format", quantity: 4, unitPrice: 220, unitOfMeasure: "ea", lineTotal: 880, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Branded brochures — 6 box (250/box)", quantity: 6, unitPrice: 127, unitOfMeasure: "box", lineTotal: 762, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    exception: {
      reasonCode: "OCR_LOW_CONFIDENCE",
      neoInvestigation:
        "Photo invoice uploaded via mobile. OCR confidence 71% — below 85% auto-post threshold. Line 2 unit price reads as either $127.00 or $137.00 from the photo; line totals ($1,640 vs $1,642) don't exactly reconcile either way. Recommend manual entry to confirm.",
      proposedAction: "Confirm line-2 unit price and total against the original document",
    },
  },

  // ── Multi-currency review (yesterday, GBP) ────────────────────────────
  {
    id: "inv-mancunian-eng-7741",
    invoiceNumber: "ME-7741",
    vendorId: "vendor-mancunian-engineering-001",
    amount: 18400,
    currency: "GBP",
    channel: "email",
    receivedAt: "2026-05-14T10:28:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-27",
    termsLabel: "Net-45",
    status: "exception",
    poRef: "PO-1320",
    poId: "po-1320",
    ocrConfidence: 0.96,
    matchMode: "exception",
    lines: [
      { lineNumber: 1, description: "Replacement spare parts — gearbox assembly", quantity: 200, unitPrice: 80, unitOfMeasure: "ea", lineTotal: 16000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Shipping crate + freight (Manchester)", quantity: 8, unitPrice: 300, unitOfMeasure: "ea", lineTotal: 2400, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    exception: {
      reasonCode: "MULTI_CURRENCY_REVIEW",
      neoInvestigation:
        "GBP 18,400 invoice from Mancunian Engineering for AcmeCo UK entity. PO + GRN match cleanly. FX policy requires treasury review for any non-USD invoice over GBP 15,000. Hold pending FX hedge confirmation.",
      proposedAction: "Route to treasury for FX policy check",
    },
  },

  // ── Master-agreement review (yesterday, Meridian Power) ───────────────
  {
    id: "inv-meridian-pwr-9921",
    invoiceNumber: "MP-9921",
    vendorId: "vendor-meridian-001",
    amount: 38200,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-14T13:14:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-27",
    termsLabel: "Net-45",
    status: "exception",
    poRef: "PO-1448",
    poId: "po-1448",
    ocrConfidence: 1.0,
    matchMode: "exception",
    lines: [
      { lineNumber: 1, description: "Switchgear installation — Plant A panel B", quantity: 1, unitPrice: 30200, unitOfMeasure: "ea", lineTotal: 30200, matchedPoLineNumber: 1 },
      {
        lineNumber: 2,
        description: "Annual maintenance contract — first quarter pro-rate",
        quantity: 1,
        unitPrice: 8000,
        unitOfMeasure: "ea",
        lineTotal: 8000,
        matchedPoLineNumber: 2,
        variance: {
          type: "price",
          amount: 2200,
          explanation:
            "Line 2 pro-rated maintenance higher than PO line 2 by $2,200. Possible master-agreement service-rate update from Feb 2026 not yet recorded in the agreement library.",
        },
      },
    ],
    exception: {
      reasonCode: "MASTER_AGREEMENT_REVIEW",
      neoInvestigation:
        "Variance of $2,200 on maintenance line. Meridian sent a Feb 2026 service-rate update but it hasn't been merged into the master agreement library. Confirm with Daniel whether the new rate is approved before posting.",
      proposedAction: "Update master agreement library OR request vendor credit for $2,200",
    },
  },
]

// ════════════════════════════════════════════════════════════════════
// Auto-posted today (22 more, today's date 2026-05-15)
// Channel mix target: email 14, EDI-810 8, Bill.com 5, Coupa 3 across full inbox.
// Hero auto-posted today: inv-atlantic-77103 (edi-810).
// Other named auto-posted today: none (inv-pacific-dist-22019 is yesterday).
// ════════════════════════════════════════════════════════════════════

const AUTO_POSTED_TODAY: Invoice[] = [
  // 1. Blue Peak Materials — closed PO from Mar (regular replenishment) — billcom
  {
    id: "inv-bluepeak-8821",
    invoiceNumber: "BP-8821",
    vendorId: "vendor-bluepeak-001",
    amount: 18650,
    currency: "USD",
    channel: "billcom",
    receivedAt: "2026-05-15T03:12:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-11",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1267",
    poId: "po-1267",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Construction aggregate — 100 ton", quantity: 100, unitPrice: 142, unitOfMeasure: "ton", lineTotal: 14200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Reinforcement mesh — 30 panel", quantity: 30, unitPrice: 148.33, unitOfMeasure: "panel", lineTotal: 4450, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1267", grnId: "grn-271", totalVariance: 0, confidence: 0.98, reasoning: "Invoice matches PO-1267 line totals exactly; GRN-271 confirms full receipt Mar 28.", sources: ["PO record", "GRN record"] },
  },
  // 2. Bluepeak — May replenishment — email
  {
    id: "inv-bluepeak-8889",
    invoiceNumber: "BP-8889",
    vendorId: "vendor-bluepeak-001",
    amount: 24350,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T05:24:00Z",
    issuedAt: "2026-05-09",
    dueAt: "2026-06-08",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1408",
    poId: "po-1408",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Aggregate — fine 500 ton", quantity: 500, unitPrice: 38, unitOfMeasure: "ton", lineTotal: 19000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Cement bags — 75 each", quantity: 75, unitPrice: 71.33, unitOfMeasure: "bag", lineTotal: 5350, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1408", grnId: "grn-413", totalVariance: 0, confidence: 0.98, reasoning: "PO + GRN match cleanly; vendor has 98% on-time-in-full history.", sources: ["PO record", "GRN record"] },
  },
  // 3. Cascade Office Solutions — May office order — email
  {
    id: "inv-cascade-5142",
    invoiceNumber: "CO-5142",
    vendorId: "vendor-cascade-001",
    amount: 5280,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T07:02:00Z",
    issuedAt: "2026-05-08",
    dueAt: "2026-06-07",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1419",
    poId: "po-1419",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Standing desk — adjustable (4)", quantity: 4, unitPrice: 720, unitOfMeasure: "ea", lineTotal: 2880, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Office chairs — ergonomic (6)", quantity: 6, unitPrice: 400, unitOfMeasure: "ea", lineTotal: 2400, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1419", grnId: "grn-422", totalVariance: 0, confidence: 0.97, reasoning: "Invoice matches PO-1419 + GRN-422 line-for-line.", sources: ["PO record", "GRN record"] },
  },
  // 4. Summit IT — monthly managed services — billcom
  {
    id: "inv-summit-it-may",
    invoiceNumber: "SIT-2226",
    vendorId: "vendor-summit-it-001",
    amount: 9000,
    currency: "USD",
    channel: "billcom",
    receivedAt: "2026-05-15T01:18:00Z",
    issuedAt: "2026-05-01",
    dueAt: "2026-05-31",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1370",
    poId: "po-1370",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Managed services — May 2026 (helpdesk + monitoring)", quantity: 1, unitPrice: 9000, unitOfMeasure: "mo", lineTotal: 9000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1370", grnId: "grn-374", totalVariance: 0, confidence: 1.0, reasoning: "Recurring service confirmation matched PO-1370 + GRN-374 for May SLA period.", sources: ["PO record", "GRN record"] },
  },
  // 5. Ironbridge — finished housings — edi-810
  {
    id: "inv-ironbridge-2114",
    invoiceNumber: "IB-2114",
    vendorId: "vendor-ironbridge-001",
    amount: 42700,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-15T02:00:00Z",
    issuedAt: "2026-05-10",
    dueAt: "2026-07-09",
    termsLabel: "Net-60",
    status: "auto-posted",
    poRef: "PO-1356",
    poId: "po-1356",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Machined housings — IB-2114 drawing", quantity: 35, unitPrice: 1220, unitOfMeasure: "ea", lineTotal: 42700, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1356", grnId: "grn-360", totalVariance: 0, confidence: 1.0, reasoning: "All 35 housings received per GRN-360 (passed drawing inspection).", sources: ["PO record", "GRN record"] },
  },
  // 6. Greenfield Packaging — May restock — email
  {
    id: "inv-greenfield-pkg-3340",
    invoiceNumber: "GP-3340",
    vendorId: "vendor-greenfield-pkg-001",
    amount: 8950,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T06:18:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-12",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1411",
    poId: "po-1411",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Shipping boxes — 60 bundle", quantity: 60, unitPrice: 58.5, unitOfMeasure: "bundle", lineTotal: 3510, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Bubble wrap — 500 yd roll", quantity: 500, unitPrice: 10.88, unitOfMeasure: "yd", lineTotal: 5440, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1411", grnId: "grn-414", totalVariance: 0, confidence: 0.97, reasoning: "Line items + totals match PO-1411 + GRN-414.", sources: ["PO record", "GRN record"] },
  },
  // 7. Tri-State Freight — closed PO (May freight) — edi-810
  {
    id: "inv-tristate-9912",
    invoiceNumber: "TSF-9912",
    vendorId: "vendor-tristate-freight-001",
    amount: 4200,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-15T03:48:00Z",
    issuedAt: "2026-05-08",
    dueAt: "2026-06-07",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1453",
    poId: "po-1453",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Atlanta DC delivery — LTL", quantity: 1, unitPrice: 2400, unitOfMeasure: "ea", lineTotal: 2400, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "LTL shipments — 8 lanes (per tariff)", quantity: 8, unitPrice: 200, unitOfMeasure: "ea", lineTotal: 1600, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Fuel surcharge", quantity: 1, unitPrice: 200, unitOfMeasure: "ea", lineTotal: 200, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
    ],
    matchProposal: { type: "3way", poId: "po-1453", grnId: "grn-456", totalVariance: 0, confidence: 1.0, reasoning: "Service confirmation GRN-456 confirms all 8 lanes delivered May 2-8.", sources: ["PO record", "GRN record"] },
  },
  // 8. Redwood Janitorial — supplies — email
  {
    id: "inv-redwood-jntr-441",
    invoiceNumber: "RJ-441",
    vendorId: "vendor-redwood-jntr-001",
    amount: 1980,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T04:42:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-11",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1425",
    poId: "po-1425",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Cleaning supplies — assorted (12 cases)", quantity: 12, unitPrice: 110, unitOfMeasure: "case", lineTotal: 1320, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Trash liners — 6 carton", quantity: 6, unitPrice: 110, unitOfMeasure: "carton", lineTotal: 660, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1425", grnId: "grn-428", totalVariance: 0, confidence: 0.98, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // 9. East River Chemical — closed PO — email
  {
    id: "inv-eastriver-chem-7720",
    invoiceNumber: "ERC-7720",
    vendorId: "vendor-eastriver-chem-001",
    amount: 14200,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T07:24:00Z",
    issuedAt: "2026-05-09",
    dueAt: "2026-06-23",
    termsLabel: "Net-45",
    status: "auto-posted",
    poRef: "PO-1318",
    poId: "po-1318",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Reagent drums — 8 each (55-gal)", quantity: 8, unitPrice: 1450, unitOfMeasure: "ea", lineTotal: 11600, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Hazmat handling surcharge", quantity: 1, unitPrice: 1800, unitOfMeasure: "ea", lineTotal: 1800, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Lab consumables — assorted", quantity: 1, unitPrice: 800, unitOfMeasure: "lot", lineTotal: 800, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
    ],
    matchProposal: { type: "3way", poId: "po-1318", grnId: "grn-321", totalVariance: 0, confidence: 0.97, reasoning: "Drums + surcharge + consumables match PO + GRN.", sources: ["PO record", "GRN record"] },
  },
  // 10. Fairfield Electric — May fixtures — email
  {
    id: "inv-fairfield-2233",
    invoiceNumber: "FE-2233",
    vendorId: "vendor-fairfield-electric-001",
    amount: 4350,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T08:02:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-12",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1434",
    poId: "po-1434",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "LED panel fixtures — 15 each", quantity: 15, unitPrice: 290, unitOfMeasure: "ea", lineTotal: 4350, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1434", grnId: "grn-436", totalVariance: 0, confidence: 0.98, reasoning: "PO + GRN match cleanly.", sources: ["PO record", "GRN record"] },
  },
  // 11. Fairfield Electric — May commodity — email
  {
    id: "inv-fairfield-2235",
    invoiceNumber: "FE-2235",
    vendorId: "vendor-fairfield-electric-001",
    amount: 5840,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T08:18:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-12",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1391",
    poId: "po-1391",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Conduit — 1in EMT (40 stick)", quantity: 40, unitPrice: 96, unitOfMeasure: "stick", lineTotal: 3840, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Junction boxes — 16 each", quantity: 16, unitPrice: 125, unitOfMeasure: "ea", lineTotal: 2000, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1391", grnId: "grn-393", totalVariance: 0, confidence: 0.98, reasoning: "PO + GRN match cleanly.", sources: ["PO record", "GRN record"] },
  },
  // 12. Northstar HVAC — service confirmation — email
  {
    id: "inv-northstar-hvac-562",
    invoiceNumber: "NH-562",
    vendorId: "vendor-northstar-hvac-001",
    amount: 8420,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T04:08:00Z",
    issuedAt: "2026-05-06",
    dueAt: "2026-06-05",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1396",
    poId: "po-1396",
    ocrConfidence: 0.97,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "RTU preventive maintenance — 5 units", quantity: 5, unitPrice: 1200, unitOfMeasure: "ea", lineTotal: 6000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Filters replaced (8)", quantity: 8, unitPrice: 240, unitOfMeasure: "ea", lineTotal: 1920, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Service report + commissioning", quantity: 1, unitPrice: 500, unitOfMeasure: "ea", lineTotal: 500, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
    ],
    matchProposal: { type: "3way", poId: "po-1396", grnId: "grn-398", totalVariance: 0, confidence: 0.96, reasoning: "Service confirmation logged Apr 28 – May 5; matches invoice line items.", sources: ["PO record", "GRN record"] },
  },
  // 13. Bluefin Security — May guard service — billcom
  {
    id: "inv-bluefin-may",
    invoiceNumber: "BFS-2226-MAY",
    vendorId: "vendor-bluefin-security-001",
    amount: 8200,
    currency: "USD",
    channel: "billcom",
    receivedAt: "2026-05-15T01:42:00Z",
    issuedAt: "2026-05-01",
    dueAt: "2026-05-31",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1421",
    poId: "po-1421",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Guard coverage — May 2026 (4 weeks, Plant A)", quantity: 4, unitPrice: 2050, unitOfMeasure: "wk", lineTotal: 8200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1421", grnId: "grn-425", totalVariance: 0, confidence: 1.0, reasoning: "Recurring guard service confirmed May 1-31 via GRN-425.", sources: ["PO record", "GRN record"] },
  },
  // 14. Millbrook MRO — small parts (May) — coupa
  {
    id: "inv-millbrook-7714",
    invoiceNumber: "MB-7714",
    vendorId: "vendor-millbrook-mro-001",
    amount: 1890,
    currency: "USD",
    channel: "coupa",
    receivedAt: "2026-05-15T05:00:00Z",
    issuedAt: "2026-05-14",
    dueAt: "2026-06-13",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1446",
    poId: "po-1446",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Fasteners — assorted bolts (6 box)", quantity: 6, unitPrice: 215, unitOfMeasure: "box", lineTotal: 1290, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Hand tools — replacement (4)", quantity: 4, unitPrice: 150, unitOfMeasure: "ea", lineTotal: 600, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1446", grnId: "grn-449", totalVariance: 0, confidence: 0.98, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // 15. Clearwater Utilities — May metered — email
  {
    id: "inv-clearwater-may",
    invoiceNumber: "CWU-2226-MAY",
    vendorId: "vendor-clearwater-utils-001",
    amount: 11800,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T02:48:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-02",
    termsLabel: "Net-21",
    status: "auto-posted",
    poRef: "PO-1382",
    poId: "po-1382",
    ocrConfidence: 1.0,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Plant A water + power — May metered", quantity: 1, unitPrice: 11800, unitOfMeasure: "mo", lineTotal: 11800 },
    ],
    matchProposal: { type: "2way", poId: "po-1382", totalVariance: 0, confidence: 0.99, reasoning: "Metered utility invoice — 2-way match to PO-1382; no GRN required for metered services.", sources: ["PO record", "vendor invoice history (utilities)"] },
  },
  // 16. Tri-State Freight — daily freight (closed PO from prior month) — edi-810
  {
    id: "inv-tristate-9938",
    invoiceNumber: "TSF-9938",
    vendorId: "vendor-tristate-freight-001",
    amount: 3850,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-15T04:18:00Z",
    issuedAt: "2026-05-14",
    dueAt: "2026-06-13",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1331",
    poId: "po-1331",
    ocrConfidence: 1.0,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Weekly LTL freight — week of May 11", quantity: 1, unitPrice: 3850, unitOfMeasure: "wk", lineTotal: 3850 },
    ],
    matchProposal: { type: "2way", poId: "po-1331", totalVariance: 0, confidence: 0.94, reasoning: "Standing freight PO; matches typical week ($3.5K-$4.2K range).", sources: ["PO record", "vendor history (freight)"] },
  },
  // 17. Marina Bay IT (SG) — switches and laptops — billcom
  {
    id: "inv-marina-it-3318",
    invoiceNumber: "MBI-3318",
    vendorId: "vendor-marina-it-001",
    amount: 12400,
    currency: "SGD",
    channel: "billcom",
    receivedAt: "2026-05-15T01:00:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-11",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1377",
    poId: "po-1377",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "MacBook Pro 14 — 4 each", quantity: 4, unitPrice: 2400, unitOfMeasure: "ea", lineTotal: 9600, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Network switch — racked", quantity: 1, unitPrice: 2800, unitOfMeasure: "ea", lineTotal: 2800, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1377", grnId: "grn-381", totalVariance: 0, confidence: 0.97, reasoning: "All 4 laptops + switch received per GRN-381 May 12.", sources: ["PO record", "GRN record"] },
  },
  // 18. Thames Print (GB) — print job — email
  {
    id: "inv-thames-print-661",
    invoiceNumber: "TP-661",
    vendorId: "vendor-thames-print-001",
    amount: 3850,
    currency: "GBP",
    channel: "email",
    receivedAt: "2026-05-15T03:36:00Z",
    issuedAt: "2026-05-02",
    dueAt: "2026-06-01",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1334",
    poId: "po-1334",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Brand brochures — 5,000 print run", quantity: 5000, unitPrice: 0.4, unitOfMeasure: "ea", lineTotal: 2000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Trade flyers — 3,000 print run", quantity: 3000, unitPrice: 0.6166667, unitOfMeasure: "ea", lineTotal: 1850, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1334", grnId: "grn-338", totalVariance: 0, confidence: 0.97, reasoning: "PO + GRN match cleanly.", sources: ["PO record", "GRN record"] },
  },
  // 19. Orchard Facilities (SG) — May retainer — billcom
  {
    id: "inv-orchard-fm-may",
    invoiceNumber: "OFM-2226-MAY",
    vendorId: "vendor-orchard-facilities-001",
    amount: 8200,
    currency: "SGD",
    channel: "billcom",
    receivedAt: "2026-05-15T00:32:00Z",
    issuedAt: "2026-05-01",
    dueAt: "2026-05-31",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1440",
    poId: "po-1440",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Facilities retainer — May 2026 (Singapore office)", quantity: 1, unitPrice: 8200, unitOfMeasure: "mo", lineTotal: 8200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1440", grnId: "grn-444", totalVariance: 0, confidence: 1.0, reasoning: "Recurring retainer confirmed for May per GRN-444.", sources: ["PO record", "GRN record"] },
  },
  // 20. Cascade Office — additional small order — coupa
  {
    id: "inv-cascade-5188",
    invoiceNumber: "CO-5188",
    vendorId: "vendor-cascade-001",
    amount: 2180,
    currency: "USD",
    channel: "coupa",
    receivedAt: "2026-05-15T06:55:00Z",
    issuedAt: "2026-05-13",
    dueAt: "2026-06-12",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1467",
    poId: "po-1467",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Office monitors — 27in (3)", quantity: 3, unitPrice: 460, unitOfMeasure: "ea", lineTotal: 1380, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Docking stations (2)", quantity: 2, unitPrice: 400, unitOfMeasure: "ea", lineTotal: 800, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1467", grnId: "grn-471", totalVariance: 0, confidence: 0.97, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // 21. Acme Cleaning — pre-paid June (PO-1477) — email
  {
    id: "inv-acme-june-prepay",
    invoiceNumber: "INV-AC-2206-JUN",
    vendorId: "vendor-aclng-001",
    amount: 4200,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-15T07:38:00Z",
    issuedAt: "2026-05-14",
    dueAt: "2026-06-13",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1477",
    poId: "po-1477",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Pre-paid June cleaning service — Plant A", quantity: 1, unitPrice: 4200, unitOfMeasure: "mo", lineTotal: 4200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1477", grnId: "grn-468", totalVariance: 0, confidence: 0.96, reasoning: "Pre-paid June service confirmed; GL coding per master agreement §2.3.", sources: ["PO record", "GRN record", "master agreement §2.3"] },
    glProposal: {
      account: "62100",
      accountLabel: "Maintenance & Supplies",
      costCenter: "PLANT-A",
      entity: "AcmeCo US",
      confidence: 0.95,
      reasoning: "Per master agreement §2.3, Acme Cleaning monthly service → 62100 Maintenance & Supplies / Plant A.",
      sources: ["master agreement §2.3", "vendor history (12 invoices)", "GL chart"],
    },
  },
  // 22. Northeast Industrial — closed PO from Apr — edi-810
  {
    id: "inv-northeast-4408",
    invoiceNumber: "4408",
    vendorId: "vendor-northeast-001",
    amount: 32400,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-15T01:24:00Z",
    issuedAt: "2026-05-14",
    dueAt: "2026-06-13",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1351",
    poId: "po-1351",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Steel beams — I-beam W8x18 (60 ft)", quantity: 60, unitPrice: 320, unitOfMeasure: "ft", lineTotal: 19200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Steel plates — 1/2in × 4ft × 8ft (80)", quantity: 80, unitPrice: 165, unitOfMeasure: "ea", lineTotal: 13200, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1351", grnId: "grn-355", totalVariance: 0, confidence: 0.99, reasoning: "Full receipt confirmed Apr 15 via GRN-355.", sources: ["PO record", "GRN record"] },
  },
]

// ════════════════════════════════════════════════════════════════════
// Historical auto-posted (7 items, received 2-7 days ago, for audit log)
// ════════════════════════════════════════════════════════════════════

const HISTORICAL_POSTED: Invoice[] = [
  // H1. Acme Cleaning — April monthly (already posted)
  {
    id: "inv-acme-apr-2026",
    invoiceNumber: "INV-AC-2226-APR",
    vendorId: "vendor-aclng-001",
    amount: 4200,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-08T07:14:00Z",
    issuedAt: "2026-05-01",
    dueAt: "2026-05-31",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1311",
    poId: "po-1311",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Cleaning Plant A — April 2026", quantity: 1, unitPrice: 4200, unitOfMeasure: "mo", lineTotal: 4200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1311", grnId: "grn-432", totalVariance: 0, confidence: 1.0, reasoning: "Matched PO-1311 + GRN-432; same coding as the rest of the recurring series.", sources: ["PO record", "GRN record"] },
    glProposal: {
      account: "62100",
      accountLabel: "Maintenance & Supplies",
      costCenter: "PLANT-A",
      entity: "AcmeCo US",
      confidence: 0.95,
      reasoning: "Per master agreement §2.3.",
      sources: ["master agreement §2.3", "vendor history (11 invoices)", "GL chart"],
    },
  },
  // H2. Bluepeak Materials — March order (closed PO-1267 follow-up)
  {
    id: "inv-bluepeak-8804",
    invoiceNumber: "BP-8804",
    vendorId: "vendor-bluepeak-001",
    amount: 14820,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-13T05:32:00Z",
    issuedAt: "2026-05-11",
    dueAt: "2026-06-10",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1437",
    poId: "po-1437",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Construction aggregate — 30 ton", quantity: 30, unitPrice: 494, unitOfMeasure: "ton", lineTotal: 14820, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1437", grnId: "grn-441b", totalVariance: 0, confidence: 0.97, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // H3. Greenfield Packaging — early May
  {
    id: "inv-greenfield-pkg-3318",
    invoiceNumber: "GP-3318",
    vendorId: "vendor-greenfield-pkg-001",
    amount: 14820,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-10T05:14:00Z",
    issuedAt: "2026-04-02",
    dueAt: "2026-05-02",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1303",
    poId: "po-1303",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Mailer envelopes — 30 carton", quantity: 30, unitPrice: 110, unitOfMeasure: "carton", lineTotal: 3300, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Air pillows — 40 case", quantity: 40, unitPrice: 145.5, unitOfMeasure: "case", lineTotal: 5820, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
      { lineNumber: 3, description: "Pallet wrap — bulk", quantity: 1, unitPrice: 5700, unitOfMeasure: "lot", lineTotal: 5700, matchedPoLineNumber: 3, matchedGrnLineNumber: 3 },
    ],
    matchProposal: { type: "3way", poId: "po-1303", grnId: "grn-307", totalVariance: 0, confidence: 0.97, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // H4. Atlantic Industrial — March bearings
  {
    id: "inv-atlantic-77081",
    invoiceNumber: "AI-77081",
    vendorId: "vendor-atlantic-001",
    amount: 28400,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-09T06:48:00Z",
    issuedAt: "2026-03-28",
    dueAt: "2026-04-27",
    termsLabel: "2/10 net 30",
    status: "auto-posted",
    poRef: "PO-1342",
    poId: "po-1342",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Industrial bearings — SKF 6309 (20)", quantity: 20, unitPrice: 920, unitOfMeasure: "ea", lineTotal: 18400, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Drive couplings — flexible (50)", quantity: 50, unitPrice: 200, unitOfMeasure: "ea", lineTotal: 10000, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1342", grnId: "grn-345", totalVariance: 0, confidence: 1.0, reasoning: "Full receipt confirmed Mar 28; standard auto-post.", sources: ["PO record", "GRN record"] },
  },
  // H5. Meridian Power — generator install (Apr)
  {
    id: "inv-meridian-pwr-9914",
    invoiceNumber: "MP-9914",
    vendorId: "vendor-meridian-001",
    amount: 68400,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-12T09:22:00Z",
    issuedAt: "2026-04-22",
    dueAt: "2026-06-06",
    termsLabel: "Net-45",
    status: "auto-posted",
    poRef: "PO-1295",
    poId: "po-1295",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Generator unit — 750kVA diesel", quantity: 1, unitPrice: 52000, unitOfMeasure: "ea", lineTotal: 52000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Commissioning + load testing", quantity: 1, unitPrice: 16400, unitOfMeasure: "ea", lineTotal: 16400, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1295", grnId: "grn-298", totalVariance: 0, confidence: 1.0, reasoning: "Generator delivered + commissioned per GRN-298.", sources: ["PO record", "GRN record"] },
  },
  // H6. Pacific Distribution — Mar order (closed PO)
  {
    id: "inv-pacific-dist-22014",
    invoiceNumber: "PD-22014",
    vendorId: "vendor-pacific-dist-001",
    amount: 22800,
    currency: "USD",
    channel: "coupa",
    receivedAt: "2026-05-11T08:18:00Z",
    issuedAt: "2026-03-30",
    dueAt: "2026-04-29",
    termsLabel: "2/10 net 30",
    status: "auto-posted",
    poRef: "PO-1289",
    poId: "po-1289",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Plastic totes — case of 6 (24)", quantity: 24, unitPrice: 550, unitOfMeasure: "case", lineTotal: 13200, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Stretch wrap — bulk (60 roll)", quantity: 60, unitPrice: 160, unitOfMeasure: "roll", lineTotal: 9600, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1289", grnId: "grn-292", totalVariance: 0, confidence: 0.98, reasoning: "Full receipt confirmed Mar 30.", sources: ["PO record", "GRN record"] },
  },
  // H7. Cornerstone Legal — Mar legal hours
  {
    id: "inv-cornerstone-legal-118",
    invoiceNumber: "CL-118",
    vendorId: "vendor-cornerstone-legal-001",
    amount: 18400,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-08T11:42:00Z",
    issuedAt: "2026-04-30",
    dueAt: "2026-06-14",
    termsLabel: "Net-45",
    status: "auto-posted",
    poRef: "PO-1413",
    poId: "po-1413",
    ocrConfidence: 0.97,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Legal hours — April 2026 (commercial)", quantity: 40, unitPrice: 460, unitOfMeasure: "hr", lineTotal: 18400 },
    ],
    matchProposal: { type: "2way", poId: "po-1413", totalVariance: 0, confidence: 0.94, reasoning: "Hours billed within agreed monthly cap; 2-way match (no GRN for legal hours).", sources: ["PO record", "vendor history (legal)"] },
  },
]

// ════════════════════════════════════════════════════════════════════
// Inbox filler — additional invoices to round the cohort to 50.
// These are received over the last several days, all auto-posted, mix of
// channels and vendors. Purpose: visual depth for the inbox + audit log.
// ════════════════════════════════════════════════════════════════════

const FILLER: Invoice[] = [
  // F1. Rosehill Staffing — April hours
  {
    id: "inv-rosehill-2244",
    invoiceNumber: "RS-2244",
    vendorId: "vendor-rosehill-staffing-001",
    amount: 14820,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-08T09:20:00Z",
    issuedAt: "2026-04-30",
    dueAt: "2026-05-14",
    termsLabel: "Net-14",
    status: "auto-posted",
    poRef: "PO-1372",
    poId: "po-1372",
    ocrConfidence: 0.96,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Temp staffing — April hours", quantity: 380, unitPrice: 39, unitOfMeasure: "hr", lineTotal: 14820 },
    ],
    matchProposal: { type: "2way", poId: "po-1372", totalVariance: 0, confidence: 0.95, reasoning: "Hours within cap; standing PO; 2-way match.", sources: ["PO record", "vendor history"] },
  },
  // F2. Harborline Shipping — closed PO, auto-posted from EDI feed
  {
    id: "inv-harborline-3318",
    invoiceNumber: "HL-3318",
    vendorId: "vendor-harborline-shipping-001",
    amount: 6840,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-12T03:42:00Z",
    issuedAt: "2026-05-09",
    dueAt: "2026-06-08",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1364",
    poId: "po-1364",
    ocrConfidence: 1.0,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Container shipping — 3 TEU (Long Beach to Newark)", quantity: 3, unitPrice: 2280, unitOfMeasure: "TEU", lineTotal: 6840 },
    ],
    matchProposal: { type: "2way", poId: "po-1364", totalVariance: 0, confidence: 0.93, reasoning: "Standing shipping PO; freight 2-way match.", sources: ["PO record", "vendor history (shipping)"] },
  },
  // F3. Blackford Insurance — quarterly premium (recurring, no GRN)
  {
    id: "inv-blackford-q2",
    invoiceNumber: "BI-Q2-2026",
    vendorId: "vendor-blackford-insurance-001",
    amount: 52000,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-09T13:18:00Z",
    issuedAt: "2026-04-30",
    dueAt: "2026-05-30",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1233",
    poId: "po-1233",
    ocrConfidence: 0.99,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "GL + property insurance — Q2 2026", quantity: 1, unitPrice: 52000, unitOfMeasure: "qtr", lineTotal: 52000 },
    ],
    matchProposal: { type: "2way", poId: "po-1233", totalVariance: 0, confidence: 1.0, reasoning: "Quarterly premium per PO-1233 schedule.", sources: ["PO record", "vendor history (insurance)"] },
  },
  // F4. Coastal Print — Apr print run
  {
    id: "inv-coastal-print-3296",
    invoiceNumber: "CP-3296",
    vendorId: "vendor-coastal-print-001",
    amount: 1640,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-09T08:34:00Z",
    issuedAt: "2026-04-22",
    dueAt: "2026-05-22",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1338",
    poId: "po-1338",
    ocrConfidence: 0.94,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Trade show banners — 4 large format", quantity: 4, unitPrice: 220, unitOfMeasure: "ea", lineTotal: 880, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Branded brochures — 4 box (250/box)", quantity: 4, unitPrice: 190, unitOfMeasure: "box", lineTotal: 760, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1338", grnId: "grn-340", totalVariance: 0, confidence: 0.94, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // F5. Sydney Harbour IT (AU) — May order
  {
    id: "inv-sydney-it-7702",
    invoiceNumber: "SHI-7702",
    vendorId: "vendor-sydney-harbour-it-001",
    amount: 6800,
    currency: "AUD",
    channel: "email",
    receivedAt: "2026-05-12T02:12:00Z",
    issuedAt: "2026-05-09",
    dueAt: "2026-06-08",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1388",
    poId: "po-1388",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Workstation monitors — 4", quantity: 4, unitPrice: 850, unitOfMeasure: "ea", lineTotal: 3400, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Wireless headsets — 4", quantity: 4, unitPrice: 850, unitOfMeasure: "ea", lineTotal: 3400, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1388", grnId: "grn-392", totalVariance: 0, confidence: 0.97, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // F6. Singapore Stationery — Apr order (audit-log filler)
  {
    id: "inv-sgs-2206-apr",
    invoiceNumber: "SGS-2206-APR",
    vendorId: "vendor-sgs-001",
    amount: 5832,
    currency: "SGD",
    channel: "billcom",
    receivedAt: "2026-05-09T02:08:00Z",
    issuedAt: "2026-04-12",
    dueAt: "2026-05-12",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1398",
    poId: "po-1398",
    ocrConfidence: 0.97,
    matchMode: "tax",
    lines: [
      { lineNumber: 1, description: "Printer paper — 5 box (10 ream)", quantity: 5, unitPrice: 360, unitOfMeasure: "box", lineTotal: 1800, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Office supplies — assorted", quantity: 1, unitPrice: 3600, unitOfMeasure: "lot", lineTotal: 3600, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    taxLine: { type: "GST", rate: 0.08, base: 5400, amount: 432, jurisdiction: "Singapore" },
    matchProposal: { type: "3way", poId: "po-1398", grnId: "grn-405", totalVariance: 0, confidence: 0.97, reasoning: "PO + GRN match; GST input tax credit eligibility verified per master vendor record.", sources: ["PO record", "GRN record", "IRAS GST registry"] },
    glProposal: {
      account: "63200",
      accountLabel: "Office Supplies",
      costCenter: "CORP-SG",
      entity: "AcmeCo Singapore",
      confidence: 0.95,
      reasoning: "Same coding as recurring Singapore Stationery order.",
      sources: ["vendor master record", "GL chart"],
    },
  },
  // F7. Keystone SaaS — annual subscription (recurring service)
  {
    id: "inv-keystone-2026",
    invoiceNumber: "KS-2026-ANN",
    vendorId: "vendor-keystone-saas-001",
    amount: 26400,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-11T15:18:00Z",
    issuedAt: "2026-02-15",
    dueAt: "2026-03-17",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1198",
    poId: "po-1198",
    ocrConfidence: 1.0,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Annual platform subscription — Feb 2026 to Feb 2027", quantity: 1, unitPrice: 26400, unitOfMeasure: "yr", lineTotal: 26400 },
    ],
    matchProposal: { type: "2way", poId: "po-1198", totalVariance: 0, confidence: 0.97, reasoning: "Annual SaaS contract per PO-1198; matches master agreement §6.4.", sources: ["PO record", "master agreement §6.4"] },
    glProposal: {
      account: "64500",
      accountLabel: "Software Subscriptions",
      costCenter: "CORP-US",
      entity: "AcmeCo US",
      confidence: 0.97,
      reasoning: "Per master agreement §6.4, Keystone subscription posts to Software Subscriptions.",
      sources: ["master agreement §6.4", "GL chart"],
    },
  },
  // F8. Prairieview Catering — recurring office coffee/lunch service
  {
    id: "inv-prairieview-may",
    invoiceNumber: "PVC-2226-MAY",
    vendorId: "vendor-prairieview-foods-001",
    amount: 1620,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-13T12:14:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-05-26",
    termsLabel: "Net-14",
    status: "auto-posted",
    poRef: "PO-1457",
    poId: "po-1457",
    ocrConfidence: 0.98,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Office coffee + snacks — May (Mon-Fri restock)", quantity: 1, unitPrice: 1620, unitOfMeasure: "mo", lineTotal: 1620, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
    ],
    matchProposal: { type: "3way", poId: "po-1457", grnId: "grn-459", totalVariance: 0, confidence: 0.96, reasoning: "Recurring monthly service confirmed via GRN-459.", sources: ["PO record", "GRN record"] },
  },
  // F9. Melbourne Printworks (AU) — Apr direct mail
  {
    id: "inv-melb-print-1184",
    invoiceNumber: "MP-1184",
    vendorId: "vendor-melbourne-printworks-001",
    amount: 2840,
    currency: "AUD",
    channel: "email",
    receivedAt: "2026-05-10T01:18:00Z",
    issuedAt: "2026-05-02",
    dueAt: "2026-06-01",
    termsLabel: "Net-30",
    status: "auto-posted",
    poRef: "PO-1361",
    poId: "po-1361",
    ocrConfidence: 0.96,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Direct mail flyers — 2,500 print + mail", quantity: 2500, unitPrice: 1.05, unitOfMeasure: "ea", lineTotal: 2625, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Mail-out logistics", quantity: 1, unitPrice: 215, unitOfMeasure: "ea", lineTotal: 215, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1361", grnId: "grn-365", totalVariance: 0, confidence: 0.95, reasoning: "PO + GRN match.", sources: ["PO record", "GRN record"] },
  },
  // F10. Mancunian Engineering (GB) — closed (smaller order)
  {
    id: "inv-mancunian-7724",
    invoiceNumber: "ME-7724",
    vendorId: "vendor-mancunian-engineering-001",
    amount: 9200,
    currency: "GBP",
    channel: "email",
    receivedAt: "2026-05-13T10:08:00Z",
    issuedAt: "2026-05-12",
    dueAt: "2026-06-26",
    termsLabel: "Net-45",
    status: "auto-posted",
    poRef: "PO-1320",
    poId: "po-1320",
    ocrConfidence: 0.97,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Spare bearings — 100 each", quantity: 100, unitPrice: 80, unitOfMeasure: "ea", lineTotal: 8000, matchedPoLineNumber: 1, matchedGrnLineNumber: 1 },
      { lineNumber: 2, description: "Shipping (Manchester)", quantity: 4, unitPrice: 300, unitOfMeasure: "ea", lineTotal: 1200, matchedPoLineNumber: 2, matchedGrnLineNumber: 2 },
    ],
    matchProposal: { type: "3way", poId: "po-1320", grnId: "grn-324", totalVariance: 0, confidence: 0.95, reasoning: "Partial-receipt PO; matches GRN-324.", sources: ["PO record", "GRN record"] },
  },

  // ══════════════════════════════════════════════════════════════════════
  // Cross-workflow invoices — referenced by spend-analytics deferral batch
  // (lib/spend-analytics/cross-workflow-tie.ts HERO_DEFERRAL_BATCH_INVOICE_IDS)
  // and by the Westpoint maverick switch hero (HERO_MAVERICK_VENDOR_INVOICE_IDS).
  // Minimal Invoice shapes so the inbox row renders + the spend-analytics
  // badge wiring (deferred-to / in-maverick-batch) can resolve cleanly.
  // ══════════════════════════════════════════════════════════════════════

  // 5 deferral-batch invoices ──────────────────────────────────────────────
  {
    id: "inv-pacific-pl-2299",
    invoiceNumber: "PL-2299",
    vendorId: "vendor-pacific-logistics",
    amount: 182_000,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-12T07:14:00Z",
    issuedAt: "2026-04-27",
    dueAt: "2026-05-27",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.98,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Q2 freight services — PNW lanes", quantity: 1, unitPrice: 182_000, unitOfMeasure: "lot", lineTotal: 182_000 },
    ],
  },
  {
    id: "inv-sumitomo-sh-4471",
    invoiceNumber: "SH-4471",
    vendorId: "vendor-sumitomo-heavy",
    amount: 156_000,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-12T09:42:00Z",
    issuedAt: "2026-04-28",
    dueAt: "2026-05-28",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.97,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Heavy equipment rental — Plant B Q2", quantity: 1, unitPrice: 156_000, unitOfMeasure: "qtr", lineTotal: 156_000 },
    ],
  },
  {
    id: "inv-coastal-cp-9112",
    invoiceNumber: "CP-9112",
    vendorId: "vendor-coastal-print",
    amount: 148_000,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-13T11:08:00Z",
    issuedAt: "2026-04-29",
    dueAt: "2026-05-29",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.97,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Q2 print campaign — multi-channel", quantity: 1, unitPrice: 148_000, unitOfMeasure: "campaign", lineTotal: 148_000 },
    ],
  },
  {
    id: "inv-atlantic-ai-77103",
    invoiceNumber: "AI-77103",
    vendorId: "vendor-atlantic-001",
    amount: 46_000,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-13T07:14:00Z",
    issuedAt: "2026-05-11",
    dueAt: "2026-06-10",
    termsLabel: "2/10 net 30",
    status: "auto-posted",
    poRef: "PO-1455",
    poId: "po-1455",
    ocrConfidence: 1.0,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Industrial bearings — SKF 6209-2RS1", quantity: 400, unitPrice: 65, unitOfMeasure: "ea", lineTotal: 26_000 },
      { lineNumber: 2, description: "Drive belts — heavy-duty V-belt assortment", quantity: 100, unitPrice: 200, unitOfMeasure: "ea", lineTotal: 20_000 },
    ],
  },
  {
    id: "inv-westside-wl-3022",
    invoiceNumber: "WL-3022",
    vendorId: "vendor-westside-logistics",
    amount: 138_000,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-13T14:12:00Z",
    issuedAt: "2026-04-30",
    dueAt: "2026-05-30",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.96,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Q2 freight services — Midwest lanes", quantity: 1, unitPrice: 138_000, unitOfMeasure: "lot", lineTotal: 138_000 },
    ],
  },
  {
    id: "inv-northeast-ni-2107",
    invoiceNumber: "NI-2107",
    vendorId: "vendor-northeast-industrial-supply",
    amount: 126_000,
    currency: "USD",
    channel: "edi-810",
    receivedAt: "2026-05-13T15:48:00Z",
    issuedAt: "2026-04-30",
    dueAt: "2026-05-30",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.99,
    matchMode: "3way",
    lines: [
      { lineNumber: 1, description: "Industrial fasteners + tooling — Plant A Q2", quantity: 1, unitPrice: 126_000, unitOfMeasure: "lot", lineTotal: 126_000 },
    ],
  },

  // 4 Westpoint maverick-batch invoices ────────────────────────────────────
  {
    id: "inv-westpoint-industrial-wp-2204",
    invoiceNumber: "WP-2204",
    vendorId: "vendor-westpoint-industrial-tools",
    amount: 19_200,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-04-08T08:14:00Z",
    issuedAt: "2026-04-08",
    dueAt: "2026-05-08",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.97,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Industrial tools — fasteners + bits (PO-WP-2204)", quantity: 800, unitPrice: 24, unitOfMeasure: "ea", lineTotal: 19_200 },
    ],
  },
  {
    id: "inv-westpoint-industrial-wp-2207",
    invoiceNumber: "WP-2207",
    vendorId: "vendor-westpoint-industrial-tools",
    amount: 28_800,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-04-19T09:08:00Z",
    issuedAt: "2026-04-19",
    dueAt: "2026-05-19",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.97,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Industrial tools — fasteners + bits (PO-WP-2207)", quantity: 1200, unitPrice: 24, unitOfMeasure: "ea", lineTotal: 28_800 },
    ],
  },
  {
    id: "inv-westpoint-industrial-wp-2210",
    invoiceNumber: "WP-2210",
    vendorId: "vendor-westpoint-industrial-tools",
    amount: 14_400,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-01T11:22:00Z",
    issuedAt: "2026-05-01",
    dueAt: "2026-06-01",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.96,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Industrial tools — fasteners + bits (PO-WP-2210)", quantity: 600, unitPrice: 24, unitOfMeasure: "ea", lineTotal: 14_400 },
    ],
  },
  {
    id: "inv-westpoint-industrial-wp-2213",
    invoiceNumber: "WP-2213",
    vendorId: "vendor-westpoint-industrial-tools",
    amount: 21_600,
    currency: "USD",
    channel: "email",
    receivedAt: "2026-05-09T10:14:00Z",
    issuedAt: "2026-05-09",
    dueAt: "2026-06-09",
    termsLabel: "Net-30",
    status: "auto-posted",
    ocrConfidence: 0.97,
    matchMode: "2way",
    lines: [
      { lineNumber: 1, description: "Industrial tools — fasteners + bits (PO-WP-2213)", quantity: 900, unitPrice: 24, unitOfMeasure: "ea", lineTotal: 21_600 },
    ],
  },
]

// ════════════════════════════════════════════════════════════════════
// Final array — 51 invoices total
// ════════════════════════════════════════════════════════════════════

export const SEED_INVOICES: Invoice[] = [
  ...HERO_INVOICES,
  ...NAMED_EXCEPTIONS,
  ...AUTO_POSTED_TODAY,
  ...HISTORICAL_POSTED,
  ...FILLER,
]

const INVOICE_INDEX: Map<InvoiceId, Invoice> = new Map(
  SEED_INVOICES.map((inv) => [inv.id, inv])
)

export function getInvoice(id: InvoiceId): Invoice | undefined {
  return INVOICE_INDEX.get(id)
}
