// lib/neoflo-workspace/cognitive-ledger.ts
//
// The Cognitive Ledger — Neoflo's operational reasoning layer.
// While the GL records what happened financially, the Cognitive Ledger
// records WHY decisions were made + HOW exceptions were resolved + WHICH
// patterns recur. Neoflo captures these signals by:
//
//   1. Observing the user's actions inside the Neoflo tool itself
//      (classifier re-labels, override approvals, dunning tone choices,
//      GL re-codes, vendor-master tweaks).
//
//   2. Observing the user's actions outside the tool via the Neoflo
//      desktop agent — screen captures of NetSuite vendor card lookups,
//      SAP FBL3N pulls, Slack escalations, Excel exports, Coupa PO
//      changes, etc.
//
// Over time, recurring observations get synthesized into RULES that the
// finance organization can adopt — turning ephemeral judgment into
// persistent institutional memory.
//
// Data here is demo seed only. In production each observation would be
// generated by the agent runtime + a pattern-detection model.

import type { PersonaId } from "./personas"

// ─────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────

/**
 * Where Neoflo observed the action. "in-tool" = inside the Neoflo UI.
 * Everything else is captured by the desktop agent.
 */
export type ObservationSource =
  | "in-tool"
  | "netsuite"
  | "sap"
  | "oracle"
  | "coupa"
  | "concur"
  | "workday"
  | "slack"
  | "outlook"
  | "excel"

export const SOURCE_META: Record<
  ObservationSource,
  { label: string; logoBg: string; initials: string }
> = {
  "in-tool": {
    label: "Neoflo",
    logoBg: "bg-primary",
    initials: "Nf",
  },
  netsuite: { label: "NetSuite", logoBg: "bg-emerald-600", initials: "NS" },
  sap: { label: "SAP", logoBg: "bg-sky-700", initials: "SA" },
  oracle: { label: "Oracle", logoBg: "bg-rose-600", initials: "OR" },
  coupa: { label: "Coupa", logoBg: "bg-cyan-600", initials: "Co" },
  concur: { label: "Concur", logoBg: "bg-blue-600", initials: "Cn" },
  workday: { label: "Workday", logoBg: "bg-amber-600", initials: "Wd" },
  slack: { label: "Slack", logoBg: "bg-purple-600", initials: "Sl" },
  outlook: { label: "Outlook", logoBg: "bg-indigo-600", initials: "Ol" },
  excel: { label: "Excel", logoBg: "bg-green-700", initials: "Xl" },
}

export type ObservationKind =
  | "override"
  | "re-classify"
  | "manual-lookup"
  | "export"
  | "approval"
  | "external-action"
  | "tone-choice"
  | "data-fix"
  | "comm-pattern"
  | "escalation"

export const KIND_LABEL: Record<ObservationKind, string> = {
  override: "Override",
  "re-classify": "Re-classification",
  "manual-lookup": "Manual lookup",
  export: "Export to spreadsheet",
  approval: "Approval",
  "external-action": "External action",
  "tone-choice": "Tone choice",
  "data-fix": "Data fix",
  "comm-pattern": "Communication pattern",
  escalation: "Escalation",
}

export type Workflow =
  | "helpdesk"
  | "cash-app"
  | "invoice-processing"
  | "collections"
  | "spend-analytics"
  | "close"
  | "ar"
  | "ap"

/**
 * An individual observation Neoflo captured. The "raw event" — many of
 * these may eventually crystallise into a drafted rule, but most just
 * stay in the ledger as historical reasoning.
 *
 * When the observation is a *decision* (an override, a tone choice, an
 * exception approval), Neoflo also captures the human-supplied
 * rationale. That rationale is the raw material that rules synthesise
 * from — it's the bridge from individual judgment to institutional
 * memory.
 */
export interface Observation {
  id: string
  /** ISO timestamp (already-formatted) — demo seed */
  occurredAt: string
  /** Who took the action */
  actor: string
  /** Where Neoflo observed it */
  source: ObservationSource
  kind: ObservationKind
  workflow: Workflow
  /** Plain-English summary of what happened */
  headline: string
  /** Longer description with the data Neoflo captured */
  detail: string
  /** Personas this observation matters to */
  relevantPersonas: PersonaId[]
  /**
   * Human-supplied "why" for decision-class observations (overrides,
   * exception approvals, deliberate tone shifts). When present, this is
   * what distinguishes a judgment from a routine action and what gets
   * distilled into rule reasoning.
   */
  decisionRationale?: string
  /** The cognitive lift — what pattern this might create (1 line) */
  patternHint?: string
  /** If a rule was drafted/accepted from this observation, the rule id */
  rulePromoted?: string
  /** Recurrence count — "we've seen this N times" */
  recurrenceCount?: number
}

// ─────────────────────────────────────────────────────────────────────────
// Rules — drafted, active, or refused
// ─────────────────────────────────────────────────────────────────────────

export type RuleStatus = "drafted" | "active" | "refused"

/**
 * Multi-step approval. For example a rule that changes GL coding logic
 * might need AP Manager → Controller; one that touches segregation of
 * duties might need AP Manager → Controller → CFO.
 *
 * `currentStep` is the next pending approver (0 = first). When the
 * chain is complete the rule's status flips drafted → active.
 */
export interface ApprovalChain {
  approvers: PersonaId[]
  /** Index of the next pending approver. equals approvers.length when complete. */
  currentStep: number
  /** Per-step audit — who approved when, in chain order. */
  history?: Array<{ approver: PersonaId; at: string }>
}

/**
 * The visible synthesis Neoflo did when promoting observations into a
 * rule. Surfaced on every drafted rule so users see the working —
 * conditions, exceptions, and what would *not* trigger the rule. Same
 * spirit as showing an LLM's chain of thought, but structured.
 */
export interface SynthesisTrace {
  /** Observation ids the synthesis pulled from. */
  contributingObservationIds: string[]
  /** Concrete conditions the rule checks (machine-readable phrasing). */
  conditions: string[]
  /** Exception cases that opt out of the rule. */
  exceptions: string[]
  /** What would NOT trigger the rule — the rejection criteria. */
  rejectionCriteria: string[]
}

export interface Rule {
  id: string
  status: RuleStatus
  /** The synthesised rule, in plain English */
  statement: string
  /** Why Neoflo drafted it */
  reasoning: string
  /** Workflow it applies to */
  workflow: Workflow
  /** Multi-step approval chain — first approver is the owner, last is the activator. */
  approvalChain: ApprovalChain
  /** Observations that drove this rule */
  observationCount: number
  /** Visible synthesis trace — empty for refused rules that never got that far. */
  synthesis?: SynthesisTrace
  /** When the rule changed status (drafted, accepted, refused) */
  statusChangedAt: string
  /** For active rules: how many times applied in the last 30d */
  appliedCount?: number
  /** Optional impact callout */
  impact?: { value: string; label: string }
}

/** Convenience: the first persona in the approval chain is the rule owner. */
export function getRuleOwner(rule: Rule): PersonaId {
  return rule.approvalChain.approvers[0]
}

/**
 * A rule is "ready for SOP" when it's been stable enough that promoting
 * it into the policy doc makes sense. Criteria (demo heuristic):
 *   - status = active
 *   - applied ≥ 15 times in the last 30d (signals it's running reliably)
 *
 * In production we'd also require zero exception flags since promotion,
 * but the demo seed doesn't track per-rule exception events.
 */
export function isReadyForSOP(rule: Rule): boolean {
  return rule.status === "active" && (rule.appliedCount ?? 0) >= 15
}

/**
 * Cluster of observations that share a patternHint. The pattern is the
 * unit — actors and sources can vary. Used by the observation feed to
 * collapse density: 6 events sharing "Acme -B duplicate" naming
 * render as a single card rather than 6.
 */
export interface ObservationCluster {
  /** The patternHint string the cluster groups around. */
  patternHint: string
  /** Events in this cluster, sorted by recency (newest first). */
  events: Observation[]
  /** Unique actors across the cluster. */
  actors: string[]
  /** Unique sources across the cluster. */
  sources: ObservationSource[]
  /** The dominant workflow (most-frequent across events). */
  workflow: Workflow
  /** Oldest event timestamp in this cluster. */
  earliestAt: string
  /** Newest event timestamp in this cluster. */
  latestAt: string
  /** Rule id this pattern promoted into, if any (first non-null wins). */
  rulePromoted?: string
}

/**
 * Partition a list of observations into clusters + singletons.
 *
 * Rules (per design doc 2026-05-19-observation-clustering-design.md):
 * - Observations sharing the same patternHint group together
 * - Cross-actor, cross-source, cross-time clustering is allowed
 * - Observations with no patternHint, or whose group has only 1 event,
 *   are returned as singletons
 * - Within a cluster, events are sorted newest-first
 * - Clusters sorted by latest event recency; singletons by own
 *   timestamp recency
 */
export function clusterObservations(observations: Observation[]): {
  clusters: ObservationCluster[]
  singletons: Observation[]
} {
  const byPattern = new Map<string, Observation[]>()
  const noPattern: Observation[] = []
  for (const o of observations) {
    if (o.patternHint && o.patternHint.trim().length > 0) {
      const list = byPattern.get(o.patternHint) ?? []
      list.push(o)
      byPattern.set(o.patternHint, list)
    } else {
      noPattern.push(o)
    }
  }

  const clusters: ObservationCluster[] = []
  const singletons: Observation[] = [...noPattern]

  for (const [patternHint, events] of byPattern.entries()) {
    if (events.length < 2) {
      // Singleton cluster → returned in the singletons list per design
      singletons.push(events[0])
      continue
    }
    // Sort events newest-first within the cluster
    events.sort((a, b) =>
      a.occurredAt > b.occurredAt ? -1 : a.occurredAt < b.occurredAt ? 1 : 0,
    )
    const actors = Array.from(new Set(events.map((e) => e.actor)))
    const sources = Array.from(new Set(events.map((e) => e.source)))
    // Workflow = mode (most frequent). For ties, take the first event's.
    const workflowCounts = new Map<Workflow, number>()
    for (const e of events) {
      workflowCounts.set(e.workflow, (workflowCounts.get(e.workflow) ?? 0) + 1)
    }
    let workflow: Workflow = events[0].workflow
    let maxCount = 0
    for (const [w, c] of workflowCounts.entries()) {
      if (c > maxCount) {
        workflow = w
        maxCount = c
      }
    }
    const rulePromoted = events.find((e) => e.rulePromoted)?.rulePromoted
    clusters.push({
      patternHint,
      events,
      actors,
      sources,
      workflow,
      earliestAt: events[events.length - 1].occurredAt,
      latestAt: events[0].occurredAt,
      rulePromoted,
    })
  }

  // Sort clusters by recency of latest event (newest first)
  clusters.sort((a, b) =>
    a.latestAt > b.latestAt ? -1 : a.latestAt < b.latestAt ? 1 : 0,
  )
  // Sort singletons by recency
  singletons.sort((a, b) =>
    a.occurredAt > b.occurredAt ? -1 : a.occurredAt < b.occurredAt ? 1 : 0,
  )

  return { clusters, singletons }
}

/**
 * Maps a workflow to the default SOP id it would promote into. The
 * dialog pre-selects this primary SOP; users can still pick anything.
 */
export const WORKFLOW_DEFAULT_SOP_ID: Partial<Record<Workflow, string>> = {
  "invoice-processing": "src-ap-playbook",
  helpdesk: "src-ap-playbook",
  ap: "src-ap-playbook",
  collections: "src-ar-playbook",
  "cash-app": "src-ar-playbook",
  ar: "src-ar-playbook",
}

// ─────────────────────────────────────────────────────────────────────────
// SEED — observations
// ─────────────────────────────────────────────────────────────────────────

export const SEED_OBSERVATIONS: Observation[] = [
  // ─── In-tool observations ──────────────────────────────────────────────
  {
    id: "obs-001",
    occurredAt: "2026-05-18T09:42:11Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "re-classify",
    workflow: "invoice-processing",
    headline:
      'Re-classified 6 Acme Cleaning invoices from "Invoice status inquiry" to "Duplicate invoice"',
    detail:
      "Over the last 7 days, Lena overrode Neo's classifier on 6 Acme Cleaning invoices. In each case the invoice number ended with a -B suffix while the matching original ended with -A. The training signal has been added to the helpdesk classifier — accuracy lifts ~3pp.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint: "Vendor-specific naming pattern → auto-classify",
    rulePromoted: "rule-005",
    recurrenceCount: 6,
  },
  {
    id: "obs-002",
    occurredAt: "2026-05-17T15:08:22Z",
    actor: "Daniel Park",
    source: "in-tool",
    kind: "override",
    workflow: "invoice-processing",
    headline:
      "Overrode the $42,800 Acme duplicate flag with the rationale 'Plant B add-on confirmed by site mgr'",
    detail:
      "Daniel marked the duplicate as not-a-duplicate, citing a verbal confirmation from the Plant B site manager. Captured: the override, the user-supplied rationale, and the time-to-decision (2m 14s). Reasoning preserved for the next similar event.",
    relevantPersonas: ["controller", "ap-manager"],
    decisionRationale:
      "Plant B add-on services were confirmed by the site manager during a verbal call. The original INV-998123-A invoice covered only Plant A; -B is a separate scope. Override approved with site-manager confirm preserved.",
    patternHint:
      "Site-manager verbal confirms are valid duplicate-override evidence — formalise as workflow step",
    recurrenceCount: 3,
  },
  {
    id: "obs-003",
    occurredAt: "2026-05-17T11:30:08Z",
    actor: "Sasha Patel",
    source: "in-tool",
    kind: "tone-choice",
    workflow: "collections",
    headline:
      'Edited 14 dunning emails from "firm" to "empathetic" before sending, all for accounts <60 days overdue',
    detail:
      "Across the May 13–17 dunning batch, Sasha consistently downshifted Neo's suggested tone on under-60-day accounts. A/B uplift confirms it: 14% faster collection, 22% fewer dispute openings. The dunning playbook has been updated to default empathetic under 60d.",
    relevantPersonas: ["ar-manager"],
    patternHint: "Tone matrix default per aging bucket",
    rulePromoted: "rule-001",
    recurrenceCount: 14,
  },
  {
    id: "obs-004",
    occurredAt: "2026-05-16T14:22:55Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "comm-pattern",
    workflow: "helpdesk",
    headline:
      "Auto-CC'd controller@acmeco.com on every banking-change vendor reply this month (11/11)",
    detail:
      "Lena copies Daniel on every banking-change verification email. The pattern is 100% consistent over 11 messages. Rule has been drafted to surface the CC automatically when 'banking-change' classifier fires.",
    relevantPersonas: ["ap-manager"],
    patternHint: "Auto-CC controller on banking-change replies",
    rulePromoted: "rule-002",
    recurrenceCount: 11,
  },
  {
    id: "obs-005",
    occurredAt: "2026-05-16T10:14:38Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "re-classify",
    workflow: "invoice-processing",
    headline:
      'Re-coded 6 invoices to GL 62100 "Plant A maintenance" — Neo had proposed 62000',
    detail:
      "All 6 invoices were from Acme Cleaning and matched the description pattern 'cleaning Plant A'. Neo learned the vendor-specific mapping and the auto-coding rule set was extended; next 4 Acme invoices passed STP without re-code.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint:
      "Vendor + description → cost-center mapping (Acme + 'Plant A' = 62100)",
    rulePromoted: "rule-003",
    recurrenceCount: 6,
  },

  // ─── External observations (desktop agent) ─────────────────────────────
  {
    id: "obs-006",
    occurredAt: "2026-05-18T08:55:12Z",
    actor: "Sarah Chen",
    source: "netsuite",
    kind: "manual-lookup",
    workflow: "invoice-processing",
    headline:
      "Opened NetSuite Vendor Card → Tax Registration tab 17 times this week to check GST status",
    detail:
      "Average 6 seconds per lookup, all for Singapore vendors. Each lookup precedes a tax-coding decision in Neoflo. Drafted rule: surface vendor GST status inline on the invoice review surface so the manual cross-system trip disappears.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint:
      "Surface NetSuite GST status inline → eliminate 17 lookups/wk",
    rulePromoted: "rule-004",
    recurrenceCount: 17,
  },
  {
    id: "obs-007",
    occurredAt: "2026-05-17T16:38:01Z",
    actor: "Marcus Bauer",
    source: "sap",
    kind: "manual-lookup",
    workflow: "close",
    headline:
      "Pulled SAP FBL3N (GL Line Items) 8 times to investigate accrual variances",
    detail:
      "Each pull was filtered to cost-center range PLANT-A–PLANT-C, period P5/2026. The variance investigation that follows happens in Neoflo's close board. Drafted rule: pre-fetch the FBL3N filtered view on Day-3 close and surface inline.",
    relevantPersonas: ["controller", "treasurer"],
    patternHint: "Pre-fetch SAP FBL3N data for accrual periods",
    recurrenceCount: 8,
  },
  {
    id: "obs-008",
    occurredAt: "2026-05-17T13:21:44Z",
    actor: "Sasha Patel",
    source: "slack",
    kind: "escalation",
    workflow: "collections",
    headline:
      "Escalated Pacific Distribution to controller via DM at 95-day silence (3rd time this quarter)",
    detail:
      "Sasha messages Daniel on Slack when AR aging crosses 90 days with 3+ ignored outreach attempts. Pattern is consistent: 95-day silence + 3 ignored = DM. Drafted rule: surface the escalation suggestion inside Neoflo at the same trigger so the DM is pre-drafted.",
    relevantPersonas: ["ar-manager", "controller"],
    patternHint:
      "Auto-suggest controller escalation at 90d aging + 3 ignored outreach",
    recurrenceCount: 3,
  },
  {
    id: "obs-009",
    occurredAt: "2026-05-17T11:02:18Z",
    actor: "Daniel Park",
    source: "excel",
    kind: "export",
    workflow: "close",
    headline:
      "Exported invoice processing data to Excel for inter-co eliminations 6× this close",
    detail:
      "Daniel pulls invoice data into Excel to manually compute parent-sub inter-co eliminations. The same VLOOKUP pattern is used each time. Drafted rule: build the inter-co elimination view inline on the close board — eliminates the export entirely.",
    relevantPersonas: ["controller"],
    patternHint: "Inline inter-co elimination view on close board",
    recurrenceCount: 6,
  },
  {
    id: "obs-010",
    occurredAt: "2026-05-16T15:48:30Z",
    actor: "Marcus Bauer",
    source: "outlook",
    kind: "comm-pattern",
    workflow: "ap",
    headline:
      "Forwarded JPM wire fee statements to Daniel + CFO with subject 'Tier benchmarking' 4 times in 30 days",
    detail:
      "Pattern of monthly forwards consistently tagged to tier-benchmarking analysis. Each forward triggers a manual fee benchmark Marcus runs separately. Drafted rule: auto-run bank fee benchmark when JPM statements ingest and surface the comparison inline.",
    relevantPersonas: ["treasurer", "cfo"],
    patternHint: "Auto-run JPM fee tier benchmark on statement ingest",
    recurrenceCount: 4,
  },
  {
    id: "obs-011",
    occurredAt: "2026-05-16T10:08:00Z",
    actor: "Lena Müller",
    source: "coupa",
    kind: "external-action",
    workflow: "invoice-processing",
    headline:
      "Updated PO-1431 line price in Coupa to match invoice (price variance reconciliation)",
    detail:
      "Variance was within MSA tolerance. Pattern: when MSA tolerance allows it, AP updates the PO to match instead of disputing. Drafted rule: auto-update PO line within MSA tolerance, captured in the audit trail.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint: "Auto-update PO within MSA price tolerance",
    recurrenceCount: 5,
  },
  {
    id: "obs-012",
    occurredAt: "2026-05-15T16:30:54Z",
    actor: "Sasha Patel",
    source: "in-tool",
    kind: "data-fix",
    workflow: "collections",
    headline:
      "Anchored 12 promised-payment dates to Thursday after rescheduling Mon/Fri picks",
    detail:
      "Sasha consistently re-picks promised-pay dates from Mon/Fri to Thursday. Network data shows Thursday promises slip 3× less than Monday. Rule now applies automatically when user picks Mon/Fri.",
    relevantPersonas: ["ar-manager"],
    patternHint: "Anchor promises to Thursday by default",
    rulePromoted: "rule-006",
    recurrenceCount: 12,
  },
  {
    id: "obs-013",
    occurredAt: "2026-05-15T14:12:09Z",
    actor: "Daniel Park",
    source: "workday",
    kind: "manual-lookup",
    workflow: "close",
    headline:
      "Opened Workday approval delegation 3 times to check OOO coverage during close",
    detail:
      "Pattern: each close kickoff Daniel checks Workday for the week's out-of-office to know who covers approvals. Drafted rule: pull Workday OOO into the approval matrix automatically + surface coverage on close kickoff.",
    relevantPersonas: ["controller"],
    patternHint: "Sync Workday OOO into approval matrix during close",
    recurrenceCount: 3,
  },
  {
    id: "obs-014",
    occurredAt: "2026-05-15T09:30:21Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "data-fix",
    workflow: "invoice-processing",
    headline:
      "Merged 2 vendor master records (Acme Cleaning + Acme Cleaning Services Inc) with shared EIN",
    detail:
      "Lena confirmed the EIN match and merged the records. The merge unblocked the duplicate detector to see $312K of split spend as a single vendor. Drafted rule: auto-flag any vendor pair with matching EIN at onboarding instead of waiting for a duplicate flag.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint: "Block creation of vendor with EIN that already exists",
    recurrenceCount: 1,
  },
  {
    id: "obs-015",
    occurredAt: "2026-05-14T17:18:33Z",
    actor: "Priya Mehta",
    source: "excel",
    kind: "export",
    workflow: "spend-analytics",
    headline:
      "Exported maverick spend report to Excel for board pre-read — added 2 sparkline charts manually",
    detail:
      "Pattern of weekly export with the same chart additions. Drafted rule: include sparkline charts in the maverick spend dashboard inline so the Excel manipulation is no longer needed.",
    relevantPersonas: ["cfo", "cpo"],
    patternHint: "Add sparklines to maverick spend dashboard",
    recurrenceCount: 4,
  },
  {
    id: "obs-016",
    occurredAt: "2026-05-14T14:48:09Z",
    actor: "Sarah Chen",
    source: "in-tool",
    kind: "approval",
    workflow: "invoice-processing",
    headline:
      "Approved 3 invoices over the $25K Controller threshold while Lena was OOO",
    detail:
      "Approval matrix correctly routed to Sarah as Lena's delegate. Captured: the delegation chain + the decision time (avg 14s per invoice — well within SLA).",
    relevantPersonas: ["controller"],
    patternHint: "Delegation chain working as intended — no rule needed",
    recurrenceCount: 3,
  },
  {
    id: "obs-017",
    occurredAt: "2026-05-14T11:05:42Z",
    actor: "Olivia Brooks",
    source: "concur",
    kind: "external-action",
    workflow: "spend-analytics",
    headline:
      "Re-categorised 8 Concur expenses from 'Travel' to 'Marketing — events'",
    detail:
      "All 8 expenses were Q2 sponsorship-related but Concur defaulted to Travel. Drafted rule: route Concur expenses with vendor name matching sponsorship keywords to Marketing > Events category.",
    relevantPersonas: ["cpo", "controller"],
    patternHint: "Vendor-name-based Concur category routing",
    recurrenceCount: 8,
  },
  {
    id: "obs-018",
    occurredAt: "2026-05-13T16:11:55Z",
    actor: "Marcus Bauer",
    source: "outlook",
    kind: "manual-lookup",
    workflow: "ar",
    headline:
      "Drafted email to Pacific Distribution at 9:47am customer-local time (Singapore)",
    detail:
      "Pattern: Marcus has sent every Singapore-customer outreach between 9:30 and 10:30am customer-local for 6 weeks. Network data confirms 2.3x reply rate vs other times. Auto-scheduling now applies this rule for all geos.",
    relevantPersonas: ["ar-manager"],
    patternHint: "Auto-schedule customer outreach for 9-11am local time",
    rulePromoted: "rule-007",
    recurrenceCount: 19,
  },
  {
    id: "obs-019",
    occurredAt: "2026-05-13T10:25:20Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "tone-choice",
    workflow: "helpdesk",
    headline:
      "Edited 4 supplier replies from Neo's draft tone — added apology language on payment delays",
    detail:
      "When the inquiry concerned a payment Neo had already missed, Lena consistently softened the tone and led with acknowledgement. Tone-classifier updated; future payment-delay replies follow her pattern.",
    relevantPersonas: ["ap-manager"],
    patternHint: "Apologetic lead on missed-payment supplier replies",
    recurrenceCount: 4,
  },
  {
    id: "obs-020",
    occurredAt: "2026-05-12T15:43:18Z",
    actor: "Daniel Park",
    source: "in-tool",
    kind: "override",
    workflow: "invoice-processing",
    headline:
      'Approved a $48K Atlantic Industrial invoice with PO variance citing "freight clause §4.2 of MSA"',
    detail:
      "Daniel's rationale referenced the specific freight-clause language from the MSA. The clause has been added to the auto-coding rule set — next 3 Atlantic Industrial freight invoices passed STP without manual review.",
    relevantPersonas: ["controller", "ap-manager"],
    decisionRationale:
      "MSA §4.2 allows ±3% freight variance without re-negotiation. Invoice variance of +2.4% is inside tolerance, so the override is contractually authorized — captured the specific clause citation for the audit trail and future synthesis.",
    patternHint:
      "MSA freight clause → auto-acceptance of price variance within that scope",
    rulePromoted: "rule-008",
    recurrenceCount: 3,
  },
  {
    id: "obs-021",
    occurredAt: "2026-05-12T13:12:36Z",
    actor: "Sasha Patel",
    source: "slack",
    kind: "comm-pattern",
    workflow: "collections",
    headline:
      'Posted "broken promise" status in #collections-daily for 4 customers this week',
    detail:
      "Pattern: Sasha posts a daily standup to #collections-daily. The team consumes it for prioritisation. Drafted rule: auto-post the broken-promise digest to Slack at 9am, eliminating Sasha's manual compose step.",
    relevantPersonas: ["ar-manager"],
    patternHint: "Auto-post broken-promise digest to #collections-daily at 9am",
    recurrenceCount: 4,
  },
  {
    id: "obs-022",
    occurredAt: "2026-05-12T09:38:01Z",
    actor: "Daniel Park",
    source: "netsuite",
    kind: "data-fix",
    workflow: "close",
    headline:
      "Modified inter-co elimination journal entry in NetSuite — corrected the wrong sub-account from 21010 to 21090",
    detail:
      "Pattern: when Daniel inserts inter-co JEs, he uses 21090 consistently for the parent-sub elimination but the default suggestion is 21010. Drafted rule: update the inter-co JE default to 21090 in the close board.",
    relevantPersonas: ["controller"],
    patternHint: "Update inter-co JE default sub-account 21010 → 21090",
    recurrenceCount: 2,
  },
  {
    id: "obs-023",
    occurredAt: "2026-05-11T16:50:12Z",
    actor: "Olivia Brooks",
    source: "in-tool",
    kind: "approval",
    workflow: "spend-analytics",
    headline:
      "Approved Northeast switch from Westpoint (maverick) on the 'Switched to Northeast' badge",
    detail:
      "Olivia's approval was the first time the cross-workflow maverick-to-switch flow fired end-to-end. Captured: the cross-workflow trace, the contracting decision, and the $10K projected save.",
    relevantPersonas: ["cpo", "ap-manager"],
    patternHint:
      "Maverick spend > preferred MSA threshold → auto-switch with notification",
    recurrenceCount: 1,
  },
  {
    id: "obs-024",
    occurredAt: "2026-05-11T11:20:48Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "data-fix",
    workflow: "invoice-processing",
    headline:
      "Edited tax treatment on 5 Sumitomo invoices from 'Standard GST' to 'Reverse charge'",
    detail:
      "All 5 invoices were cross-border Singapore→Japan. Pattern is consistent across the last 12 weeks. The Singapore GST rule pack has been updated for Sumitomo specifically — IRAS rejection rate for this vendor dropped to 0%.",
    relevantPersonas: ["ap-manager", "controller"],
    decisionRationale:
      "Singapore IRAS treats Sumitomo Japan→Singapore cross-border invoices as reverse-charge under §14 of the GST Act. Standard-GST default would invite an IRAS rejection. Edit applied with the regulation citation preserved.",
    patternHint: "Sumitomo cross-border → reverse charge GST default",
    rulePromoted: "rule-009",
    recurrenceCount: 5,
  },
  {
    id: "obs-025",
    occurredAt: "2026-05-10T17:02:30Z",
    actor: "Priya Mehta",
    source: "excel",
    kind: "manual-lookup",
    workflow: "close",
    headline:
      "Built a margin-by-shipment lookup in Excel for Q2 board prep (4 hours)",
    detail:
      "Priya manually joined freight log + COGS + sales invoices to find which shipments drove the Q2 margin slip. Drafted rule: build the margin-by-shipment view as a standing report so Q3 prep takes 4 minutes instead of 4 hours.",
    relevantPersonas: ["cfo", "controller"],
    patternHint: "Standing margin-by-shipment report tied to freight log",
    recurrenceCount: 1,
  },

  // ─── Sibling observations — create clusters so the feed compresses ────
  // Each shares a patternHint with an earlier observation, so the cluster
  // view groups them. Without these, every observation would be a
  // singleton in the design's cluster taxonomy.

  // Cluster: "Auto-CC controller on banking-change replies"
  {
    id: "obs-026",
    occurredAt: "2026-05-18T11:15:42Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "comm-pattern",
    workflow: "helpdesk",
    headline:
      "CC'd controller@ on Pacific Distribution banking-change verification reply",
    detail:
      "12th consecutive banking-change reply with controller@ in CC. Pattern stable across 6+ weeks.",
    relevantPersonas: ["ap-manager"],
    patternHint: "Auto-CC controller on banking-change replies",
    recurrenceCount: 1,
  },
  {
    id: "obs-027",
    occurredAt: "2026-05-17T09:48:19Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "comm-pattern",
    workflow: "helpdesk",
    headline:
      "CC'd controller@ on Westpoint Manufacturing banking-change reply",
    detail:
      "Banking-change inquiry resolved with controller@ CC'd. Same pattern as the prior 11 messages.",
    relevantPersonas: ["ap-manager"],
    patternHint: "Auto-CC controller on banking-change replies",
    recurrenceCount: 1,
  },

  // Cluster: "Vendor + description → cost-center mapping"
  {
    id: "obs-028",
    occurredAt: "2026-05-17T13:12:08Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "re-classify",
    workflow: "invoice-processing",
    headline:
      'Re-coded Acme Cleaning invoice ACL-1188 from GL 62000 → 62100 (Plant A)',
    detail:
      "Description matched the 'Plant A' substring rule we observed last week. Posting once the rule is fully active.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint:
      "Vendor + description → cost-center mapping (Acme + 'Plant A' = 62100)",
    recurrenceCount: 1,
  },
  {
    id: "obs-029",
    occurredAt: "2026-05-16T15:55:17Z",
    actor: "Sarah Chen",
    source: "in-tool",
    kind: "re-classify",
    workflow: "invoice-processing",
    headline:
      'Re-coded Acme Cleaning invoice ACL-1187 from GL 62000 → 62100 (Plant B)',
    detail:
      "Same vendor + description pattern, applied to Plant B. Sarah is covering for Lena this week.",
    relevantPersonas: ["ap-manager"],
    patternHint:
      "Vendor + description → cost-center mapping (Acme + 'Plant A' = 62100)",
    recurrenceCount: 1,
  },

  // Cluster: "Sumitomo cross-border → reverse charge GST default"
  {
    id: "obs-030",
    occurredAt: "2026-05-18T08:32:00Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "data-fix",
    workflow: "invoice-processing",
    headline:
      "Edited tax treatment on Sumitomo invoice SH-4475 — Standard GST → Reverse charge",
    detail:
      "6th Sumitomo cross-border edit. The IRAS §14 citation is consistent across all of them.",
    relevantPersonas: ["ap-manager", "controller"],
    decisionRationale:
      "IRAS §14 — Japan→Singapore cross-border services attract reverse charge regardless of vendor-side invoicing.",
    patternHint: "Sumitomo cross-border → reverse charge GST default",
    recurrenceCount: 1,
  },
  {
    id: "obs-031",
    occurredAt: "2026-05-15T10:24:50Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "data-fix",
    workflow: "invoice-processing",
    headline:
      "Edited tax treatment on Sumitomo invoice SH-4474 — Standard GST → Reverse charge",
    detail:
      "Same vendor + jurisdiction. Drafted rule waiting on Controller sign-off — once active, this edit disappears.",
    relevantPersonas: ["ap-manager"],
    patternHint: "Sumitomo cross-border → reverse charge GST default",
    recurrenceCount: 1,
  },

  // Cluster: "Anchor promises to Thursday by default"
  {
    id: "obs-032",
    occurredAt: "2026-05-18T14:08:33Z",
    actor: "Sasha Patel",
    source: "in-tool",
    kind: "data-fix",
    workflow: "collections",
    headline:
      "Rescheduled Atlantic Logistics promised pay date from Mon May 25 → Thu May 28",
    detail:
      "Rule already running — caught the Monday pick and proposed Thursday. Sasha accepted.",
    relevantPersonas: ["ar-manager"],
    patternHint: "Anchor promises to Thursday by default",
    recurrenceCount: 1,
  },
  {
    id: "obs-033",
    occurredAt: "2026-05-17T11:42:15Z",
    actor: "Sasha Patel",
    source: "in-tool",
    kind: "data-fix",
    workflow: "collections",
    headline:
      "Rescheduled Pacific Distribution promised pay date Fri May 22 → Thu May 21",
    detail:
      "Same anchor rule. Promise day-of-week consistency improves slip rate per network data.",
    relevantPersonas: ["ar-manager"],
    patternHint: "Anchor promises to Thursday by default",
    recurrenceCount: 1,
  },

  // Cluster: "Vendor-specific naming pattern → auto-classify" (the Acme -B story)
  {
    id: "obs-034",
    occurredAt: "2026-05-18T16:21:09Z",
    actor: "Lena Müller",
    source: "in-tool",
    kind: "re-classify",
    workflow: "invoice-processing",
    headline:
      "Re-classified INV-998502-B from 'Invoice status' → 'Duplicate invoice'",
    detail:
      "Suffix '-B' against a matching '-A' invoice in our paid history. Same Acme pattern.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint: "Vendor-specific naming pattern → auto-classify",
    recurrenceCount: 1,
  },
  {
    id: "obs-035",
    occurredAt: "2026-05-15T12:48:27Z",
    actor: "Daniel Park",
    source: "in-tool",
    kind: "re-classify",
    workflow: "invoice-processing",
    headline:
      "Re-classified INV-998477-B from 'Invoice status' → 'Duplicate invoice'",
    detail:
      "Daniel caught it during the Friday batch review. Same Acme naming pattern continues.",
    relevantPersonas: ["ap-manager", "controller"],
    patternHint: "Vendor-specific naming pattern → auto-classify",
    recurrenceCount: 1,
  },
]

// ─────────────────────────────────────────────────────────────────────────
// SEED — rules
// ─────────────────────────────────────────────────────────────────────────

// Chain shorthand — first entry is owner, last is final approver.
function chain(...approvers: PersonaId[]): ApprovalChain {
  return { approvers, currentStep: 0, history: [] }
}
function completedChain(
  approvers: PersonaId[],
  history: Array<{ approver: PersonaId; at: string }>,
): ApprovalChain {
  return { approvers, currentStep: approvers.length, history }
}

export const SEED_RULES: Rule[] = [
  // ─── Active rules (chain complete) ─────────────────────────────────────
  {
    id: "rule-001",
    status: "active",
    statement: "Use empathetic dunning tone for AR aging under 60 days",
    reasoning:
      "Sasha downshifted 14 of 14 dunning emails from 'firm' to 'empathetic' for accounts <60 days overdue. Cross-network A/B confirmed: 14% faster collection, 22% fewer dispute openings.",
    workflow: "collections",
    approvalChain: completedChain(
      ["ar-manager", "controller"],
      [
        { approver: "ar-manager", at: "2026-05-17T11:30:08Z" },
        { approver: "controller", at: "2026-05-17T11:42:00Z" },
      ],
    ),
    observationCount: 14,
    synthesis: {
      contributingObservationIds: ["obs-003"],
      conditions: [
        "Workflow = collections",
        "Customer aging bucket < 60 days",
        "Outbound dunning message draft",
      ],
      exceptions: [
        "Customer has open dispute (preserve firm tone)",
        "Customer is on credit hold (use formal tone)",
      ],
      rejectionCriteria: [
        "Aging ≥ 60 days uses the existing firm-tone playbook",
        "Internal-team comms unaffected (this is customer-facing only)",
      ],
    },
    statusChangedAt: "2026-05-17T11:42:00Z",
    appliedCount: 28,
    impact: { value: "+14%", label: "collection speed" },
  },
  {
    id: "rule-002",
    status: "active",
    statement:
      "Auto-CC controller@acmeco.com on all banking-change verification replies",
    reasoning:
      "Lena CC'd controller@ on 11 of 11 banking-change replies this month. Pattern is 100% consistent across 6+ weeks.",
    workflow: "helpdesk",
    approvalChain: completedChain(
      ["ap-manager", "controller"],
      [
        { approver: "ap-manager", at: "2026-05-16T14:25:00Z" },
        { approver: "controller", at: "2026-05-16T15:01:00Z" },
      ],
    ),
    observationCount: 11,
    synthesis: {
      contributingObservationIds: ["obs-004"],
      conditions: [
        "Outbound reply on a banking-change inquiry",
        "Reply tagged with classifier label 'Banking change request'",
      ],
      exceptions: [
        "User explicitly removes the CC before send",
        "Customer-side compliance team already in the To: line",
      ],
      rejectionCriteria: [
        "Other inquiry types are not auto-CC'd",
        "Internal team replies are unaffected",
      ],
    },
    statusChangedAt: "2026-05-16T15:01:00Z",
    appliedCount: 9,
  },
  {
    id: "rule-003",
    status: "active",
    statement:
      "Acme Cleaning invoices with line description matching 'Plant A' / 'Plant B' → cost center PLANT-A or PLANT-B + GL 62100",
    reasoning:
      "Lena re-coded 6 Acme Cleaning invoices in 7 days to extract the cost center from the line description. STP rate for this vendor jumped from 60% to 100%.",
    workflow: "invoice-processing",
    approvalChain: completedChain(
      ["ap-manager", "controller"],
      [
        { approver: "ap-manager", at: "2026-05-16T10:14:38Z" },
        { approver: "controller", at: "2026-05-16T10:34:00Z" },
      ],
    ),
    observationCount: 6,
    synthesis: {
      contributingObservationIds: ["obs-005"],
      conditions: [
        "vendor = 'Acme Cleaning Services'",
        "Line description contains 'Plant A' or 'Plant B'",
      ],
      exceptions: [
        "Description mentions 'Plant C' or unnamed location — drops to manual coding",
        "Multiple plants on a single line — split into per-plant journals",
      ],
      rejectionCriteria: [
        "Other vendors are unaffected (vendor-specific rule)",
        "Acme Cleaning invoices without plant mentions still route through normal coding",
      ],
    },
    statusChangedAt: "2026-05-16T10:34:00Z",
    appliedCount: 4,
    impact: { value: "+40pp", label: "vendor STP" },
  },
  {
    id: "rule-005",
    status: "active",
    statement:
      "Re-classify invoices ending '-B' from vendors with a matching '-A' invoice already paid → flag as duplicate candidate",
    reasoning:
      "Lena re-classified 6 Acme Cleaning -B invoices to 'Duplicate' this week. The vendor's naming pattern is consistent enough to act on at classification time, before the duplicate detector runs.",
    workflow: "invoice-processing",
    approvalChain: completedChain(
      ["ap-manager", "controller"],
      [
        { approver: "ap-manager", at: "2026-05-18T09:42:11Z" },
        { approver: "controller", at: "2026-05-18T10:05:00Z" },
      ],
    ),
    observationCount: 6,
    synthesis: {
      contributingObservationIds: ["obs-001"],
      conditions: [
        "Invoice number matches pattern `*-B`",
        "Same vendor has a `*-A` invoice paid within 90 days",
        "Total amounts match within ±1%",
      ],
      exceptions: [
        "Vendor master notes flag pattern as intentional (e.g. plant-split invoices)",
        "PO reference differs between A and B",
      ],
      rejectionCriteria: [
        "Different vendor with -B suffix doesn't apply",
        "If amounts differ > 1%, fall back to the normal duplicate detector",
      ],
    },
    statusChangedAt: "2026-05-18T10:05:00Z",
    appliedCount: 2,
    impact: { value: "$84K", label: "additional dup prevention" },
  },
  {
    id: "rule-006",
    status: "active",
    statement:
      "When user picks Mon/Fri for a promised-payment date, re-anchor the suggestion to nearest Thursday",
    reasoning:
      "Sasha rescheduled 12 promise dates from Mon/Fri to Thursday. Network data confirms Thursday promises slip 3× less than Monday.",
    workflow: "collections",
    approvalChain: completedChain(
      ["ar-manager"],
      [{ approver: "ar-manager", at: "2026-05-15T16:30:54Z" }],
    ),
    observationCount: 12,
    synthesis: {
      contributingObservationIds: ["obs-012"],
      conditions: [
        "User selects Monday or Friday for promise-to-pay date",
        "No customer-supplied date override on file",
      ],
      exceptions: [
        "Customer-requested date in writing (email or portal)",
        "Customer is on a fixed-Friday payment cycle",
      ],
      rejectionCriteria: [
        "Tuesday / Wednesday / Thursday picks stand unchanged",
        "Weekend picks were never offered to begin with",
      ],
    },
    statusChangedAt: "2026-05-15T16:30:54Z",
    appliedCount: 18,
    impact: { value: "-3x", label: "promise slip rate" },
  },
  {
    id: "rule-007",
    status: "active",
    statement:
      "Schedule customer outreach for 9–11am customer-local time by default",
    reasoning:
      "Marcus + Sasha consistently shifted outreach to morning local-time windows for 6+ weeks. Network data confirms 2.3× reply rate.",
    workflow: "collections",
    approvalChain: completedChain(
      ["ar-manager"],
      [{ approver: "ar-manager", at: "2026-05-13T16:11:55Z" }],
    ),
    observationCount: 19,
    synthesis: {
      contributingObservationIds: ["obs-018"],
      conditions: [
        "Customer outreach email or call",
        "Customer geo on file (so local time is calculable)",
      ],
      exceptions: [
        "Customer is on no-contact window (incident, dispute escalation)",
        "Time-sensitive collections action (broken-promise day-of)",
      ],
      rejectionCriteria: [
        "Internal-team notifications are unaffected",
        "Customers without geo data fall back to AR-team local time",
      ],
    },
    statusChangedAt: "2026-05-13T16:11:55Z",
    appliedCount: 34,
    impact: { value: "+2.3x", label: "reply rate" },
  },

  // ─── Drafted rules — chains in progress ────────────────────────────────
  {
    id: "rule-004",
    status: "drafted",
    statement:
      "Surface NetSuite vendor GST status inline on the invoice review surface (eliminates per-invoice tab switching)",
    reasoning:
      "Sarah opened the NetSuite Vendor Card → Tax Registration tab 17 times this week to check GST status before tax-coding decisions. Each lookup averages 6 seconds; total ~5 min/wk reclaimed per user if surfaced inline. Pattern across 3 users.",
    workflow: "invoice-processing",
    approvalChain: chain("ap-manager", "controller"),
    observationCount: 17,
    synthesis: {
      contributingObservationIds: ["obs-006"],
      conditions: [
        "Invoice review surface loads for a vendor with non-null tax registration",
        "Vendor jurisdiction ∈ {SG, IN, AU, EU, GB, JP}",
      ],
      exceptions: [
        "Tax registration in NetSuite > 90 days stale — show with 'verify in NetSuite' link",
      ],
      rejectionCriteria: [
        "US vendors don't get a GST chip (no GST regime)",
        "Inactive vendors don't trigger the lookup",
      ],
    },
    statusChangedAt: "2026-05-18T08:55:12Z",
    impact: { value: "~5 min/wk", label: "per user" },
  },
  {
    id: "rule-008",
    status: "drafted",
    statement:
      "Auto-accept price variance on Atlantic Industrial freight invoices when within MSA §4.2 tolerance (±3%)",
    reasoning:
      "Daniel approved 3 Atlantic Industrial freight variances citing the same MSA clause across the last 6 weeks. The clause is unambiguous and machine-readable.",
    workflow: "invoice-processing",
    approvalChain: chain("controller", "cfo"),
    observationCount: 3,
    synthesis: {
      contributingObservationIds: ["obs-020"],
      conditions: [
        "vendor = 'Atlantic Industrial'",
        "Line classification = 'freight'",
        "Variance vs PO ≤ 3% (per MSA §4.2)",
      ],
      exceptions: [
        "MSA amendment changes the tolerance — rule auto-refreshes from MSA library",
        "Variance accumulates across the quarter > $50K — escalates regardless",
      ],
      rejectionCriteria: [
        "Other vendors: variance still goes to Daniel for review",
        "Non-freight Atlantic Industrial lines: no auto-accept",
      ],
    },
    statusChangedAt: "2026-05-12T15:43:18Z",
    impact: { value: "~12 invoices/Q", label: "auto-pass" },
  },
  {
    id: "rule-009",
    status: "drafted",
    statement:
      "Default Sumitomo cross-border invoices to 'Reverse charge' GST treatment",
    reasoning:
      "Lena edited the GST treatment on 5 Sumitomo invoices in 12 weeks. The vendor + jurisdiction pair is unambiguous. Applying the rule eliminates the manual edit and drops IRAS rejection rate for this vendor to 0%.",
    workflow: "invoice-processing",
    approvalChain: chain("ap-manager", "controller"),
    observationCount: 5,
    synthesis: {
      contributingObservationIds: ["obs-024"],
      conditions: [
        "vendor = 'Sumitomo Heavy'",
        "Bill-to entity is Singapore",
        "Vendor jurisdiction = Japan",
      ],
      exceptions: [
        "Vendor invoice explicitly tags 'Standard GST'",
        "IRAS issues a Sumitomo-specific notice — rule pauses",
      ],
      rejectionCriteria: [
        "Other Japan→Singapore vendors evaluated independently",
        "Domestic Sumitomo invoices (Japan→Japan) unaffected",
      ],
    },
    statusChangedAt: "2026-05-11T11:20:48Z",
    impact: { value: "0%", label: "IRAS rejection (was 4.7%)" },
  },
  {
    id: "rule-010",
    status: "drafted",
    statement:
      "Pre-fetch SAP FBL3N filtered view (cost-centers PLANT-A through PLANT-C) on Day-3 of close",
    reasoning:
      "Marcus pulled FBL3N 8 times during the May close with the same filters. The view is deterministic and the close window is predictable.",
    workflow: "close",
    approvalChain: chain("controller", "treasurer"),
    observationCount: 8,
    synthesis: {
      contributingObservationIds: ["obs-007"],
      conditions: [
        "Close calendar shows Day-3",
        "User has previously pulled FBL3N during the same close phase",
      ],
      exceptions: [
        "Close is in 'hot' mode (variance >2σ) — surface live data instead of cached",
        "User opts out via close-board settings",
      ],
      rejectionCriteria: [
        "Other days of close don't trigger the pre-fetch",
        "Different SAP transactions are not auto-pre-fetched without an observed pattern",
      ],
    },
    statusChangedAt: "2026-05-17T16:38:01Z",
    impact: { value: "~30 min", label: "per close" },
  },
  {
    id: "rule-011",
    status: "drafted",
    statement:
      "Block creation of vendor master records when the EIN already exists",
    reasoning:
      "Lena merged 2 Acme Cleaning records this week; the duplicate had been created in 2022 despite a shared EIN. Adding an onboarding-time guard would prevent $312K of split-spend visibility loss in the future.",
    workflow: "invoice-processing",
    approvalChain: chain("ap-manager", "controller", "cfo"),
    observationCount: 1,
    synthesis: {
      contributingObservationIds: ["obs-014"],
      conditions: [
        "New vendor onboarding form submitted",
        "EIN already exists on an active vendor record",
      ],
      exceptions: [
        "Vendor master notes explicitly authorise a separate record (e.g. legal entity split)",
      ],
      rejectionCriteria: [
        "Vendors with the same name but different EINs are not blocked",
        "International tax IDs are evaluated against their own uniqueness rule",
      ],
    },
    statusChangedAt: "2026-05-15T09:30:21Z",
    impact: { value: "Hard guard", label: "EIN uniqueness" },
  },
  {
    id: "rule-012",
    status: "drafted",
    statement:
      "Auto-post the broken-promise digest to #collections-daily at 9am EST",
    reasoning:
      "Sasha posts a manual broken-promise digest 4× per week. The content is deterministic from the collections store. Eliminate her ~10 min/day compose step by auto-posting at 9am.",
    workflow: "collections",
    approvalChain: chain("ar-manager"),
    observationCount: 4,
    synthesis: {
      contributingObservationIds: ["obs-021"],
      conditions: [
        "9:00am EST trigger",
        "Slack channel #collections-daily reachable",
        "Broken-promise count > 0 from yesterday",
      ],
      exceptions: [
        "Channel temporarily archived",
        "Bank holiday — defer to next business day",
      ],
      rejectionCriteria: [
        "Other channels are not auto-posted",
        "Zero broken promises → no post (avoid noise)",
      ],
    },
    statusChangedAt: "2026-05-12T13:12:36Z",
    impact: { value: "~50 min/wk", label: "reclaimed" },
  },
  {
    id: "rule-013",
    status: "drafted",
    statement:
      "Sync Workday OOO into the approval matrix automatically — surface coverage chain on close kickoff",
    reasoning:
      "Daniel opens Workday delegation 3× per close to look up coverage. Pulling the data inline removes the trip + ensures the approval matrix is always current.",
    workflow: "close",
    approvalChain: chain("controller", "cfo"),
    observationCount: 3,
    synthesis: {
      contributingObservationIds: ["obs-013"],
      conditions: [
        "Close kickoff banner is being rendered",
        "Workday OOO data is < 24h old",
      ],
      exceptions: [
        "Workday API is unreachable — fall back to last-known coverage",
      ],
      rejectionCriteria: [
        "Non-close approvals continue to use the static approval matrix",
        "Personal OOO is shown only to those above in the chain — not to peers",
      ],
    },
    statusChangedAt: "2026-05-15T14:12:09Z",
  },

  // ─── Refused (kept for transparency) ───────────────────────────────────
  {
    id: "rule-rf-1",
    status: "refused",
    statement:
      "Auto-confirm duplicate when same vendor + same amount + within 30 days",
    reasoning:
      "Daniel refused this rule on May 12 — too aggressive given the $42,800 Acme override case where the second invoice was legitimate. Kept as a candidate for tighter conditions (e.g. + same line items verbatim).",
    workflow: "invoice-processing",
    approvalChain: completedChain(
      ["ap-manager", "controller"],
      [{ approver: "ap-manager", at: "2026-05-12T14:00:00Z" }],
    ),
    observationCount: 2,
    statusChangedAt: "2026-05-12T16:00:00Z",
  },
]

// ─────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────

export function filterObservationsByPersona(
  observations: Observation[],
  persona: PersonaId,
): Observation[] {
  if (persona === "all") return observations
  return observations.filter(
    (o) =>
      o.relevantPersonas.includes("all") ||
      o.relevantPersonas.includes(persona),
  )
}

/**
 * A persona sees a rule if they're anywhere in its approval chain —
 * not just the owner. That way a Controller sees rules the AP Manager
 * proposed that need their sign-off next.
 */
export function filterRulesByPersona(
  rules: Rule[],
  persona: PersonaId,
): Rule[] {
  if (persona === "all") return rules
  return rules.filter((r) => r.approvalChain.approvers.includes(persona))
}

export function getRule(id: string): Rule | undefined {
  return SEED_RULES.find((r) => r.id === id)
}

export function getObservation(id: string): Observation | undefined {
  return SEED_OBSERVATIONS.find((o) => o.id === id)
}

export function ledgerStats() {
  return {
    observationsTotal: SEED_OBSERVATIONS.length,
    activeRules: SEED_RULES.filter((r) => r.status === "active").length,
    draftedRules: SEED_RULES.filter((r) => r.status === "drafted").length,
    refusedRules: SEED_RULES.filter((r) => r.status === "refused").length,
    sourcesObserved: Array.from(
      new Set(SEED_OBSERVATIONS.map((o) => o.source)),
    ).length,
  }
}
