// lib/workspace/seed-feed.ts
//
// Ranked "everything that needs you today" feed shown on
// /workspace/all-work. Pure data — references icons by string key
// (PhosphorIconKey) so this file remains JSON-serializable.

import type { PhosphorIconKey } from "@/lib/neoflo-os/workspace/workflow-icons"

export type FeedItem = {
  /** Stable id, used for completion tracking & analytics */
  id: string
  icon: PhosphorIconKey
  /** Tailwind class for icon background */
  iconBg: string
  /** Tailwind class for icon text color */
  iconText: string
  /** Workflow label, e.g. "Helpdesk · banking change" */
  workflow: string
  title: string
  meta: string
  urgency:
    | "HIGH RISK"
    | "Needs approval"
    | "Blocking close"
    | "Ready to send"
    | "FYI"
  urgencyTone: "rose" | "amber" | "primary" | "emerald"
  /** Persona shown on the right, e.g. "AP Director" */
  persona: string
  cta: string
  ctaTone: "primary" | "neutral"
  href: string
  /** Filterable categories */
  domain: "P2P" | "O2C" | "R2R"
  tags: ("high-risk" | "needs-approval" | "quick-win")[]
}

export const SEED_FEED: FeedItem[] = [
  {
    id: "pacific-banking-change",
    icon: "ShieldWarning",
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    workflow: "Helpdesk · banking change",
    title: "Pacific Distribution wants to change banking details",
    meta: "Domain mismatch flagged · pre-built verification protocol attached · 3 min",
    urgency: "HIGH RISK",
    urgencyTone: "rose",
    persona: "AP Director",
    cta: "Review",
    ctaTone: "primary",
    href: "/workspace/helpdesk/inbox/bank-change-pacific",
    domain: "P2P",
    tags: ["high-risk", "quick-win"],
  },
  {
    id: "cash-app-short-pays",
    icon: "HandCoins",
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    workflow: "Cash application",
    title: "Acme Industrial $97.5K · 1:many match needs your eyes",
    meta: "Neo matched 1:3 with FREIGHT_DISCOUNT explanation · open the puzzle",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AR Manager",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/cash-app/match/pay-3392-2026",
    domain: "O2C",
    tags: ["needs-approval"],
  },
  {
    id: "close-day-3-blocked",
    icon: "Calendar",
    iconBg: "bg-cyan-100",
    iconText: "text-cyan-700",
    workflow: "Close · day 3",
    title: "Bank rec blocked: JPMorgan feed missed yesterday",
    meta: "2 of 12 day-3 tasks blocked · Lena owns payroll",
    urgency: "Blocking close",
    urgencyTone: "amber",
    persona: "Controller",
    cta: "Unblock",
    ctaTone: "neutral",
    href: "/workspace/close",
    domain: "R2R",
    tags: [],
  },
  {
    id: "collections-monday-batch",
    icon: "PaperPlaneTilt",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Collections",
    title: "Drafted 18 collections emails for Monday-morning sequence",
    meta: "Awaiting batch approval · top 5 customers in 90+ aging",
    urgency: "Ready to send",
    urgencyTone: "primary",
    persona: "AR Manager",
    cta: "Approve",
    ctaTone: "primary",
    href: "/workspace/collections",
    domain: "O2C",
    tags: ["needs-approval"],
  },
  {
    id: "collections-atlantic-dispute-resolved",
    icon: "CheckCircle",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Collections · dispute",
    title: "Resolved $4,200 dispute from Atlantic Industrial — credit memo $63 drafted",
    meta: "PO + POD matched · 1.5% short ship validated · awaiting your sign-off",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "AR Manager",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/collections/dispute/dispute-atlantic-9912",
    domain: "O2C",
    tags: [],
  },
  {
    id: "collections-pacific-account-hold",
    icon: "ShieldWarning",
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    workflow: "Collections · escalation",
    title: "Recommend account hold on Pacific Distribution — 95 days, $120K, unresponsive",
    meta: "3 ignored emails · last 6mo orders $340K · CFO sign-off required",
    urgency: "HIGH RISK",
    urgencyTone: "rose",
    persona: "AR Manager",
    cta: "Review",
    ctaTone: "primary",
    href: "/workspace/collections/customer/cust-pacific-distribution",
    domain: "O2C",
    tags: ["high-risk", "needs-approval"],
  },
  {
    id: "invoice-processing-posted-24h",
    icon: "FileMagnifyingGlass",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Invoice processing",
    title: "Posted 24 invoices straight-through last 24h",
    meta: "Auto-matched 3-way · journal posted · audit trail attached",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "AP Manager",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/invoice-processing/inbox",
    domain: "P2P",
    tags: [],
  },
  {
    id: "invoice-processing-duplicate-acme",
    icon: "ShieldWarning",
    iconBg: "bg-rose-100",
    iconText: "text-rose-700",
    workflow: "Invoice processing · duplicate",
    title: "Caught likely duplicate from Acme Cleaning — $42,800 saved if confirmed",
    meta: "INV-998123-B identical to invoice paid Apr 18 · stop payment before next run",
    urgency: "HIGH RISK",
    urgencyTone: "rose",
    persona: "AP Manager",
    cta: "Review",
    ctaTone: "primary",
    href: "/workspace/invoice-processing/match/inv-998123-b",
    domain: "P2P",
    tags: ["high-risk", "needs-approval"],
  },
  {
    id: "invoice-processing-gst-singapore",
    icon: "FileMagnifyingGlass",
    iconBg: "bg-cyan-100",
    iconText: "text-cyan-700",
    workflow: "Invoice processing · GST coding",
    title: "Coded Singapore Stationery GST input tax credit at 96% confidence",
    meta: "SG-GST 9% · mapped to 2310-InputTax · ready for your second look",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AP Manager",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/invoice-processing/match/inv-singapore-stationery-may",
    domain: "P2P",
    tags: ["needs-approval"],
  },
  {
    id: "spend-westpoint-maverick",
    icon: "ChartLineUp",
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    workflow: "Spend analytics · maverick",
    title: "Maverick spend caught · Westpoint Industrial $84K · switch to Northeast saves $12K annualized",
    meta: "Off-MSA Q2 spend · preferred-vendor MSA available · procurement notification drafted",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "CFO / CPO",
    cta: "Review",
    ctaTone: "primary",
    href: "/workspace/spend-analytics/maverick/maverick-westpoint-q2-2026",
    domain: "P2P",
    tags: ["needs-approval"],
  },
  {
    id: "spend-working-capital-opportunity",
    icon: "ChartLineUp",
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    workflow: "Spend analytics · working capital",
    title: "$1.8M working capital trapped · 12 vendors absorb DPO 38→42 stretch",
    meta: "Per-vendor elasticity reasoning attached · no single-source vendors affected",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "CFO",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/spend-analytics",
    domain: "P2P",
    tags: [],
  },
  {
    id: "spend-deferral-opportunity",
    icon: "ChartLineUp",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Spend analytics · cash flow",
    title: "$890K deferral opportunity · 6 invoices shift 4-7 days within terms",
    meta: "Aligns AP outflows with May 30 customer receipt forecast · no late fees, no supplier risk",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "CFO",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/spend-analytics/cashflow",
    domain: "P2P",
    tags: ["needs-approval"],
  },
  {
    id: "billing-q2-milestone-batch",
    icon: "Receipt",
    iconBg: "bg-sky-100",
    iconText: "text-sky-700",
    workflow: "Billing",
    title: "42 milestone invoices ready to dispatch",
    meta: "Q2 SaaS contracts · all priced & tax-coded · awaiting your sign-off",
    urgency: "Ready to send",
    urgencyTone: "primary",
    persona: "AR Manager",
    cta: "Send",
    ctaTone: "primary",
    href: "/workspace/billing",
    domain: "O2C",
    tags: ["needs-approval"],
  },
  {
    id: "kpi-may-flux-margin",
    icon: "ChartBar",
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    workflow: "KPI reporting",
    title: "May flux: gross margin -2.1pp vs prior month",
    meta: "Auto-explanation drafted · driver: 3 specific shipments",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "FP&A",
    cta: "Read",
    ctaTone: "neutral",
    href: "/workspace/kpi-reporting",
    domain: "R2R",
    tags: [],
  },

  // ============ Helpdesk extras ============
  {
    id: "helpdesk-sumitomo-remittance",
    icon: "ChatCircleText",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Helpdesk · remittance",
    title: "Sumitomo Heavy asks remittance for PO-1432",
    meta: "Auto-drafted reply with attached remittance · ready to send",
    urgency: "Ready to send",
    urgencyTone: "primary",
    persona: "AP Team",
    cta: "Approve",
    ctaTone: "primary",
    href: "/workspace/helpdesk",
    domain: "P2P",
    tags: ["needs-approval", "quick-win"],
  },
  {
    id: "helpdesk-coastal-payment-status",
    icon: "ChatCircleText",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Helpdesk · payment status",
    title: "Coastal Print payment confirmation request",
    meta: "Tipalti record located · 1-click reply drafted",
    urgency: "Ready to send",
    urgencyTone: "primary",
    persona: "AP Team",
    cta: "Send",
    ctaTone: "primary",
    href: "/workspace/helpdesk",
    domain: "P2P",
    tags: ["quick-win"],
  },
  {
    id: "helpdesk-westside-statement",
    icon: "ChatCircleText",
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    workflow: "Helpdesk · statement reconciliation",
    title: "Westside Logistics June statement — 3 line variance",
    meta: "$1,820 variance vs our AP ledger · Neo proposes credit memo for missing invoice",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AP Team",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/helpdesk",
    domain: "P2P",
    tags: ["needs-approval"],
  },

  // ============ Invoice processing extras ============
  {
    id: "invoice-processing-grn-pending",
    icon: "FileMagnifyingGlass",
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    workflow: "Invoice processing · GRN pending",
    title: "8 invoices pending GRN match — total $186K",
    meta: "Receiving team auto-pinged · GRNs typically post within 24h",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AP Manager",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/invoice-processing/exceptions",
    domain: "P2P",
    tags: ["needs-approval"],
  },
  {
    id: "invoice-processing-tax-cross-border",
    icon: "FileMagnifyingGlass",
    iconBg: "bg-cyan-100",
    iconText: "text-cyan-700",
    workflow: "Invoice processing · cross-border tax",
    title: "Tax review batch: 3 cross-border invoices ($24K total)",
    meta: "GB VAT, EU VAT, SG GST · all input-tax-credit eligible per Neo",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AP Manager",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/invoice-processing/exceptions",
    domain: "P2P",
    tags: ["needs-approval"],
  },
  {
    id: "invoice-processing-auto-posted-47",
    icon: "FileMagnifyingGlass",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Invoice processing · auto-posted",
    title: "Auto-posted 47 PO-matched invoices last 24h",
    meta: "All 3-way · cumulative AP $1.2M · audit trail attached",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "AP Manager",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/invoice-processing/inbox",
    domain: "P2P",
    tags: [],
  },

  // ============ Cash app extras ============
  {
    id: "cash-app-unapplied-aging",
    icon: "HandCoins",
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    workflow: "Cash application · unapplied",
    title: "5 unapplied payments aging >7 days · $128K",
    meta: "All missing remittance · Neo drafted customer follow-ups",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AR Manager",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/cash-app/unapplied",
    domain: "O2C",
    tags: ["needs-approval"],
  },
  {
    id: "cash-app-overnight-posted",
    icon: "HandCoins",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Cash application · overnight",
    title: "Posted $890K to invoices overnight (1:1 + 1:many)",
    meta: "62 payments matched · 0 short-pays · STP rate 94%",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "AR Manager",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/cash-app",
    domain: "O2C",
    tags: [],
  },

  // ============ Collections extras ============
  {
    id: "collections-promise-expires-today",
    icon: "Calendar",
    iconBg: "bg-amber-100",
    iconText: "text-amber-700",
    workflow: "Collections · promise tracking",
    title: "3 promise-to-pay commitments expire today · $94K",
    meta: "Tone-shifted follow-ups drafted if any breach by EOD",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "AR Manager",
    cta: "Open",
    ctaTone: "neutral",
    href: "/workspace/collections/worklist",
    domain: "O2C",
    tags: ["needs-approval"],
  },
  {
    id: "collections-dso-trend",
    icon: "ChartLineUp",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-700",
    workflow: "Collections · DSO trend",
    title: "Quarterly DSO down 4 days vs last quarter (45 → 41)",
    meta: "Driven by faster dispute resolution · trending toward 38 target",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "Controller",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/collections",
    domain: "O2C",
    tags: [],
  },

  // ============ Close extras ============
  {
    id: "close-day-3-progress",
    icon: "Calendar",
    iconBg: "bg-cyan-100",
    iconText: "text-cyan-700",
    workflow: "Close · day 3",
    title: "Day-3 close: 8 of 12 tasks complete on track",
    meta: "Bank rec + payroll still blocked · everything else green",
    urgency: "FYI",
    urgencyTone: "emerald",
    persona: "Controller",
    cta: "View",
    ctaTone: "neutral",
    href: "/workspace/close",
    domain: "R2R",
    tags: [],
  },

  // ============ Spend analytics extras ============
  {
    id: "spend-q2-concentration-alert",
    icon: "ChartLineUp",
    iconBg: "bg-violet-100",
    iconText: "text-violet-700",
    workflow: "Spend analytics · concentration",
    title: "Q2 vendor concentration: top 5 vendors = 62% of spend",
    meta: "Above 50% threshold · CFO flagged for procurement diversification review",
    urgency: "Needs approval",
    urgencyTone: "amber",
    persona: "CFO / CPO",
    cta: "Review",
    ctaTone: "neutral",
    href: "/workspace/spend-analytics",
    domain: "P2P",
    tags: ["needs-approval"],
  },
]
