// 80 fictional mid-market vendors for the spend-analytics demo.
//
// Source of truth: docs/handoff/spend-analytics/04-data-model.md § "seed-vendors.ts"
// + the Bundle B brief in docs/plans/2026-05-16-spend-analytics-phase-1-implementation.md.
//
// Composition:
//   - 7 hero vendors (Westpoint, Northeast, Acme, Pacific Logistics, Sumitomo,
//     Coastal Print, Westside Logistics) — IDs verbatim, surfaces depend on them.
//   - 6 additional preferred-category vendors (Cornerstone Legal, Summit IT,
//     Blackford Facilities, Keystone Office, Mariner Travel, Vanguard Misc).
//   - 12 vendors flagged "absorbs DPO stretch" — standard/long-tail, late-paying,
//     consumed by the $1.8M DPO opportunity in Bundle C.
//   - 6 vendors flagged "DO NOT stretch" — strategic, on/early-paying.
//   - ~49 baseline vendors with realistic spend distribution across all
//     10 SpendCategory values, totalling ~$120M YTD across the cohort.
//
// Total YTD spend across the 80 vendors approximates $120M.

import type { SpendCategory, Vendor, VendorId } from "./types"

export const SEED_VENDORS: Vendor[] = [
  // ── Hero vendors (verbatim IDs) ──────────────────────────────────────────

  // Maverick hero — off-MSA industrial tools.
  {
    id: "vendor-westpoint-industrial-tools",
    name: "Westpoint Industrial Tools",
    category: "industrial-tools",
    ytdSpend: 3_400_000,
    ttmSpend: 4_100_000,
    concentrationShare: 0.028,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 2d late · 0 disputes · standard elasticity",
    industry: "Industrial supplies",
  },
  // Preferred alternative for industrial-tools.
  {
    id: "vendor-northeast-industrial-supply",
    name: "Northeast Industrial Supply",
    category: "industrial-tools",
    ytdSpend: 8_400_000,
    ttmSpend: 10_200_000,
    concentrationShare: 0.070,
    msaActive: true,
    msaId: "msa-northeast-industrial-tools",
    isPreferredForCategory: true,
    elasticityTier: "strategic",
    averageDaysToPay: 28,
    paymentTermsDays: 30,
    paymentHistorySummary: "On terms · 0 disputes · strategic vendor",
    strategicNotes: "Preferred vendor for industrial-tools per active MSA; do not stretch.",
    industry: "Industrial supplies",
  },
  // Concentration hero — 18% of total spend, single-source.
  {
    id: "vendor-acme-industrial-supplies",
    name: "Acme Industrial Supplies",
    category: "industrial-tools",
    ytdSpend: 21_600_000,
    ttmSpend: 26_400_000,
    concentrationShare: 0.180,
    msaActive: true,
    msaId: "msa-acme-industrial",
    isPreferredForCategory: false,
    elasticityTier: "strategic",
    averageDaysToPay: 24,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 6d early · 0 disputes · strategic single-source",
    strategicNotes:
      "Single-source for 12 critical SKUs · do not stretch DPO · concentration risk above benchmark",
    singleSourceRisk: true,
    industry: "Industrial supplies",
  },
  // Pacific Logistics — top-2 concentration, late-payer, DPO-elastic.
  {
    id: "vendor-pacific-logistics",
    name: "Pacific Logistics",
    category: "logistics",
    ytdSpend: 9_600_000,
    ttmSpend: 11_400_000,
    concentrationShare: 0.080,
    msaActive: true,
    msaId: "msa-pacific-logistics",
    isPreferredForCategory: true,
    elasticityTier: "standard",
    averageDaysToPay: 36,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 6d late on average · 0 disputes · strong elasticity",
    industry: "Logistics",
  },
  // Sumitomo Heavy — equipment-rental sub of industrial-tools.
  {
    id: "vendor-sumitomo-heavy",
    name: "Sumitomo Heavy",
    category: "industrial-tools",
    ytdSpend: 6_000_000,
    ttmSpend: 7_300_000,
    concentrationShare: 0.050,
    msaActive: true,
    msaId: "msa-sumitomo-heavy",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 38,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 8d late · 1 dispute (resolved) · strong elasticity",
    industry: "Equipment rental",
  },
  // Coastal Print — preferred marketing vendor.
  {
    id: "vendor-coastal-print",
    name: "Coastal Print",
    category: "marketing",
    ytdSpend: 7_200_000,
    ttmSpend: 8_700_000,
    concentrationShare: 0.060,
    msaActive: true,
    msaId: "msa-coastal-print",
    isPreferredForCategory: true,
    elasticityTier: "standard",
    averageDaysToPay: 34,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 4d late · 0 disputes · medium elasticity",
    industry: "Marketing & print",
  },
  // Westside Logistics — second logistics vendor, DPO-elastic.
  {
    id: "vendor-westside-logistics",
    name: "Westside Logistics",
    category: "logistics",
    ytdSpend: 4_800_000,
    ttmSpend: 5_900_000,
    concentrationShare: 0.040,
    msaActive: true,
    msaId: "msa-westside-logistics",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 35,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 5d late · 0 disputes · strong elasticity",
    industry: "Logistics",
  },

  // ── Additional preferred-category vendors (PREFERRED_VENDOR_MAP) ────────

  {
    id: "vendor-cornerstone-legal",
    name: "Cornerstone Legal",
    category: "legal",
    ytdSpend: 2_400_000,
    ttmSpend: 2_900_000,
    concentrationShare: 0.020,
    msaActive: true,
    msaId: "msa-cornerstone-legal",
    isPreferredForCategory: true,
    elasticityTier: "strategic",
    averageDaysToPay: 26,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 4d early · 0 disputes · strategic counsel",
    strategicNotes: "Outside counsel of record; do not stretch.",
    industry: "Legal services",
  },
  {
    id: "vendor-summit-it",
    name: "Summit IT",
    category: "IT",
    ytdSpend: 5_400_000,
    ttmSpend: 6_500_000,
    concentrationShare: 0.045,
    msaActive: true,
    msaId: "msa-summit-it",
    isPreferredForCategory: true,
    elasticityTier: "strategic",
    averageDaysToPay: 27,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 3d early · 0 disputes · strategic SaaS partner",
    strategicNotes: "Anchor SaaS contract for ERP middleware; do not stretch.",
    industry: "IT services",
  },
  {
    id: "vendor-blackford-facilities",
    name: "Blackford Facilities",
    category: "facilities",
    ytdSpend: 3_600_000,
    ttmSpend: 4_300_000,
    concentrationShare: 0.030,
    msaActive: true,
    msaId: "msa-blackford-facilities",
    isPreferredForCategory: true,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    paymentHistorySummary: "On terms · 0 disputes · medium elasticity",
    industry: "Facilities management",
  },
  {
    id: "vendor-keystone-office",
    name: "Keystone Office",
    category: "office-supplies",
    ytdSpend: 960_000,
    ttmSpend: 1_150_000,
    concentrationShare: 0.008,
    msaActive: true,
    msaId: "msa-keystone-office",
    isPreferredForCategory: true,
    elasticityTier: "long-tail",
    averageDaysToPay: 35,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 5d late · 0 disputes · strong elasticity",
    industry: "Office supplies",
  },
  {
    id: "vendor-mariner-travel",
    name: "Mariner Travel",
    category: "travel",
    ytdSpend: 1_440_000,
    ttmSpend: 1_700_000,
    concentrationShare: 0.012,
    msaActive: true,
    msaId: "msa-mariner-travel",
    isPreferredForCategory: true,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    paymentHistorySummary: "On terms · 0 disputes · standard elasticity",
    industry: "Travel management",
  },
  {
    id: "vendor-vanguard-misc",
    name: "Vanguard Misc",
    category: "other",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: true,
    msaId: "msa-vanguard-misc",
    isPreferredForCategory: true,
    elasticityTier: "long-tail",
    averageDaysToPay: 33,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 3d late · 0 disputes · long-tail fallback",
    industry: "General services",
  },

  // ── 12 "absorbs DPO stretch" vendors (Bundle C consumes these) ──────────
  // Each: standard or long-tail tier, averageDaysToPay > paymentTermsDays,
  //       no strategicNotes, no singleSourceRisk.
  // Combined contribution to DPO opportunity: ~$1.8M (per vendor $50K-$300K).

  {
    id: "vendor-pinewood-supplies",
    name: "Pinewood Supplies",
    category: "facilities",
    ytdSpend: 1_800_000,
    ttmSpend: 2_150_000,
    concentrationShare: 0.015,
    msaActive: true,
    msaId: "msa-pinewood-supplies",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 34,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 4d late · 0 disputes · strong elasticity",
    industry: "Industrial supplies",
  },
  {
    id: "vendor-skyharbor-logistics",
    name: "Skyharbor Logistics",
    category: "logistics",
    ytdSpend: 2_400_000,
    ttmSpend: 2_900_000,
    concentrationShare: 0.020,
    msaActive: true,
    msaId: "msa-skyharbor-logistics",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 37,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 7d late · 0 disputes · strong elasticity",
    industry: "Logistics",
  },
  {
    id: "vendor-harmony-tools",
    name: "Harmony Tools",
    category: "industrial-tools",
    ytdSpend: 1_200_000,
    ttmSpend: 1_440_000,
    concentrationShare: 0.010,
    msaActive: true,
    msaId: "msa-harmony-tools",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 36,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 6d late · 0 disputes · strong elasticity",
    industry: "Industrial supplies",
  },
  {
    id: "vendor-evergreen-print",
    name: "Evergreen Print",
    category: "marketing",
    ytdSpend: 720_000,
    ttmSpend: 870_000,
    concentrationShare: 0.006,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 38,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 8d late · 0 disputes · strong elasticity",
    industry: "Marketing & print",
  },
  {
    id: "vendor-fairhaven-it",
    name: "Fairhaven IT",
    category: "IT",
    ytdSpend: 1_500_000,
    ttmSpend: 1_800_000,
    concentrationShare: 0.0125,
    msaActive: true,
    msaId: "msa-fairhaven-it",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 35,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 5d late · 0 disputes · strong elasticity",
    industry: "IT services",
  },
  {
    id: "vendor-trailhead-office",
    name: "Trailhead Office",
    category: "office-supplies",
    ytdSpend: 600_000,
    ttmSpend: 720_000,
    concentrationShare: 0.005,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 36,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 6d late · 0 disputes · strong elasticity",
    industry: "Office supplies",
  },
  {
    id: "vendor-northstar-marketing",
    name: "Northstar Marketing",
    category: "marketing",
    ytdSpend: 900_000,
    ttmSpend: 1_080_000,
    concentrationShare: 0.0075,
    msaActive: true,
    msaId: "msa-northstar-marketing",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 34,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 4d late · 0 disputes · medium elasticity",
    industry: "Marketing & print",
  },
  {
    id: "vendor-brightline-travel",
    name: "Brightline Travel",
    category: "travel",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 37,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 7d late · 0 disputes · strong elasticity",
    industry: "Travel management",
  },
  {
    id: "vendor-cascadia-facilities",
    name: "Cascadia Facilities",
    category: "facilities",
    ytdSpend: 1_080_000,
    ttmSpend: 1_290_000,
    concentrationShare: 0.009,
    msaActive: true,
    msaId: "msa-cascadia-facilities",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 34,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 4d late · 0 disputes · strong elasticity",
    industry: "Facilities management",
  },
  {
    id: "vendor-bayside-supplies",
    name: "Bayside Supplies",
    category: "office-supplies",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 40,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 10d late · 0 disputes · strong elasticity",
    industry: "Office supplies",
  },
  {
    id: "vendor-redwood-it",
    name: "Redwood IT",
    category: "IT",
    ytdSpend: 1_200_000,
    ttmSpend: 1_450_000,
    concentrationShare: 0.010,
    msaActive: true,
    msaId: "msa-redwood-it",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 35,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 5d late · 0 disputes · strong elasticity",
    industry: "IT services",
  },
  {
    id: "vendor-meridian-print",
    name: "Meridian Print",
    category: "marketing",
    ytdSpend: 540_000,
    ttmSpend: 650_000,
    concentrationShare: 0.0045,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 36,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 6d late · 0 disputes · medium elasticity",
    industry: "Marketing & print",
  },

  // ── 6 "DO NOT stretch" vendors (strategic / singleSource / pays on time) ─

  {
    id: "vendor-helios-research",
    name: "Helios Research",
    category: "professional-services",
    ytdSpend: 2_100_000,
    ttmSpend: 2_550_000,
    concentrationShare: 0.0175,
    msaActive: true,
    msaId: "msa-helios-research",
    isPreferredForCategory: true,
    elasticityTier: "strategic",
    averageDaysToPay: 28,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 2d early · 0 disputes · strategic research partner",
    strategicNotes:
      "Anchor R&D partner with multi-year roadmap dependency · do not stretch",
    industry: "Professional services",
  },
  {
    id: "vendor-atlas-engineering",
    name: "Atlas Engineering",
    category: "professional-services",
    ytdSpend: 1_800_000,
    ttmSpend: 2_160_000,
    concentrationShare: 0.015,
    msaActive: true,
    msaId: "msa-atlas-engineering",
    isPreferredForCategory: false,
    elasticityTier: "strategic",
    averageDaysToPay: 26,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 4d early · 0 disputes · strategic engineering counterparty",
    strategicNotes: "Single-source for plant-A retrofit engineering · do not stretch",
    singleSourceRisk: true,
    industry: "Professional services",
  },
  {
    id: "vendor-orion-power-systems",
    name: "Orion Power Systems",
    category: "industrial-tools",
    ytdSpend: 2_700_000,
    ttmSpend: 3_240_000,
    concentrationShare: 0.0225,
    msaActive: true,
    msaId: "msa-orion-power-systems",
    isPreferredForCategory: false,
    elasticityTier: "strategic",
    averageDaysToPay: 27,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 3d early · 0 disputes · strategic equipment vendor",
    strategicNotes:
      "Sole supplier of certified power modules for Plant B · do not stretch",
    singleSourceRisk: true,
    industry: "Power systems",
  },
  {
    id: "vendor-quantum-cloud",
    name: "Quantum Cloud",
    category: "IT",
    ytdSpend: 2_400_000,
    ttmSpend: 2_880_000,
    concentrationShare: 0.020,
    msaActive: true,
    msaId: "msa-quantum-cloud",
    isPreferredForCategory: false,
    elasticityTier: "strategic",
    averageDaysToPay: 25,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 5d early · 0 disputes · strategic cloud partner",
    strategicNotes:
      "Anchor cloud spend; auto-pay enabled to preserve credit rebate tier · do not stretch",
    industry: "Cloud infrastructure",
  },
  {
    id: "vendor-pinnacle-insurance",
    name: "Pinnacle Insurance",
    category: "professional-services",
    ytdSpend: 1_800_000,
    ttmSpend: 2_160_000,
    concentrationShare: 0.015,
    msaActive: true,
    msaId: "msa-pinnacle-insurance",
    isPreferredForCategory: false,
    elasticityTier: "strategic",
    averageDaysToPay: 28,
    paymentTermsDays: 30,
    paymentHistorySummary: "Pays 2d early · 0 disputes · strategic policy underwriter",
    strategicNotes:
      "Carrier of record for property + general liability · auto-pay · do not stretch",
    industry: "Insurance",
  },
  {
    id: "vendor-vertex-audit",
    name: "Vertex Audit",
    category: "professional-services",
    ytdSpend: 1_200_000,
    ttmSpend: 1_440_000,
    concentrationShare: 0.010,
    msaActive: true,
    msaId: "msa-vertex-audit",
    isPreferredForCategory: false,
    elasticityTier: "strategic",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    paymentHistorySummary: "On terms · 0 disputes · strategic audit firm",
    strategicNotes: "External auditor of record · do not stretch",
    industry: "Professional services",
  },

  // ── ~49 baseline vendors with realistic distribution ────────────────────
  // Spread across all 10 SpendCategory values.
  // Aggregate baseline YTD spend brings the total cohort to ~$120M.

  // ── industrial-tools baseline ─────────────────────────────────────────
  {
    id: "vendor-baseline-it-001-ironclad-bolts",
    name: "Ironclad Bolts",
    category: "industrial-tools",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-ironclad-bolts",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Industrial supplies",
  },
  {
    id: "vendor-baseline-it-002-titan-machining",
    name: "Titan Machining",
    category: "industrial-tools",
    ytdSpend: 840_000,
    ttmSpend: 1_010_000,
    concentrationShare: 0.007,
    msaActive: true,
    msaId: "msa-titan-machining",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Industrial supplies",
  },
  {
    id: "vendor-baseline-it-003-cobalt-fasteners",
    name: "Cobalt Fasteners",
    category: "industrial-tools",
    ytdSpend: 720_000,
    ttmSpend: 870_000,
    concentrationShare: 0.006,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Industrial supplies",
  },
  {
    id: "vendor-baseline-it-004-summit-abrasives",
    name: "Summit Abrasives",
    category: "industrial-tools",
    ytdSpend: 600_000,
    ttmSpend: 720_000,
    concentrationShare: 0.005,
    msaActive: true,
    msaId: "msa-summit-abrasives",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Industrial supplies",
  },
  {
    id: "vendor-baseline-it-005-stratton-welding",
    name: "Stratton Welding Co.",
    category: "industrial-tools",
    ytdSpend: 540_000,
    ttmSpend: 650_000,
    concentrationShare: 0.0045,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 33,
    paymentTermsDays: 30,
    industry: "Industrial supplies",
  },

  // ── professional-services baseline ────────────────────────────────────
  {
    id: "vendor-baseline-ps-001-mercer-strategy",
    name: "Mercer Strategy",
    category: "professional-services",
    ytdSpend: 1_000_000,
    ttmSpend: 1_200_000,
    concentrationShare: 0.00833,
    msaActive: true,
    msaId: "msa-mercer-strategy",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Consulting",
  },
  {
    id: "vendor-baseline-ps-002-bridgepoint-tax",
    name: "Bridgepoint Tax Advisors",
    category: "professional-services",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-bridgepoint-tax",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 29,
    paymentTermsDays: 30,
    industry: "Tax services",
  },
  {
    id: "vendor-baseline-ps-003-monarch-payroll",
    name: "Monarch Payroll",
    category: "professional-services",
    ytdSpend: 540_000,
    ttmSpend: 650_000,
    concentrationShare: 0.0045,
    msaActive: true,
    msaId: "msa-monarch-payroll",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "HR services",
  },
  {
    id: "vendor-baseline-ps-004-emerald-translation",
    name: "Emerald Translation",
    category: "professional-services",
    ytdSpend: 240_000,
    ttmSpend: 290_000,
    concentrationShare: 0.002,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Translation services",
  },
  {
    id: "vendor-baseline-ps-005-frontier-talent",
    name: "Frontier Talent",
    category: "professional-services",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Staffing",
  },

  // ── IT baseline ──────────────────────────────────────────────────────
  {
    id: "vendor-baseline-it-cloud-001-vertex-saas",
    name: "Vertex SaaS",
    category: "IT",
    ytdSpend: 960_000,
    ttmSpend: 1_150_000,
    concentrationShare: 0.008,
    msaActive: true,
    msaId: "msa-vertex-saas",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "SaaS",
  },
  {
    id: "vendor-baseline-it-cloud-002-northbeam-data",
    name: "Northbeam Data",
    category: "IT",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-northbeam-data",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Data infrastructure",
  },
  {
    id: "vendor-baseline-it-cloud-003-arclight-security",
    name: "Arclight Security",
    category: "IT",
    ytdSpend: 600_000,
    ttmSpend: 720_000,
    concentrationShare: 0.005,
    msaActive: true,
    msaId: "msa-arclight-security",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Security",
  },
  {
    id: "vendor-baseline-it-cloud-004-azimuth-devtools",
    name: "Azimuth DevTools",
    category: "IT",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Developer tools",
  },
  {
    id: "vendor-baseline-it-cloud-005-quartz-hosting",
    name: "Quartz Hosting",
    category: "IT",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: true,
    msaId: "msa-quartz-hosting",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Hosting",
  },

  // ── facilities baseline ──────────────────────────────────────────────
  {
    id: "vendor-baseline-fac-001-prairie-hvac",
    name: "Prairie HVAC",
    category: "facilities",
    ytdSpend: 600_000,
    ttmSpend: 720_000,
    concentrationShare: 0.005,
    msaActive: true,
    msaId: "msa-prairie-hvac",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Facilities management",
  },
  {
    id: "vendor-baseline-fac-002-acme-cleaning",
    name: "Acme Cleaning Services",
    category: "facilities",
    ytdSpend: 540_000,
    ttmSpend: 650_000,
    concentrationShare: 0.0045,
    msaActive: true,
    msaId: "msa-acme-cleaning",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Facilities management",
  },
  {
    id: "vendor-baseline-fac-003-greenleaf-grounds",
    name: "Greenleaf Grounds",
    category: "facilities",
    ytdSpend: 300_000,
    ttmSpend: 360_000,
    concentrationShare: 0.0025,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Landscaping",
  },
  {
    id: "vendor-baseline-fac-004-shoreline-security",
    name: "Shoreline Security",
    category: "facilities",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: true,
    msaId: "msa-shoreline-security",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Physical security",
  },
  {
    id: "vendor-baseline-fac-005-mountainview-waste",
    name: "Mountainview Waste",
    category: "facilities",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: true,
    msaId: "msa-mountainview-waste",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Waste management",
  },

  // ── marketing baseline ───────────────────────────────────────────────
  {
    id: "vendor-baseline-mkt-001-lighthouse-media",
    name: "Lighthouse Media",
    category: "marketing",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-lighthouse-media",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Media buying",
  },
  {
    id: "vendor-baseline-mkt-002-falcon-creative",
    name: "Falcon Creative",
    category: "marketing",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-falcon-creative",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Creative agency",
  },
  {
    id: "vendor-baseline-mkt-003-aurora-digital",
    name: "Aurora Digital",
    category: "marketing",
    ytdSpend: 540_000,
    ttmSpend: 650_000,
    concentrationShare: 0.0045,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 33,
    paymentTermsDays: 30,
    industry: "Digital marketing",
  },
  {
    id: "vendor-baseline-mkt-004-tidewater-events",
    name: "Tidewater Events",
    category: "marketing",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Events",
  },

  // ── logistics baseline ───────────────────────────────────────────────
  {
    id: "vendor-baseline-log-001-eastwind-freight",
    name: "Eastwind Freight",
    category: "logistics",
    ytdSpend: 840_000,
    ttmSpend: 1_010_000,
    concentrationShare: 0.007,
    msaActive: true,
    msaId: "msa-eastwind-freight",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Freight",
  },
  {
    id: "vendor-baseline-log-002-cascade-warehousing",
    name: "Cascade Warehousing",
    category: "logistics",
    ytdSpend: 840_000,
    ttmSpend: 1_010_000,
    concentrationShare: 0.007,
    msaActive: true,
    msaId: "msa-cascade-warehousing",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Warehousing",
  },
  {
    id: "vendor-baseline-log-003-redhawk-courier",
    name: "Redhawk Courier",
    category: "logistics",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Courier",
  },
  {
    id: "vendor-baseline-log-004-silverlake-trucking",
    name: "Silverlake Trucking",
    category: "logistics",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Trucking",
  },

  // ── office-supplies baseline ─────────────────────────────────────────
  {
    id: "vendor-baseline-off-001-meadowbrook-paper",
    name: "Meadowbrook Paper",
    category: "office-supplies",
    ytdSpend: 240_000,
    ttmSpend: 290_000,
    concentrationShare: 0.002,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 33,
    paymentTermsDays: 30,
    industry: "Office supplies",
  },
  {
    id: "vendor-baseline-off-002-glacier-print",
    name: "Glacier Print",
    category: "office-supplies",
    ytdSpend: 180_000,
    ttmSpend: 220_000,
    concentrationShare: 0.0015,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 32,
    paymentTermsDays: 30,
    industry: "Office supplies",
  },
  {
    id: "vendor-baseline-off-003-cedarpoint-furniture",
    name: "Cedarpoint Furniture",
    category: "office-supplies",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: true,
    msaId: "msa-cedarpoint-furniture",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Office furniture",
  },

  // ── travel baseline ──────────────────────────────────────────────────
  {
    id: "vendor-baseline-trv-001-aspen-airfare",
    name: "Aspen Airfare",
    category: "travel",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Travel",
  },
  {
    id: "vendor-baseline-trv-002-cobblestone-hotels",
    name: "Cobblestone Hotels",
    category: "travel",
    ytdSpend: 240_000,
    ttmSpend: 290_000,
    concentrationShare: 0.002,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Hospitality",
  },
  {
    id: "vendor-baseline-trv-003-summit-rentals",
    name: "Summit Auto Rentals",
    category: "travel",
    ytdSpend: 180_000,
    ttmSpend: 220_000,
    concentrationShare: 0.0015,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Vehicle rental",
  },

  // ── legal baseline ───────────────────────────────────────────────────
  {
    id: "vendor-baseline-leg-001-amberglass-counsel",
    name: "Amberglass Counsel",
    category: "legal",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-amberglass-counsel",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 29,
    paymentTermsDays: 30,
    industry: "Legal services",
  },
  {
    id: "vendor-baseline-leg-002-ironbridge-litigation",
    name: "Ironbridge Litigation",
    category: "legal",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: true,
    msaId: "msa-ironbridge-litigation",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Legal services",
  },
  {
    id: "vendor-baseline-leg-003-northstar-ip",
    name: "Northstar IP Counsel",
    category: "legal",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: true,
    msaId: "msa-northstar-ip",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Legal services",
  },

  // ── other baseline ───────────────────────────────────────────────────
  {
    id: "vendor-baseline-oth-001-bluefern-charity",
    name: "Bluefern Charity Partners",
    category: "other",
    ytdSpend: 240_000,
    ttmSpend: 290_000,
    concentrationShare: 0.002,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Charity",
  },
  {
    id: "vendor-baseline-oth-002-quartzfield-research",
    name: "Quartzfield Research Co-op",
    category: "other",
    ytdSpend: 180_000,
    ttmSpend: 220_000,
    concentrationShare: 0.0015,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Research",
  },
  {
    id: "vendor-baseline-oth-003-glassbrook-membership",
    name: "Glassbrook Membership Dues",
    category: "other",
    ytdSpend: 120_000,
    ttmSpend: 145_000,
    concentrationShare: 0.001,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Memberships",
  },

  // ── extra baseline mid-spend vendors to reach ~$120M total ─────────────
  {
    id: "vendor-baseline-it-006-ferndale-machinery",
    name: "Ferndale Machinery",
    category: "industrial-tools",
    ytdSpend: 900_000,
    ttmSpend: 1_080_000,
    concentrationShare: 0.0075,
    msaActive: true,
    msaId: "msa-ferndale-machinery",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Industrial machinery",
  },
  {
    id: "vendor-baseline-it-007-rockport-castings",
    name: "Rockport Castings",
    category: "industrial-tools",
    ytdSpend: 960_000,
    ttmSpend: 1_150_000,
    concentrationShare: 0.008,
    msaActive: true,
    msaId: "msa-rockport-castings",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Castings",
  },
  {
    id: "vendor-baseline-it-008-westvalley-electrical",
    name: "Westvalley Electrical",
    category: "industrial-tools",
    ytdSpend: 720_000,
    ttmSpend: 870_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-westvalley-electrical",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Electrical",
  },
  {
    id: "vendor-baseline-log-005-bayshore-marine",
    name: "Bayshore Marine Freight",
    category: "logistics",
    ytdSpend: 600_000,
    ttmSpend: 720_000,
    concentrationShare: 0.005,
    msaActive: true,
    msaId: "msa-bayshore-marine",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Marine freight",
  },
  {
    id: "vendor-baseline-it-009-canyon-systems",
    name: "Canyon Systems",
    category: "IT",
    ytdSpend: 480_000,
    ttmSpend: 580_000,
    concentrationShare: 0.004,
    msaActive: true,
    msaId: "msa-canyon-systems",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Systems integration",
  },
  {
    id: "vendor-baseline-fac-006-juniper-utilities",
    name: "Juniper Utilities",
    category: "facilities",
    ytdSpend: 720_000,
    ttmSpend: 860_000,
    concentrationShare: 0.006,
    msaActive: true,
    msaId: "msa-juniper-utilities",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Utilities",
  },
  {
    id: "vendor-baseline-ps-006-keystone-recruiting",
    name: "Keystone Recruiting",
    category: "professional-services",
    ytdSpend: 360_000,
    ttmSpend: 430_000,
    concentrationShare: 0.003,
    msaActive: true,
    msaId: "msa-keystone-recruiting",
    isPreferredForCategory: false,
    elasticityTier: "standard",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Recruiting",
  },
  {
    id: "vendor-baseline-trv-004-pacific-coast-rail",
    name: "Pacific Coast Rail Travel",
    category: "travel",
    ytdSpend: 120_000,
    ttmSpend: 144_000,
    concentrationShare: 0.001,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 31,
    paymentTermsDays: 30,
    industry: "Rail travel",
  },
  {
    id: "vendor-baseline-oth-004-foundry-subscriptions",
    name: "Foundry Subscriptions",
    category: "other",
    ytdSpend: 96_000,
    ttmSpend: 115_000,
    concentrationShare: 0.0008,
    msaActive: false,
    isPreferredForCategory: false,
    elasticityTier: "long-tail",
    averageDaysToPay: 30,
    paymentTermsDays: 30,
    industry: "Subscriptions",
  },
]

// ════════════════════════════════════════════════════════════════════════
// Indexed lookups (consumed by derive.ts + screens)
// ════════════════════════════════════════════════════════════════════════

const VENDOR_INDEX: Record<VendorId, Vendor> = SEED_VENDORS.reduce(
  (acc, vendor) => {
    acc[vendor.id] = vendor
    return acc
  },
  {} as Record<VendorId, Vendor>,
)

export function getVendor(id: VendorId): Vendor | undefined {
  return VENDOR_INDEX[id]
}

export function getVendorsByCategory(cat: SpendCategory): Vendor[] {
  return SEED_VENDORS.filter((vendor) => vendor.category === cat)
}
