// 50 fictional B2B customers for the cash-app demo. Hand-written so Neo's reasoning
// has realistic agreement clauses and payment-behavior signals to reference.
//
// Source of truth: docs/handoff/cash-app/04-data-model.md § "lib/cash-app/seed-customers.ts".
// Hero customer (cust-acme-industrial) is the verbatim spec — do not edit copy without
// also updating the demo script (docs/handoff/cash-app/05-demo-script.md).

import type { Customer, CustomerId } from "./types"

export const SEED_CUSTOMERS: Customer[] = [
  // ── Hero customer ─────────────────────────────────────────────────────
  {
    id: "cust-acme-industrial",
    name: "Acme Industrial Supplies",
    domain: "acmeindustrial.com",
    primaryContactName: "Sarah Chen",
    primaryContactEmail: "ar@acmeindustrial.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§4.2",
        text: "Buyer may deduct freight charges if delivered later than agreed ship date.",
        relatesTo: "FREIGHT_DISCOUNT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Multi-invoice, freight discount avg $620 (range $400-$870)",
      averageDaysToPay: 42,
      multiInvoicePaymentLikelihood: 0.75,
    },
  },

  // ── Other dashboard short-pay customers ───────────────────────────────
  {
    id: "cust-pacific-distribution",
    name: "Pacific Distribution Co",
    domain: "pacificdist.com",
    primaryContactName: "Marcus Reed",
    primaryContactEmail: "ap@pacificdist.com",
    paymentTermsDays: 45,
    agreementClauses: [
      {
        section: "§7.1",
        text: "Buyer may credit returned goods against current-period invoices upon RMA confirmation.",
        relatesTo: "RETURN_CREDIT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Returns offset, avg $1,100/month",
      averageDaysToPay: 48,
      multiInvoicePaymentLikelihood: 0.4,
    },
  },
  {
    id: "cust-northeast-supply",
    name: "Northeast Supply Group",
    domain: "nesupply.com",
    primaryContactName: "Linda Park",
    primaryContactEmail: "accounts@nesupply.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§3.4",
        text: "Wire fees are deducted at source; buyer remits net of bank charges.",
        relatesTo: "BANK_FEE",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Wire-fee net deductions, $50-$120 per payment",
      averageDaysToPay: 28,
      multiInvoicePaymentLikelihood: 0.2,
    },
  },
  {
    id: "cust-westpoint-mfg",
    name: "Westpoint Manufacturing",
    domain: "westpointmfg.com",
    primaryContactName: "Diego Alvarez",
    primaryContactEmail: "ar@westpointmfg.com",
    paymentTermsDays: 60,
    agreementClauses: [
      {
        section: "§5.6",
        text: "Tier-3 volume rebate applies when quarterly purchases exceed $500K (2.5% of period spend).",
        relatesTo: "VOLUME_TIER_DISCOUNT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Quarterly volume rebate, $300-$650 per multi-invoice batch",
      averageDaysToPay: 55,
      multiInvoicePaymentLikelihood: 0.85,
    },
  },

  // ── Unapplied / dashboard payer cases ─────────────────────────────────
  {
    id: "cust-atlantic-industrial-logistics",
    name: "Atlantic Industrial Logistics Co",
    domain: "atlanticindlog.com",
    primaryContactName: "Priya Krishnan",
    primaryContactEmail: "billing@atlanticindlog.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§2.3",
        text: "Buyer remits via wholly-owned subsidiary 'Atlantic Logistics LLC' for freight-only invoices.",
        relatesTo: "CUSTOMER_NAME_MISMATCH",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Wholly-owned subsidiary remits as 'Atlantic Logistics LLC'",
      averageDaysToPay: 35,
      multiInvoicePaymentLikelihood: 0.6,
    },
  },

  // ── Other customers with agreement clauses (10+ total with clauses) ──
  {
    id: "cust-northstar-building",
    name: "Northstar Building Materials",
    domain: "northstarbm.com",
    primaryContactName: "Alex Tan",
    primaryContactEmail: "ap@northstarbm.com",
    paymentTermsDays: 45,
    agreementClauses: [
      {
        section: "§6.1",
        text: "2% discount available for payment within 10 days of invoice (2/10 net 45).",
        relatesTo: "EARLY_PAY_DISCOUNT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Takes 2/10 early-pay discount on ~60% of invoices",
      averageDaysToPay: 11,
      multiInvoicePaymentLikelihood: 0.55,
    },
  },
  {
    id: "cust-sunbelt-services",
    name: "Sunbelt Services Group",
    domain: "sunbeltsvc.com",
    primaryContactName: "Renee Holcomb",
    primaryContactEmail: "ar@sunbeltsvc.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§4.5",
        text: "Disputed line items are deducted pending resolution; balance remits net.",
        relatesTo: "DISPUTED_LINE",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Frequent line-item disputes, avg $2,400 per dispute",
      averageDaysToPay: 38,
      multiInvoicePaymentLikelihood: 0.5,
    },
  },
  {
    id: "cust-greatlakes-distribution",
    name: "Great Lakes Distribution",
    domain: "greatlakesdist.com",
    primaryContactName: "Henry Wojcik",
    primaryContactEmail: "accounting@greatlakesdist.com",
    paymentTermsDays: 60,
    agreementClauses: [
      {
        section: "§3.2",
        text: "Approved partial-payment plan: 40% on receipt, 30% at day 30, 30% at day 60.",
        relatesTo: "PARTIAL_PAYMENT_AGREED",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Pre-arranged 3-tranche schedule per master agreement",
      averageDaysToPay: 50,
      multiInvoicePaymentLikelihood: 0.3,
    },
  },
  {
    id: "cust-coastal-foods",
    name: "Coastal Foods Wholesale",
    domain: "coastalfoodswh.com",
    primaryContactName: "Yuki Tanaka",
    primaryContactEmail: "ap@coastalfoodswh.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§4.7",
        text: "Buyer may deduct freight charges for cold-chain deliveries arriving above 38°F at dock receipt.",
        relatesTo: "FREIGHT_DISCOUNT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Cold-chain freight deduction on ~25% of multi-invoice runs",
      averageDaysToPay: 33,
      multiInvoicePaymentLikelihood: 0.7,
    },
  },
  {
    id: "cust-redmesa-equipment",
    name: "Red Mesa Equipment Rentals",
    domain: "redmesaeq.com",
    primaryContactName: "Tom Buchanan",
    primaryContactEmail: "ar@redmesaeq.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§5.2",
        text: "Volume rebate: 1.5% on annual spend over $1M, applied as deduction on Q4 invoices.",
        relatesTo: "VOLUME_TIER_DISCOUNT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Annual rebate deduction in Q4, ~$15K/year",
      averageDaysToPay: 31,
      multiInvoicePaymentLikelihood: 0.45,
    },
  },
  {
    id: "cust-bayside-medical",
    name: "Bayside Medical Supply",
    domain: "baysidemed.com",
    primaryContactName: "Aditi Sharma",
    primaryContactEmail: "ap@baysidemed.com",
    paymentTermsDays: 45,
    agreementClauses: [
      {
        section: "§3.1",
        text: "Returns within 60 days credited against next invoice cycle.",
        relatesTo: "RETURN_CREDIT",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Monthly return credits, $400-$1,200",
      averageDaysToPay: 47,
      multiInvoicePaymentLikelihood: 0.35,
    },
  },
  {
    id: "cust-summitline-mfg",
    name: "Summitline Manufacturing",
    domain: "summitlinemfg.com",
    primaryContactName: "Robert Kershaw",
    primaryContactEmail: "ar@summitlinemfg.com",
    paymentTermsDays: 30,
    agreementClauses: [
      {
        section: "§4.4",
        text: "Buyer remits net of $35 wire-transfer fee per ACH origination.",
        relatesTo: "BANK_FEE",
      },
    ],
    paymentBehavior: {
      typicalShortPayPattern: "Net-of-wire-fee, exactly $35 per payment",
      averageDaysToPay: 29,
      multiInvoicePaymentLikelihood: 0.25,
    },
  },

  // ── 38 more customers — payment behavior only, no agreement clauses ──
  {
    id: "cust-ironforge-tools",
    name: "Ironforge Tooling",
    domain: "ironforgetools.com",
    primaryContactName: "Caitlin Ramos",
    primaryContactEmail: "ap@ironforgetools.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Clean payer", averageDaysToPay: 27, multiInvoicePaymentLikelihood: 0.2 },
  },
  {
    id: "cust-evergreen-paper",
    name: "Evergreen Paper Products",
    domain: "evergreenpp.com",
    primaryContactName: "Daniel Ofori",
    primaryContactEmail: "ar@evergreenpp.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Reliable, slightly slow", averageDaysToPay: 52, multiInvoicePaymentLikelihood: 0.3 },
  },
  {
    id: "cust-meridian-electric",
    name: "Meridian Electric Supply",
    domain: "meridianelectric.com",
    primaryContactName: "Sasha Volkov",
    primaryContactEmail: "ap@meridianelectric.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "On time, single-invoice payments", averageDaysToPay: 30, multiInvoicePaymentLikelihood: 0.1 },
  },
  {
    id: "cust-pinnacle-logistics",
    name: "Pinnacle Logistics Partners",
    domain: "pinnaclelog.com",
    primaryContactName: "Marcus Whitfield",
    primaryContactEmail: "ar@pinnaclelog.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Bundled monthly remits", averageDaysToPay: 58, multiInvoicePaymentLikelihood: 0.9 },
  },
  {
    id: "cust-cascade-chemicals",
    name: "Cascade Chemicals",
    domain: "cascadechem.com",
    primaryContactName: "Vinod Reddy",
    primaryContactEmail: "accounts@cascadechem.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Slow but predictable", averageDaysToPay: 41, multiInvoicePaymentLikelihood: 0.4 },
  },
  {
    id: "cust-driftwood-hospitality",
    name: "Driftwood Hospitality Group",
    domain: "driftwoodhg.com",
    primaryContactName: "Elena Kovac",
    primaryContactEmail: "ap@driftwoodhg.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Multi-property batched payments", averageDaysToPay: 44, multiInvoicePaymentLikelihood: 0.8 },
  },
  {
    id: "cust-stonebridge-construction",
    name: "Stonebridge Construction",
    domain: "stonebridgeconst.com",
    primaryContactName: "Gabriela Mendez",
    primaryContactEmail: "billing@stonebridgeconst.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Project-milestone batched", averageDaysToPay: 62, multiInvoicePaymentLikelihood: 0.65 },
  },
  {
    id: "cust-clearwater-pharma",
    name: "Clearwater Pharmaceuticals",
    domain: "clearwaterpharma.com",
    primaryContactName: "Otis Wilkerson",
    primaryContactEmail: "ar@clearwaterpharma.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Always on time, never short", averageDaysToPay: 26, multiInvoicePaymentLikelihood: 0.15 },
  },
  {
    id: "cust-blueridge-textiles",
    name: "Blue Ridge Textiles",
    domain: "blueridgetextiles.com",
    primaryContactName: "Hana Yoshida",
    primaryContactEmail: "ap@blueridgetextiles.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Sporadic remittance documentation", averageDaysToPay: 49, multiInvoicePaymentLikelihood: 0.55 },
  },
  {
    id: "cust-grandview-hardware",
    name: "Grandview Hardware Supply",
    domain: "grandviewhw.com",
    primaryContactName: "Ricky Owens",
    primaryContactEmail: "ar@grandviewhw.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Single-invoice clean payer", averageDaysToPay: 28, multiInvoicePaymentLikelihood: 0.05 },
  },
  {
    id: "cust-harborside-metals",
    name: "Harborside Metals",
    domain: "harborsidemetals.com",
    primaryContactName: "Devorah Klein",
    primaryContactEmail: "accounts@harborsidemetals.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Quarterly batched, late by 5-10 days", averageDaysToPay: 67, multiInvoicePaymentLikelihood: 0.95 },
  },
  {
    id: "cust-trailhead-outdoor",
    name: "Trailhead Outdoor Gear",
    domain: "trailheadoutdoor.com",
    primaryContactName: "Bryce Calderón",
    primaryContactEmail: "ap@trailheadoutdoor.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Seasonal volume swings (Q2/Q3 heavy)", averageDaysToPay: 34, multiInvoicePaymentLikelihood: 0.5 },
  },
  {
    id: "cust-silverline-aviation",
    name: "Silverline Aviation Services",
    domain: "silverlineaviation.com",
    primaryContactName: "Margot Pelletier",
    primaryContactEmail: "ar@silverlineaviation.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Wire-only payments, clean", averageDaysToPay: 38, multiInvoicePaymentLikelihood: 0.3 },
  },
  {
    id: "cust-magnolia-dairy",
    name: "Magnolia Dairy Cooperative",
    domain: "magnoliadairy.coop",
    primaryContactName: "Eleanor Babcock",
    primaryContactEmail: "accounts@magnoliadairy.coop",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Bi-weekly batched", averageDaysToPay: 32, multiInvoicePaymentLikelihood: 0.7 },
  },
  {
    id: "cust-cobaltridge-mining",
    name: "Cobalt Ridge Mining",
    domain: "cobaltridge.com",
    primaryContactName: "Wesley Otieno",
    primaryContactEmail: "ar@cobaltridge.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Long terms, generally on time", averageDaysToPay: 60, multiInvoicePaymentLikelihood: 0.4 },
  },
  {
    id: "cust-fieldcrest-agri",
    name: "Fieldcrest Agricultural Supply",
    domain: "fieldcrestag.com",
    primaryContactName: "Dolores Ramirez",
    primaryContactEmail: "ap@fieldcrestag.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Harvest-cycle payment timing", averageDaysToPay: 51, multiInvoicePaymentLikelihood: 0.6 },
  },
  {
    id: "cust-windrose-marine",
    name: "Windrose Marine Equipment",
    domain: "windrosemarine.com",
    primaryContactName: "Cole Sundgren",
    primaryContactEmail: "ar@windrosemarine.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Reliable single-invoice", averageDaysToPay: 30, multiInvoicePaymentLikelihood: 0.2 },
  },
  {
    id: "cust-bristol-printing",
    name: "Bristol Commercial Printing",
    domain: "bristolprint.com",
    primaryContactName: "Shawna Mendel",
    primaryContactEmail: "ap@bristolprint.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Late, missing remittance ~20% of payments", averageDaysToPay: 43, multiInvoicePaymentLikelihood: 0.35 },
  },
  {
    id: "cust-aspenglow-resorts",
    name: "Aspenglow Resorts",
    domain: "aspenglowresorts.com",
    primaryContactName: "Tobias Reinhart",
    primaryContactEmail: "ar@aspenglowresorts.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Multi-property bundled", averageDaysToPay: 46, multiInvoicePaymentLikelihood: 0.85 },
  },
  {
    id: "cust-keystone-grocers",
    name: "Keystone Grocers",
    domain: "keystonegrocers.com",
    primaryContactName: "Marisol Aguilar",
    primaryContactEmail: "accounts@keystonegrocers.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Weekly payment runs", averageDaysToPay: 27, multiInvoicePaymentLikelihood: 0.75 },
  },
  {
    id: "cust-thornwood-furniture",
    name: "Thornwood Furniture Co",
    domain: "thornwoodfurn.com",
    primaryContactName: "Jasper Lin",
    primaryContactEmail: "ap@thornwoodfurn.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Slow but pays in full", averageDaysToPay: 65, multiInvoicePaymentLikelihood: 0.4 },
  },
  {
    id: "cust-vanguard-security",
    name: "Vanguard Security Systems",
    domain: "vanguardsec.com",
    primaryContactName: "Adrienne Czarnecki",
    primaryContactEmail: "ar@vanguardsec.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Monthly subscription bundled", averageDaysToPay: 31, multiInvoicePaymentLikelihood: 0.55 },
  },
  {
    id: "cust-twinpines-lumber",
    name: "Twin Pines Lumber",
    domain: "twinpineslumber.com",
    primaryContactName: "Casey Birdwell",
    primaryContactEmail: "billing@twinpineslumber.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Fast payer, occasionally early", averageDaysToPay: 22, multiInvoicePaymentLikelihood: 0.25 },
  },
  {
    id: "cust-meridian-fitness",
    name: "Meridian Fitness Equipment",
    domain: "meridianfit.com",
    primaryContactName: "Roman Avalos",
    primaryContactEmail: "ar@meridianfit.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Single-invoice, on time", averageDaysToPay: 29, multiInvoicePaymentLikelihood: 0.15 },
  },
  {
    id: "cust-stratoview-aerospace",
    name: "Stratoview Aerospace",
    domain: "stratoview.com",
    primaryContactName: "Imani Okafor",
    primaryContactEmail: "ar@stratoview.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Long-cycle, large payments", averageDaysToPay: 64, multiInvoicePaymentLikelihood: 0.45 },
  },
  {
    id: "cust-foundry-auto-parts",
    name: "Foundry Auto Parts",
    domain: "foundryautoparts.com",
    primaryContactName: "Damaris Schroeder",
    primaryContactEmail: "ap@foundryautoparts.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Multi-warehouse bundled", averageDaysToPay: 47, multiInvoicePaymentLikelihood: 0.8 },
  },
  {
    id: "cust-lighthouse-publishing",
    name: "Lighthouse Publishing",
    domain: "lighthousepub.com",
    primaryContactName: "Quincy Marlowe",
    primaryContactEmail: "ar@lighthousepub.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Quarterly royalty reconciliation", averageDaysToPay: 38, multiInvoicePaymentLikelihood: 0.5 },
  },
  {
    id: "cust-rivercrest-banking",
    name: "Rivercrest Banking Services",
    domain: "rivercrestbank.com",
    primaryContactName: "Augustine Holloway",
    primaryContactEmail: "ap@rivercrestbank.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Wire-only, predictable", averageDaysToPay: 40, multiInvoicePaymentLikelihood: 0.35 },
  },
  {
    id: "cust-hawthorne-dental",
    name: "Hawthorne Dental Supply",
    domain: "hawthornedental.com",
    primaryContactName: "Beatriz Quintero",
    primaryContactEmail: "ar@hawthornedental.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Monthly bundled, on time", averageDaysToPay: 30, multiInvoicePaymentLikelihood: 0.6 },
  },
  {
    id: "cust-merrybrook-bakery",
    name: "Merrybrook Bakery Group",
    domain: "merrybrookbakery.com",
    primaryContactName: "Calvin Pendleton",
    primaryContactEmail: "ar@merrybrookbakery.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Daily-fresh delivery, weekly remits", averageDaysToPay: 14, multiInvoicePaymentLikelihood: 0.85 },
  },
  {
    id: "cust-foggy-harbor-shipping",
    name: "Foggy Harbor Shipping",
    domain: "foggyharbor.com",
    primaryContactName: "Saoirse O'Bannon",
    primaryContactEmail: "accounts@foggyharbor.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Bunkers-and-fees occasional shorts", averageDaysToPay: 49, multiInvoicePaymentLikelihood: 0.45 },
  },
  {
    id: "cust-burnsidehill-coffee",
    name: "Burnside Hill Coffee Roasters",
    domain: "burnsidehill.coffee",
    primaryContactName: "Mateo Velasquez",
    primaryContactEmail: "ar@burnsidehill.coffee",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Café-chain bundled, monthly", averageDaysToPay: 32, multiInvoicePaymentLikelihood: 0.7 },
  },
  {
    id: "cust-orionstar-software",
    name: "Orionstar Software Solutions",
    domain: "orionstarsoft.com",
    primaryContactName: "Emiliana Ruszowski",
    primaryContactEmail: "ap@orionstarsoft.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Subscription-bundled, clean", averageDaysToPay: 26, multiInvoicePaymentLikelihood: 0.5 },
  },
  {
    id: "cust-cedarvalley-retail",
    name: "Cedar Valley Retail Group",
    domain: "cedarvalleyretail.com",
    primaryContactName: "Booker Tatum",
    primaryContactEmail: "ar@cedarvalleyretail.com",
    paymentTermsDays: 45,
    paymentBehavior: { typicalShortPayPattern: "Multi-store, occasional missing remits", averageDaysToPay: 48, multiInvoicePaymentLikelihood: 0.75 },
  },
  {
    id: "cust-gulfshore-energy",
    name: "Gulfshore Energy Partners",
    domain: "gulfshore-energy.com",
    primaryContactName: "Marquis DuBois",
    primaryContactEmail: "ar@gulfshore-energy.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Large wires, predictable", averageDaysToPay: 55, multiInvoicePaymentLikelihood: 0.4 },
  },
  {
    id: "cust-skyharbor-logistics",
    name: "Sky Harbor Logistics",
    domain: "skyharborlog.com",
    primaryContactName: "Garrison Wexley",
    primaryContactEmail: "ap@skyharborlog.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Reliable, single-invoice clean", averageDaysToPay: 28, multiInvoicePaymentLikelihood: 0.2 },
  },
  {
    id: "cust-woodlandcrest-toys",
    name: "Woodland Crest Toys",
    domain: "woodlandcresttoys.com",
    primaryContactName: "Fern Aldridge",
    primaryContactEmail: "ar@woodlandcresttoys.com",
    paymentTermsDays: 60,
    paymentBehavior: { typicalShortPayPattern: "Q4-heavy, slow Q1 payments", averageDaysToPay: 68, multiInvoicePaymentLikelihood: 0.6 },
  },
  {
    id: "cust-emberlight-candles",
    name: "Emberlight Candle Co",
    domain: "emberlightcandles.com",
    primaryContactName: "Soledad Marchetti",
    primaryContactEmail: "ap@emberlightcandles.com",
    paymentTermsDays: 30,
    paymentBehavior: { typicalShortPayPattern: "Boutique cycle, holiday spike", averageDaysToPay: 35, multiInvoicePaymentLikelihood: 0.4 },
  },
]

const CUSTOMER_INDEX: Record<CustomerId, Customer> = SEED_CUSTOMERS.reduce(
  (acc, c) => {
    acc[c.id] = c
    return acc
  },
  {} as Record<CustomerId, Customer>,
)

export function getCustomer(id: CustomerId): Customer | undefined {
  return CUSTOMER_INDEX[id]
}
